### ISSUE TITLE
iview-admin首页对Safari不友好

### ISSUE THREAD

**Issue by dhcbox** [iview/iview-admin#1008]
iview-admin首页对Safari不友好，Chrome和Firefox没问题。如下图：
![snip20181007_1](https://user-images.githubusercontent.com/7694855/46581999-5c191e80-ca73-11e8-95d0-50d65b12093a.png)

**Comment by RedStarGroup** [comment]
没错，需要自己HACK了。这个项目的问题反馈速度比较慢，也不太活跃。

**Comment by RedStarGroup** [comment]
估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。

**Comment by lison16** [comment]
> 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。

付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的

**Comment by lison16** [comment]
试了下，没发现你这样的现象
<img width="1368" alt="2018-10-09 2 34 59" src="https://user-images.githubusercontent.com/20942571/46650890-c09dc000-cbd0-11e8-9499-1285d205c949.png">

**Comment by RedStarGroup** [comment]
> > 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。
> 
> 付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的

抱歉，确实不清楚你们是怎么分工的，但并不存在什么别的目的。
不过GitHub上的提出的问题反馈比较慢是事实，其他朋友也有反映。作为一个开源项目，相信使用admin的朋友应该也不少，但既然开源了，对于大家提出的问题，有时间还是应该及时回复，没有时间精力，开源在项目上声明，告诉大家，或者也可以请社区的朋友一起帮忙完善，主要是解决问题，而不是一直杳无音信，提的问题都石沉大海相信谁都不会喜欢。

**Comment by RedStarGroup** [comment]
> > 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。
> 
> 付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的

另外关于付费论坛，我也可以谈谈个人看法，虽然不是你搞的，但是毕竟是Iview生态的一部分，作为该框架的使用者，对此表示可以部分理解，但是确实不赞成，也不认为这种做法能够走下去。

**Comment by lison16** [comment]
> > > 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。
> > 
> > 
> > 付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的
> 
> 抱歉，确实不清楚你们是怎么分工的，但并不存在什么别的目的。
> 不过GitHub上的提出的问题反馈比较慢是事实，其他朋友也有反映。作为一个开源项目，相信使用admin的朋友应该也不少，但既然开源了，对于大家提出的问题，有时间还是应该及时回复，没有时间精力，开源在项目上声明，告诉大家，或者也可以请社区的朋友一起帮忙完善，主要是希望能解决问题，而不是一直杳无音信，大家提的issues都石沉大海了，相信谁都不会喜欢。

很多通知都是在QQ群进行的，QQ群沟通起来要方便的多，比起github要便捷，当然了，issue我也会通过邮件回复，但是只会回复疑似admin的bug的，像不会使用webpack这类问题，我不会回复

**Comment by RedStarGroup** [comment]
> > > > 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。
> > > 
> > > 
> > > 付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的
> > 
> > 
> > 抱歉，确实不清楚你们是怎么分工的，但并不存在什么别的目的。
> > 不过GitHub上的提出的问题反馈比较慢是事实，其他朋友也有反映。作为一个开源项目，相信使用admin的朋友应该也不少，但既然开源了，对于大家提出的问题，有时间还是应该及时回复，没有时间精力，开源在项目上声明，告诉大家，或者也可以请社区的朋友一起帮忙完善，主要是希望能解决问题，而不是一直杳无音信，大家提的issues都石沉大海了，相信谁都不会喜欢。
> 
> 很多通知都是在QQ群进行的，QQ群沟通起来要方便的多，比起github要便捷，当然了，issue我也会通过邮件回复，但是只会回复疑似admin的bug的，像不会使用webpack这类问题，我不会回复

webpack配置之类的问题确实不需要一一回复。虽然QQ群沟通方便，但是也有弊端，一个是容易歪楼，难以控制讨论的主题，甚至很多是扯淡闲谈的内容（所以，一些人加群后不久就会退群）；二是无法有效记录与该框架使用相关的各种问题及其解决方案，会损害社区生态建设。

**Comment by lison16** [comment]
> > > 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。
> > 
> > 
> > 付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的
> 
> 另外关于付费论坛，我也可以谈谈个人看法，虽然不是你搞的，但是毕竟是Iview生态的一部分，作为该框架的使用者，对此表示可以部分理解，但是确实不赞成，也不认为这种做法能够走下去。

Aresn自己运营这个论坛，服务器等等各种成本，弄一个免费的答疑社区，谁来买单，靠微薄的广告吗，知识付费的时代而已

**Comment by RedStarGroup** [comment]
> > > > 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。
> > > 
> > > 
> > > 付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的
> > 
> > 
> > 另外关于付费论坛，我也可以谈谈个人看法，虽然不是你搞的，但是毕竟是Iview生态的一部分，作为该框架的使用者，对此表示可以部分理解，但是确实不赞成，也不认为这种做法能够走下去。
> 
> Aresn自己运营这个论坛，服务器等等各种成本，弄一个免费的答疑社区，谁来买单，靠微薄的广告吗，知识付费的时代而已

你们高兴就好

**Comment by RedStarGroup** [comment]
> > > > 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。
> > > 
> > > 
> > > 付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的
> > 
> > 
> > 另外关于付费论坛，我也可以谈谈个人看法，虽然不是你搞的，但是毕竟是Iview生态的一部分，作为该框架的使用者，对此表示可以部分理解，但是确实不赞成，也不认为这种做法能够走下去。
> 
> Aresn自己运营这个论坛，服务器等等各种成本，弄一个免费的答疑社区，谁来买单，靠微薄的广告吗，知识付费的时代而已

那种模式多半是自娱自乐，恐怕很少有人光顾。何况没有人要你们一定要搞这种论坛啊，至于服务器的支出就不要拿出来唬人了，技术论坛远远不能和新闻资讯内站点相比吧，一个轻量应用在服务器的支出上能有多少，AWS，阿里云，腾讯云的服务器价格大家都清楚。

**Comment by lison16** [comment]
> > > > > 估计是因为框架作者开了付费论坛，主要搞那个去了，GitHub的项目不再维护了。
> > > > 
> > > > 
> > > > 付费论坛是Aresn搞的，admin是我做的，我们并不是同一个人，而且这个项目也一直在维护，提交记录可以看出，不知道你这样诋毁出于什么目的
> > > 
> > > 
> > > 另外关于付费论坛，我也可以谈谈个人看法，虽然不是你搞的，但是毕竟是Iview生态的一部分，作为该框架的使用者，对此表示可以部分理解，但是确实不赞成，也不认为这种做法能够走下去。
> > 
> > 
> > Aresn自己运营这个论坛，服务器等等各种成本，弄一个免费的答疑社区，谁来买单，靠微薄的广告吗，知识付费的时代而已
> 
> 那种模式多半是自娱自乐，恐怕很少有人光顾。何况没有人要你们一定要搞这种论坛啊，至于服务器的支出就不要拿出来唬人了，技术论坛远远不能和新闻资讯内站点相比吧，一个轻量应用在服务器的支出上能有多少，AWS，阿里云，腾讯云的服务器价格大家都清楚。

反正论坛不是我搞的，我不关心

**Comment by dhcbox** [comment]
> 试了下，没发现你这样的现象
> <img alt="2018-10-09 2 34 59" width="1368" src="https://user-images.githubusercontent.com/20942571/46650890-c09dc000-cbd0-11e8-9499-1285d205c949.png">

我用的Chrome没问题，Safari确实有问题

**Comment by dhcbox** [comment]
https://github.com/iview/iview-admin/issues/1008#issuecomment-428103405
safari升级到12.0的版本就ok了

**Comment by dhcbox** [comment]
> > 试了下，没发现你这样的现象
> > <img alt="2018-10-09 2 34 59" width="1368" src="https://user-images.githubusercontent.com/20942571/46650890-c09dc000-cbd0-11e8-9499-1285d205c949.png">
> 
> 我用的Chrome没问题，Safari确实有问题

Safari的12.0版本没问题
