### ISSUE TITLE
新手求问。。打包后入口文件在哪啊？

### ISSUE THREAD

**Issue by RubbbbbY** [iview/iview-admin#103]
打包后文件好乱

**Comment by lison16** [comment]
打包后的文件是编译过的，吧index_prod.html和dist文件夹放到服务器，急着打包之前修改webpack.config.prod.js里的output.publicPath

**Comment by RubbbbbY** [comment]
修改webpack.config.prod.js里的output.publicPath有什么用？

**Comment by lison16** [comment]
建议你看一下iview-admin的配置，然后自己动手修改，如果想深入学习建议看webpack文档

**Comment by RubbbbbY** [comment]
放服务器上了，但是很多404
