### ISSUE TITLE
刷新页面会跳转到home标签页

### ISSUE THREAD

**Issue by bloodbook** [iview/iview-admin#1031]
2.0.0-beta8版本刷新页面会关闭除home页所有标签页并跳转到home标签页

**Comment by lison16** [comment]
更新到最新代码再试试

**Comment by zjxszw** [comment]
同问，我也是这样

**Comment by tylerrrkd** [comment]
@lison16 哥们儿方便说下是哪个commit的版本修复了这个问题么，同样使用了2.0.0-beta8进行开发的，也遇到了这个问题，但是项目已经进行到一半了，想根据commit记录修改。谢谢您。iview-admin无敌！

**Comment by tylerrrkd** [comment]
@lison16 是这个版本吗？[修复白屏](https://github.com/iview/iview-admin/commit/c2d3969ac76de8a6efd5218d8527d90b735e829f)

**Comment by tylerrrkd** [comment]
@DamonSnow  好的 谢谢你 哥们儿

**Comment by tylerrrkd** [comment]
@DamonSnow Thank you my friend, it works.
