### ISSUE TITLE
求指教，怎么修改端口号。

### ISSUE THREAD

**Issue by Jam1zhu** [iview/iview-admin#104]
RT，小白，求大神赐教

**Comment by lingdang2017** [comment]
https://github.com/iview/iview-admin/issues/106
我把iview-admin的端口改成了80，可以看看。代理不需要就删掉proxy吧

**Comment by Jam1zhu** [comment]
@lingdang2017 谢谢🙏

**Comment by tkucn** [comment]
node_modules\webpack-dev-server\bin\webpack-dev-server.js 下面的：

const DEFAULT_PORT = 8080;
