### ISSUE TITLE
iview-admin项目架构一些建议

### ISSUE THREAD

**Issue by leixuesong** [iview/iview-admin#1059]
**a、login-form组件可以直接写在login页面。**
1、这个login-form组件复用的可能性比较小。
2、如果login-form组件放在src/components里面，会让人难以理解，也让代码结构增加不比较的阅读麻烦
3、公用性很小的建议就写在页面里面，不然在学习代码和编程的时候就会不停的换文件夹和文件，无形中添加了一些麻烦。

**b、view里面的文件及结构优化**
/view/components/count-to/count-to.vue可以调整为/view/components/count-to.vue，因为基本每个vue文件包含了template,script和style。没有必要用一个文件夹，大部分情况一个vue页面就足够。整个菜单页面结构可以设置为，一级菜单为文件夹，如果有三级菜单，则三级菜单的父级二级菜单为文件夹，其余二级菜单为vue文件。这样更符合菜单逻辑。

**c、iview-admin的权限比较鸡肋，因为一般的项目都是有权限显示菜单，没权限就不显示这个菜单，现在权限的实现是所有的菜单显示，然后有权限就正常访问，没权限就重定向到没有权限的页面。用户体验会比较差，可以在router/routers.js里面定义不需要控制权限的静态路由，然后在libs/util.js中定义一个获取路由的方法，在router/routers.js调用该方法，然后在合并静态方法生成新的路由，导出这个新的路由，实现动态路由和菜单，达到权限控制**
希望iview-admin发展越来越好！！！感谢
@lison16

**Comment by lison16** [comment]
左侧菜单现在就是没权限的不显示，你可以用admin账号测试，现在的权限方案是权限方案中的一种，适合简单的角色系统，如果要求较高，可以改用动态挂载路由方案

**Comment by leixuesong** [comment]
好的，我试一下。
