### ISSUE TITLE
跨域请求

### ISSUE THREAD

**Issue by codeItachi** [iview/iview-admin#106]
跨域请求用util.ajax 可以吗？

**Comment by lingdang2017** [comment]
我实现跨域是改了build/webpack.dev.config.js
在devtool和output之间加下面内容（注：我改了iview-admin端口为80了，因为后台是8080，这个根据需要改吧）
    devServer: {
        inline: true,
        port: 80,
        proxy: {
            '/api': {
                target: 'http://localhost:8080',
                changeOrigin: true,
                pathRewrite: {
                    '^/api': '/'
                }
            }
        }
    }

参考的这个关闭的issue      https://github.com/iview/iview-admin/issues/46

**Comment by codeItachi** [comment]
@lingdang2017 可以看下怎么请求的吗？

**Comment by lingdang2017** [comment]
你好，我贴一段我改了login.vue里面的代码吧
let data = 'username=' + this.form.userName +
                        '&password=' + this.form.password;
                    axios.post('api/sys/login', data)
                        .then((response) => {
                            if (response.data.code === 0) {
                                this.$Message.success('登录成功!');
                            } else {
                                this.$Message.error({
                                    content: response.data.msg,
                                    duration: 4,
                                    closable: true});
                                this.$Loading.error();
                            }
                        }).catch((err) => {
                            this.$Message.error('服务器异常!');
                            this.$Loading.error();
                            this.loading = false;
                        });

api/sys/login会被换成localhost:8080/sys/login去请求后台

**Comment by codeItachi** [comment]
@lingdang2017 谢谢 我也这么写的 没请求到  我再试试

**Comment by codeItachi** [comment]
@lingdang2017 我的跨域还是不行  求指教啊

**Comment by lingdang2017** [comment]
@codeItachi  你把你跨域的配置和请求后台的这两处代码发我下，我给你瞅瞅
我的邮箱：820704815@qq.com
