### ISSUE TITLE
iview admin 2.1.1 设置服务器接口   依然请求的mock 数据

### ISSUE THREAD

**Issue by souliot** [iview/iview-admin#1073]

**Comment by souliot** [comment]
解决了  谢谢
main.js
注释掉下面这句
// if (process.env.NODE_ENV !== 'production') require('@/mock')

**Comment by StrangeClow** [comment]
注释掉会报错呀

**Comment by souliot** [comment]
需要设置服务器  数据接口   如果跨域  需要 在vue.config.js 配置  代理

在api 路径下面   配置服务器 具体请求接口
