### ISSUE TITLE
全屏之后弹框看不见

### ISSUE THREAD

**Issue by sharpfeel** [iview/iview-admin#108]

**Comment by lison16** [comment]
你指的是什么弹窗？

**Comment by luoruiqing** [comment]
Moadl(对话框) 不出现. 点击放小之后就立刻出来了.

**Comment by lison16** [comment]
OK，确实是个bug，你把main.js里handleFullscreen方法的let main = document.getElementById(‘main’)改成let main = document.body;就行了。谢谢反馈

**Comment by codeItachi** [comment]
@lison16  在main.vue文件下

**Comment by lison16** [comment]
你的不是最新版本，最新版本放到了main.js里，否则会有个bug
