### ISSUE TITLE
otherRouter 隐藏菜单不销毁

### ISSUE THREAD

**Issue by luoruiqing** [iview/iview-admin#109]
页面上通过 this.$router.push(`/dashboard/filter?name=${params.row.name}`) 跳转到隐藏菜单下的时候不销毁现在实例.
![tx38r5yqwn](https://user-images.githubusercontent.com/10202760/32102500-3c3f4298-bae2-11e7-9cdb-93b4d9ad5ae4.gif)
路由也发生了变化..但是他依然是第一次的值,是不是可以考虑加一个参数来决定这个插件是否需要重新加载?
谢谢~

**Comment by lison16** [comment]
动图太快了没太看懂

**Comment by luoruiqing** [comment]
额,左上角的按个标题对应的列表标题哈~

**Comment by lison16** [comment]
这是由于开启了页面缓存的缘故，如果你不需要页面缓存，可以删掉Main.vue里<router-view></router-view>组件外面的keep-alive组件即可，如果需要的话那你需要学习下vue的生命周期钩子  activated  和  deactivated

**Comment by luoruiqing** [comment]
嗯嗯~ 多谢大神~
