### ISSUE TITLE
BackTop组件在iView-Admin项目中无效

### ISSUE THREAD

**Issue by ulyanovsk** [iview/iview-admin#1099]
单独使用可以，但在iView-Admin项目中使用，不管放哪里，都不显示

**Comment by lison16** [comment]
因为iview-admin的 页面滚动不是整个页面的滚动，而是一个DIV容器的滚动

**Comment by ulyanovsk** [comment]
赞，issues处理一定要跟上👍

**Comment by lison16** [comment]
最新代码新增ABackTop组件，支持自定义指定滚动容器，现已加入iview-admin，滚动可显示 https://github.com/iview/iview-admin/commit/853f3d3fb88b3cffb4c744bb0f8858e8913fd3eb
[cid:8F1AD13D-AAAF-49AF-BD2D-A0982D0CC5CB]
