### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by janchengwang** [iview/iview-admin#11]
`ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Main.vue
Module not found: Error: Can't resolve './main_components/tagsPageopened.vue' in '/home/disk/workspace/vue/iview-admin/src/views'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/Main.vue 11:22-69
 @ ./src/views/Main.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/markdown-editor/markdown-editor.vue
Module not found: Error: Can't resolve 'SimpleMDE' in '/home/disk/workspace/vue/iview-admin/src/views/my_components/markdown-editor'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/markdown-editor/markdown-editor.vue 7:17-37
 @ ./src/views/my_components/markdown-editor/markdown-editor.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/count-to/CountTo.vue
Module not found: Error: Can't resolve 'countUp' in '/home/disk/workspace/vue/iview-admin/src/views/my_components/count-to'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/count-to/CountTo.vue 7:15-33
 @ ./src/views/my_components/count-to/CountTo.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/count-to/count-to.vue
 @ ./src/views/my_components/count-to/count-to.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/components/countUp.vue
Module not found: Error: Can't resolve 'countUp' in '/home/disk/workspace/vue/iview-admin/src/views/home/components'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/components/countUp.vue 7:15-33
 @ ./src/views/home/components/countUp.vue
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/views/home/home.vue
 @ ./src/views/home/home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main
`

**Comment by janchengwang** [comment]
关闭issue给个提示吧@lison16

**Comment by lison16** [comment]
不好意思哈

**Comment by janchengwang** [comment]
主要是 import SimpleMDE from 'SimpleMDE' 和 import countUp from 'countUp' 这两个地方会报Module not found。昨天晚上还clone到本地，不知道什么问题，这两个是第三方插件吧，，@lison16
