### ISSUE TITLE
首页右上角显示的用户名，若有中文字符且超长就会换行

### ISSUE THREAD

**Issue by lingdang2017** [iview/iview-admin#110]
hi:
问题描述如题，下面是例子
http://jsbin.com/sufomus/edit?html,css,js,output
目前纯文本+数字组合是会以省略号代替的。

个人拙见，一个就是参考github、gitee，直接显示头像而非用户名，Dropdown下再显示用户名；二是针对中文优化，超出长度也以省略号来代替

**Comment by lison16** [comment]
中文的用户名确实没考虑到，稍后做个处理

**Comment by lison16** [comment]
已修复

**Comment by lingdang2017** [comment]
@lison16  @RenShine  3q
