### ISSUE TITLE
config配置文件能否类似vue-cli的生成的配置一样有dev.env.js、prod.env.js?

### ISSUE THREAD

**Issue by CharlesSong** [iview/iview-admin#111]
config配置文件能否类似vue-cli的生成的配置一样有dev.env.js、prod.env.js?

**Comment by ShawshankLin** [comment]
支持加上,,还是觉得vue-cli的结构比较熟悉

**Comment by gh81997167** [comment]
端口号不知道在哪里修改 ，不能编译成index.html？

**Comment by lison16** [comment]
关于配置后面会做一下补充优化

**Comment by CharlesSong** [comment]
@lison16 关于配置啥时候能优化好呢？现在就差配置这一块了
