### ISSUE TITLE
打包之前没有删除上次打包的文件，冗余文件越来越多。

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#112]
输出路径修改到/dist/，每次打包会生产新的hash文件，与旧文件共存，文件夹越来越大。希望能优化

**Comment by ShawshankLin** [comment]
原本dist下不是有文件吗,,那么打包也会放到里面吗?还有打包后我没有看到index.html

**Comment by codeItachi** [comment]
@dolphinfine 同问怎么解决呢

**Comment by dolphinfine** [comment]
@codeItachi 手动删除dist下面的带有hash的文件。注意文件夹不可删。

**Comment by lison16** [comment]
文件夹和名字不是随机生成的那几个样式表文件不能删，暂时是需要手动把以前生成的删除，后面我们把这修改下

**Comment by SoyMeng** [comment]
改成url?h=hash的方式就可以了

**Comment by CharlesSong** [comment]
@SoyMeng 能在具体描述下么？

**Comment by SoyMeng** [comment]
@CharlesSong build文件名称的配置在/build/webpack.prod.config.js中，按照上面的方式，可以修改js名称方式为
```
output: {
        publicPath: 'https://iview.github.io/iview-admin/dist/',
        filename: '[name].js?hash=[hash]',
        chunkFilename: '[name].[hash].chunk.js'
    },
```
其他如css等可参照

**Comment by davecat** [comment]
dist文件夹下好多已经存在的文件，确实不够清爽。而且每次build以后需要手动去选择删除生成的文件，并不能直接删除dist来的快。。。希望在下个版本能看到改进。

**Comment by lison16** [comment]
预期下周会进行优化
