### ISSUE TITLE
动态路由外部打开bug

### ISSUE THREAD

**Issue by hiyoi** [iview/iview-admin#1121]
官方的例子:
随机一个动态页面
(所有操作均在chrome无痕浏览模式，避免cache)
重现步骤:
1. 新标签打开https://admin.iviewui.com/home
2. 跳转到登陆页，登陆
3. 新建一个标签打开 https://admin.iviewui.com/argu/params/89160
4. 会自动跳转到 https://admin.iviewui.com/home
而不是自动创建一个该params参数的tab页

希望能解决下

**Comment by KfcRun** [comment]
这个应该不算是bug吧，
跟登陆逻辑有关，如果需要直接通过url地址进行访问，把鉴权/登陆判断的去掉就可以了。

**Comment by hiyoi** [comment]
> 这个应该不算是bug吧，
> 跟登陆逻辑有关，如果需要直接通过url地址进行访问，把鉴权/登陆判断的去掉就可以了。

没看懂么，是跳转到home，已登陆状态。

**Comment by KfcRun** [comment]
浏览器无痕模式下，相当于新开一个浏览器，就算之前已经登陆了，也是拿不到登陆状态的。

**Comment by hiyoi** [comment]
> 浏览器无痕模式下，相当于新开一个浏览器，就算之前已经登陆了，也是拿不到登陆状态的。

应该描述的很清楚，是打开无痕浏览，然后登陆过。有cookie了
![image](https://user-images.githubusercontent.com/2487038/49986396-bb7f3780-ffaa-11e8-8634-1fa992564a86.png)

**Comment by hiyoi** [comment]
这个问题影响的应用场景：

1.  生成了一个新的订单，订单详情为动态路由url。
2. 发送邮件该url 通知给用户，用户打开url不能直接定位到该详情页

原本以为是个人配置的问题，发现官方的例子也有这个问题。。应该是个bug
