### ISSUE TITLE
如何使用iview-admin 的权限功能

### ISSUE THREAD

**Issue by leogorden** [iview/iview-admin#1123]
rouer.js 中有关于权限的规定，我想问的是我应该怎样给当前用户赋予access呢？谢谢

**Comment by KfcRun** [comment]
我觉得应该是有权限组/角色组的概念，把某一类菜单授权标识为一个权限组，类似于[‘admin’],在接口返回菜单数据时 接口封装access属性，前端只要原封不到的取数后addrouters()；就可以了。

**Comment by leogorden** [comment]
iview-admin 还处于比较早期的阶段，确实还有些问题，希望以后越来越好

**Comment by caizhiyuan** [comment]
返回来的是一个权限组，每个路由name是个键值。判断键值是否在权限组里比较方便，作者刚好相反！
