### ISSUE TITLE
simplemde不能全屏

### ISSUE THREAD

**Issue by janchengwang** [iview/iview-admin#113]
simplemde全屏的时候会被顶部跟左边的菜单栏遮住

**Comment by lison16** [comment]
这个是iview菜单组件和顶部导航条的z-index的值设置过高的问题，后面会进行修复

**Comment by luvvien** [comment]
> 这个是iview菜单组件和顶部导航条的z-index的值设置过高的问题，后面会进行修复

老板能告诉一下怎么解决吗，我没用这个项目，我是自己写的，simplemde也是被左侧顶部挡住
