### ISSUE TITLE
tag-nav切换或者关闭后chrome内存未释放

### ISSUE THREAD

**Issue by qx4235** [iview/iview-admin#1156]
使用的是当前master版本，未做代码变动，本地dev,不断发现切换首页和其他tab时，chrome内存不断上升，一直未释放
![image](https://user-images.githubusercontent.com/4419557/50534565-536b4c80-0b79-11e9-97ab-3195e71c5b2a.png)
![image](https://user-images.githubusercontent.com/4419557/50534568-58c89700-0b79-11e9-85c1-d2dc1f57f54d.png)
想问问是什么问题，有没有什么解决方案。
我们用down下来的版本做了改动后发现以上问题，在低配置机器上开上十个左右tab之后，页面卡顿明显，内存不够

**Comment by qx4235** [comment]
> keep-alive引起的。不能讲大量页面缓存起来。只能讲必要的页面进行缓存。。。

现在的做法是tag-nav控制cachePage的keep alive，master版本中以切换tab引起内存上升，现实当中发现关闭tab页面后内存也未释放，这个问题有什么方案可以解决吗

**Comment by 715476864** [comment]
我们之前遇到的情况是：开上10+个tab以后，页面就开始卡顿。
原因就是，框架默认是将所有页面都要进行缓存。于是乎我们调整了页面的缓存机制，我们在路由的meta属性中新增了keepAlive属性，将需要（而不是全部）缓存的页面keepAlive设置为true。然后在main页面将
<keep-alive>……</keep-alive>改了一下：
`<keep-alive>
                <router-view
                  v-if="this.$route.meta && this.$route.meta.keepAlive"
                  :key="'level-one'+$route.path"
                />
              </keep-alive>
              <router-view
                v-if="!(this.$route.meta && this.$route.meta.keepAlive)"
                :key="'level-one'+$route.path"
              />`
就这样，解决了这个问题。


不知道你和我们的情况是不是一样的……

**Comment by qx4235** [comment]
> 我们之前遇到的情况是：开上10+个tab以后，页面就开始卡顿。
> 原因就是，框架默认是将所有页面都要进行缓存。于是乎我们调整了页面的缓存机制，我们在路由的meta属性中新增了keepAlive属性，将需要（而不是全部）缓存的页面keepAlive设置为true。然后在main页面将
> ……改了一下：
> `<keep-alive> <router-view v-if="this.$route.meta && this.$route.meta.keepAlive" :key="'level-one'+$route.path" /> </keep-alive> <router-view v-if="!(this.$route.meta && this.$route.meta.keepAlive)" :key="'level-one'+$route.path" />`
> 就这样，解决了这个问题。
> 
> 不知道你和我们的情况是不是一样的……

非常感谢你的帮助，从描述上来看我们表现的是一致的，我采用你的方案后发现问题依旧，可能是某些地方没有做到。我将parent-view中keep alive注释，main.vue中的keep alive也注释后发现，我只打开两三个tab，来回切换时内存依旧是猛增，并没有明显的回落，关闭tab之后也是如此，这让我很疑惑。希望得到你的进一步解答或启发，十分感谢。

**Comment by 715476864** [comment]
不好意思，我们遇到卡顿的问题就是这样解决的。

**Comment by a869057476** [comment]
> 不好意思，我们遇到卡顿的问题就是这样解决的。

请问我们项目我把keep-alive去掉了内存还是不会释放，会是什么问题了

**Comment by a869057476** [comment]
今天发现是组件中引入的子组件产生的内存问题。比如说路由指向了一个一级菜单，这个一级菜单有一个弹出框的子组件，按照普通方式引入子组件后切换路由再回来每次都要增加内存，但是把这个子组件注释后发现切换路由再回来并不会增加内存了。。所以我只能在子组件中加了个v-if，根据弹出框的状态。。。有个问题是过度动画没了，但是内存问题算是解决了，不知道有没更好的方案

**Comment by 715476864** [comment]
请问：
1、你的路由是不是keepalive的呢？
2、子组件v-if是怎么弄的呢，我有点没明白，能不能把代码贴上呢？

目前我的项目依然没有彻底解决这个问题，只要我将路由全部缓存（keepalive）上就会出现这个问题，于是我只能有选择性地缓存路由，以临时解决。



坑啊，难以填补的坑！

**Comment by gjwfiza** [comment]
我也遇到了这个问题，确实关闭标签后组件确实是被destory了，但内存却没有下降

**Comment by qx4235** [comment]
这个问题目前看是无解的，反正它也商业化了，转ant或者element了，可惜了漂亮的组件
