### ISSUE TITLE
[已实现] iview-admin动态加载路由修改方法

### ISSUE THREAD

**Issue by majinkai** [iview/iview-admin#1158]
# iview-admin动态加载路由修改方法

本示例基于iview-admin的template分支修改，其他分支应该也是支持的，通过mock方式模拟后台数据，将mock数据更改为自己的后端数据格式，转换方法稍加修改即可

### @/mock/login.js中增加数据

直接将@router/routers.js中，home节点到404节点之间的数据 __剪切 __过去即可
```javascript
export const getUserMenus = req => {
  return [
    // 粘贴到这里就可以了
    // 需要把所有的component: () => import('@/view/**/*.vue')
    // 修改为component: 'view/**/*.vue'
    // 注意main和parent-view
    {
      path: '',
      name: 'doc',
      meta: {
        title: '文档',
        href: 'https://lison16.github.io/iview-admin-doc/#/',
        icon: 'ios-book'
      }
    },
    {
      path: '/multilevel',
      name: 'multilevel',
      meta: {
        icon: 'md-menu',
        title: '多级菜单'
      },
      component: 'components/main',
      children: [
        {
          path: 'level_2_1',
          name: 'level_2_1',
          meta: {
            icon: 'md-funnel',
            title: '二级-1'
          },
          component: 'view/multilevel/level-2-1.vue'
        },
        {
          path: 'level_2_2',
          name: 'level_2_2',
          meta: {
            access: ['super_admin'],
            icon: 'md-funnel',
            showAlways: true,
            title: '二级-2'
          },
          component: 'components/parent-view',
          children: [
            {
              path: 'level_2_2_1',
              name: 'level_2_2_1',
              meta: {
                icon: 'md-funnel',
                title: '三级'
              },
              component: 'view/multilevel/level-2-2/level-3-1.vue'
            }
          ]
        },
        {
          path: 'level_2_3',
          name: 'level_2_3',
          meta: {
            icon: 'md-funnel',
            title: '二级-3'
          },
          component: 'view/multilevel/level-2-3.vue'
        }
      ]
    }
  ]
}
```

### @/mock/index.js中增加解析
```javascript
Mock.mock(/\/get_user_menus/, getUserMenus)
```

### @/api/user.js中增加方法
```javascript
export const listUserMenus = () => {
  return axios.request({
    url: 'get_user_menus',
    method: 'get'
  })
}
```

### @/libs/utils.js中添加后端数据转换成路由的工具函数
```javascript
/**
 * @description 将后端菜单树转换为路由树
 * @param {Array} menus
 * @returns {Array}
 */
export const backendMenusToRouters = (menus) => {
  let routers = []
  forEach(menus, (menu) => {
    // 将后端数据转换成路由数据
    let route = backendMenuToRoute(menu)
    // 如果后端数据有下级，则递归处理下级
    if (menu.children && menu.children.length !== 0) {
      route.children = backendMenusToRouters(menu.children)
    }
    routers.push(route)
  })
  return routers
}

/**
 * @description 将后端菜单转换为路由
 * @param {Object} menu
 * @returns {Object}
 */
const backendMenuToRoute = (menu) => {
  // 具体内容根据自己的数据结构来定，这里需要注意的一点是
  // 原先routers写法是component: () => import('@/view/error-page/404.vue')
  // 经过json数据转换，这里会丢失，所以需要按照上面提过的做转换，下面只写了核心点，其他自行处理
  let route = Object.assign({}, menu)
  route.component = () => import(`@/${menu.component}`)
  return route
}
```

### @/store/module/app.js中做如下修改，只标注新增和修改的内容
```javascript
export default {
  state: {
    routers: [],
    hasGetRouter: false
  },
  getters: {
    menuList: (state) => (state, getters, rootState) => getMenuByRouter(state.routers, rootState.user.access),
  },
  mutations: {
    setRouters (state, routers) {
      state.routers = routers
    },
    setHasGetRouter (state, status) {
      state.hasGetRouter = status
    }
  },
  actions: {
    getRouters ({ commit }) {
      return new Promise((resolve, reject) => {
        try {
          listUserMenus().then(res => {
            let routers = backendMenusToRouters(res.data)
            commit('setRouters', routers)
            commit('setHasGetRouter', true)
            resolve(routers)
          }).catch(err => {
            reject(err)
          })
        } catch (error) {
          reject(error)
        }
      })
    }
  }
}
```

### @/router/index.js中，修改turnTo函数和beforeEach钩子里面最后一个else中的代码
```javascript
const turnTo = (to, access, next) => {
  if (canTurnTo(to.name, access, store.state.app.routers.concat(routes))) next() // 有权限，可访问
  else next({ replace: true, name: 'error_401' }) // 无权限，重定向到401页面
}


// 修改这部分代码
if (store.state.user.hasGetInfo && store.state.app.hasGetRouter) {
  turnTo(to, store.state.user.access, next)
} else {
  // 加载用户信息
  store.dispatch('getUserInfo').then(user => {
    // 加载用户菜单
    store.dispatch('getRouters').then(routers => {
      // commonRoutes需要追加到路由解析最后的404，把原先的routers.js中的404删掉即可
      router.addRoutes(routers.concat([
        {
          path: '*',
          name: 'error_404',
          meta: {
            hideInMenu: true
          },
          component: () => import('@/view/error-page/404.vue')
        }
      ]))
      next({ ...to })
    })
  }).catch(() => {
    setToken('')
    next({ name: 'login' })
  })
}
```

### @/components/main/components/user/user.vue中，处理注销问题
需要修改注销的代码，注销成功后跳转到登录页面，这样可以起到强制刷新的作用，清空缓存的routers
```javascript
logout () {
  this.handleLogOut().then(() => {
    window.location = '/login'
  })
}
```

**Comment by hankaibo** [comment]
👍
可以提个pr

**Comment by wulongkuan** [comment]
icon会报错

**Comment by hellosun** [comment]
我添加了 route.component = () => import(`@/${menu.component}`) 行后 npm run dev 就不行了，显示 ERR! code ELIFECYCLE，babel也添加了@babel/plugin-syntax-dynamic-import

**Comment by majinkai** [comment]
route.component = () => import(`@/${menu.component}`)

是不是少写了``

**Comment by qzzm** [comment]
http://localhost:8082/multilevel/level_2_2/level_2_2_1  比如浏览器访问未打开过的路由页面，直接返回首页，再手工点找到那页面才可以访问   如何解决能直接一次打开？

**Comment by majinkai** [comment]
@qzzm 这个问题我还真没注意，我明天看一下，应该可以解决

**Comment by majinkai** [comment]
> @majinkai
> @/router/index.js中，修改turnTo函数和beforeEach钩子里面最后一个else中的代码
> `const turnTo = (to, access, next) => { if (canTurnTo(to.name, access, store.state.app.routes.concat(routes))) next() // 有权限，可访问 else next({ replace: true, name: 'error_401' }) // 无权限，重定向到401页面 }`
> 
> 这里 `store.state.app.routes.concat(routes))` 少了个r 应改成
> 
> `const turnTo = (to, access, next) => { if (canTurnTo(to.name, access, store.state.app.routers.concat(routes))) next() // 有权限，可访问 else next({ replace: true, name: 'error_401' }) // 无权限，重定向到401页面 }`

感谢，已经改正

**Comment by qzzm** [comment]
> @qzzm 这个问题我还真没注意，我明天看一下，应该可以解决

> menuList: (state) => (state, getters, rootState) => getMenuByRouter(state.routers, rootState.user.access),
这句 我测试不正确  按以下写就能加载出左侧菜单 不要（state）=>
menuList:  (state, getters, rootState) => getMenuByRouter(state.routers, rootState.user.access),

**Comment by qzzm** [comment]
经测试 mode history 没打开过的情况下 无法直接访问url   hash 方式正常， 不知道如何兼容~

**Comment by yundingy** [comment]
route.component = () => import(`@/${menu.component}`)
这句貌似会导致编译的速度变得很慢，不知道是什么原因

**Comment by yichangle** [comment]
小白提问，后端数据什么样的格式呢？
     权限控制功能如果在前端能将路由数据扁平化后放在后端存储，管理员为不同用户赋菜单权限，打开页面时，根据用户权限，前端依据从后台读取路由数据来显示菜单，就非常棒了。
     能否将修改后的完整代码放在github上？谢谢！

**Comment by caiya** [comment]
> > route.component = () => import(`@/${menu.component}`)
> > 这句貌似会导致编译的速度变得很慢，不知道是什么原因
> 
> 我改用这方法可以编译很快
> npm install babel-plugin-syntax-dynamic-import
> 
> .babelrc 增加
> {
> "plugins": ["syntax-dynamic-import"]
> }
> 然后你说的那句改为
> route.component = resolve => require([`@/${menu.component}`], resolve)
> 
> 但是 build的时候很感人 没有分包

**这样修改之后貌似还是run不起来，一直报错，能解答下不**

**Comment by caiya** [comment]
@majinkai 加入如下后代码就run不起来了
`route.component = resolve => require([`@/${menu.component}`], resolve)`

**Comment by majinkai** [comment]
> 小白提问，后端数据什么样的格式呢？
> 权限控制功能如果在前端能将路由数据扁平化后放在后端存储，管理员为不同用户赋菜单权限，打开页面时，根据用户权限，前端依据从后台读取路由数据来显示菜单，就非常棒了。
> 能否将修改后的完整代码放在github上？谢谢！

根据自己的后端数据格式去修改@/libs/utils.js的backendMenuToRoute方法，就可以了

**Comment by majinkai** [comment]
> > route.component = () => import(`@/${menu.component}`)
> > 这句貌似会导致编译的速度变得很慢，不知道是什么原因
> 
> 我改用这方法可以编译很快
> npm install babel-plugin-syntax-dynamic-import
> 
> .babelrc 增加
> {
> "plugins": ["syntax-dynamic-import"]
> }
> 然后你说的那句改为
> route.component = resolve => require([`@/${menu.component}`], resolve)
> 
> 但是 build的时候很感人 没有分包

在.babelrc文件里面加上dynamic-import-node速度就快了
```
{
  "presets": [
    "@vue/app"
  ],
  "env": {
    "development": {
      "plugins": [
        "dynamic-import-node"
      ]
    }
  }
}
```

**Comment by wangcongcong** [comment]
退出后除了刷新重新加载登录页解决store里的state失效，还能怎样来实现呐，重新加载，页面会闪，效果不太好，等待大佬指点~

**Comment by dysw** [comment]
@majinkai 小白提问 动态的多级菜单,同一view 不同参数怎么实现呢

**Comment by ddkcstream** [comment]
樓主方法可行 已實現 頂下

**Comment by qinkaizhi0516** [comment]
store里的MenuLIst要做什么处理， 我按照你的方法修改了 但是报错，
Invalid prop: type check failed for prop "menuList". Expected Array, got Function 

found in

---> <SideMenu> at src/components/main/components/side-menu/side-menu.vue
       <Sider>
         <Layout>
           <Main> at src/components/main/main.vue
             <App> at src/App.vue
               <Root>

**Comment by doujiangbaozi** [comment]
看楼上都实现了，我这里不行。最后卡在
  let route = Object.assign({}, menu)
  route.component = () => import(`@/${menu.component}`)
  return route
这个地方，console里面看到下面错误，也就是component的参数没有正确传入
component: ƒ ()
arguments: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:2:14)]
caller: (...)
length: 0
name: ""
prototype: {constructor: ƒ}
__proto__: ƒ ()
[[FunctionLocation]]: util.js?c276:56
[[Scopes]]: Scopes[4]

**Comment by suojian0313** [comment]
请问有人遇到这种情况么？
[Vue warn]: Error in callback for watcher "$route": "TypeError: Cannot read property 'icon' of undefined"

还有就是用这种方式实现 面包屑导航不见了。。

**Comment by taobali32** [comment]
发现一个bug.
版本 2.0.0

当分配三级菜单的时候.  如左侧菜单为
#站点设置
##权限管理
###角色管理
的时候 只会显示  权限管理.
-------------------------------
如左侧菜单为
#站点设置
##权限管理
###角色管理
##系统设置
###网站标题
-------------------------------
的时候 是没有问题的，  问题出在2级菜单渲染的时候.  

可能我的描述不清晰.待复现这个bug

现在再用,但是这个bug没有能力解决. 我的qq:3196672779，非常希望可以帮我查看一下这个问题.

**Comment by xiao0502** [comment]
@majinkai 正常的登录进去后，左侧的菜单栏加载，  `main.vue` 里面的 `this.$store.getters.menuList`是一个空数组

**Comment by qinkaizhi0516** [comment]
按照楼主的思路 已实现~ 多谢！

**Comment by Song1216** [comment]
> 按照楼主的思路 已实现~ 多谢！

老哥，你是怎么实现的啊，能给我讲讲不

**Comment by Song1216** [comment]
> > 按照楼主的思路 已实现~ 多谢！
> 
> 老哥，你是怎么实现的啊，能给我讲讲不

我也实现了......

**Comment by qinkaizhi0516** [comment]
> > 按照楼主的思路 已实现~ 多谢！
> 
> 老哥，你是怎么实现的啊，能给我讲讲不

哈哈 实现就好 其实不难

**Comment by kaedeliu** [comment]
@majinkai 我也遇到数据错误了 这是什么原因
错误日志..................
webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Invalid prop: type check failed for prop "menuList". Expected Array, got Function 

found in

---> <SideMenu> at src/components/main/components/side-menu/side-menu.vue
       <Sider>
         <Layout>
           <Main> at src/components/main/main.vue
             <App> at src/App.vue
               <Root>

**Comment by Song1216** [comment]
我是把红框里面的内容去掉就可以了，这里明显语法错误了


------------------ 原始邮件 ------------------
发件人: "kaedeliu"<notifications@github.com>;
发送时间: 2019年7月23日(星期二) 中午12:48
收件人: "iview/iview-admin"<iview-admin@noreply.github.com>;
抄送: "范特洒～"<2378073133@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [iview/iview-admin] [已实现] iview-admin动态加载路由修改方法 (#1158)




@majinkai 我也遇到数据错误了 这是什么原因
 错误日志..................
 webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:620 [Vue warn]: Invalid prop: type check failed for prop "menuList". Expected Array, got Function
 
found in
 
--->  at src/components/main/components/side-menu/side-menu.vue
 
 
 
 at src/components/main/main.vue
  at src/App.vue

**Comment by kaedeliu** [comment]
去掉menuList数据就空了 还是不行
我最后按照楼上把
menuList: (state) => (state, getters, rootState) => getMenuByRouter(state.routers, rootState.user.access),
改为menuList: (state, getters, rootState) => getMenuByRouter(state.routers, rootState.user.access),
就没问题了

**Comment by 634323580** [comment]
> 请问有人遇到这种情况么？
> [Vue警告]：观察者“$ route”的回调错误：“TypeError：无法读取未定义的属性'icon'
> 
> 还有就是用这种方式实现面包屑导导不见了..



> 请问有人遇到这种情况么？
> [Vue警告]：观察者“$ route”的回调错误：“TypeError：无法读取未定义的属性'icon'
> 
> 还有就是用这种方式实现面包屑导导不见了..

我也遇到了，请问你是怎么解决的

**Comment by 634323580** [comment]
> 请问有人遇到这种情况么？
> [Vue警告]：观察者“$ route”的回调错误：“TypeError：无法读取未定义的属性'icon'
> 
> 还有就是用这种方式实现面包屑导导不见了..

我也遇到了，请问你是怎么解决的。

**Comment by Song1216** [comment]
去掉红框部分内容


------------------ 原始邮件 ------------------
发件人: "xiaoZ"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 中午12:00
收件人: "iview/iview-admin"<iview-admin@noreply.github.com>;
抄送: "范特洒～"<2378073133@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [iview/iview-admin] [已实现] iview-admin动态加载路由修改方法 (#1158)



 
请问有人遇到这种情况么？
 [Vue警告]：观察者“$ route”的回调错误：“TypeError：无法读取未定义的属性'icon'
 
还有就是用这种方式实现面包屑导导不见了..
  
我也遇到了，请问你是怎么解决的。

**Comment by 634323580** [comment]
@Song1216 没看到红框部分内容呀？

**Comment by as496866408** [comment]
已经搞定。主要就是三个js。非常感谢大神

**Comment by timothyadam** [comment]
按照大神的写法 使用过程中 发现了menuList () {
      console.log('从vuex 中获取')
      console.log(this.$store.getters.routers)
      return this.$store.getters.routers
    },   main.vue 取出来的值为空 左侧菜单无法显示

**Comment by luterc** [comment]
我弄了个简单例子，供参考：https://github.com/MayBeWrong/iview-admin-dynamic-router.git

**Comment by azhai2016** [comment]
component: ƒ ()
arguments: [Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (:2:14)]
caller: (...)
length: 0
name: ""
prototype: {constructor: ƒ}
proto: ƒ ()
[[FunctionLocation]]: util.js?c276:56
[[Scopes]]: Scopes[4]
后台加载的菜单，比较了一下，
name:"" 这个 少了 “component” 
然后左边点击跳转的话会生成新页面，不知道为什么？

**Comment by Michaelmlh** [comment]
> 请问有人遇到这种情况么？
> [Vue warn]: Error in callback for watcher "$route": "TypeError: Cannot read property 'icon' of undefined"
> 
> 还有就是用这种方式实现 面包屑导航不见了。。


 原因：
1. (@/lib/util.js)在加载面包屑（getBreadCrumbList）时（由@/store/module/app.js调用），调用homeRoute.meta时，homeRoute为空对象；
2. ---->(@/lib/util.js)在获取主页路由组件 （getHomeRoute）时（由@/store/module/app.js调用），homeName(@/config/index.js)未存在于当前路由（getHomeRoute的参数routers）中；
3. ---->此时，（@/router/index.js中）router.onReady()方法未执行，所以未获取动态路由，即homeName不在当前路由中；

 解决方法：
 主页（homeName的路由）在@/router/routers.js中写好，而不要写在动态路由中。
