### ISSUE TITLE
能否提供一个JSCS的代码风格配置文件？

### ISSUE THREAD

**Issue by yangyang0507** [iview/iview-admin#116]
想使用iView的默认风格，但是每个IDE的代码格式化插件都不同，不能很好的遵循规范，这就导致了格式化代码后，ESLint校验代码格式有问题，如果能够提供一个默认的JSCS代码风格配置文件，我们就可以通过它进行统一代码风格管理。

**Comment by lison16** [comment]
项目根目录下有.eslintrc.json文件
