### ISSUE TITLE
npm run build 生成的index_prod.html 点击登录跳转不了

### ISSUE THREAD

**Issue by ysjsgzq** [iview/iview-admin#117]
打扰了，我把这个项目下载到本地，改了编译build目录里面的webpack.prod.config.js，我把 output. publicPath: 'dist/'改成这样了，编译成功以后，我打开index_prod.html点击登录跳转不了，控制台也没报错，是我这里没改对么？

**Comment by lison16** [comment]
请问启动本地服务器了吗

**Comment by ysjsgzq** [comment]
没有用服务器，就直接点击的html文件。本地还要啥服务器么

**Comment by ysjsgzq** [comment]
@lison16

**Comment by ysjsgzq** [comment]
@lison16  谢谢，我放apache服务器里面可以正常跳转了。
