### ISSUE TITLE
官方的分页示例无法使用

### ISSUE THREAD

**Issue by TombarthiteL** [iview/iview-admin#118]
https://www.iviewui.com/components/table 这个上面的介绍 上面的复杂分页
我在admin这里新建立一个页面 粘贴代码报错 Component template should contain exactly one root element. If you are using
刚学这个 不太熟悉  希望能有个完整的分页示例

**Comment by lison16** [comment]
建议你先看下vue文档单文件组件部分

**Comment by TombarthiteL** [comment]
哈哈哈 看了文档一下就解决了 ...  后端过来的  刚学 莫怪 莫怪
