### ISSUE TITLE
打包加载成功后，默认使用localhost打开，如果改用本机IP打开则无法打开，请问需要配置哪个参数可以使用IP打开

### ISSUE THREAD

**Issue by HankBass** [iview/iview-admin#119]

**Comment by dolphinfine** [comment]
在webpack-dev-server 构建的服务器不能在局域网打开，可以在运行命令后加--host 0.0.0.0解决。完整的运行命令如下（package.json中的script）

"scripts": { "dev": "webpack-dev-server --content-base ./ --host 0.0.0.0 --inline --hot --compress --history-api-fallback --progress --colors --config build/webpack.dev.config.js" },

**Comment by HankBass** [comment]
确实是这样，感谢
