### ISSUE TITLE
进入富文本编辑器时出现 script 路径错误

### ISSUE THREAD

**Issue by itpretty** [iview/iview-admin#12]
浏览器：Firefox 56.0.1 (64位)
控制台：**指向“ https://iview.github.io/iview-admin//themes/modern/theme.js ”的 <script> 加载失败。**

**Comment by lison16** [comment]
这个是firefox上存在的问题，暂时还没有发现是什么原因，如果您了解了欢迎您指出，感谢您的支持

**Comment by Qsnh** [comment]
这个是因为你删除了dist目录下面的关于tinymce的插件依赖问题

**Comment by RenShine** [comment]
@lison16  这个问题的根源是当你使用require的方式引入tinymceEditor的时候  它是使用document.currentScript来获取baseURL的，但是firefox并不支持这个方法，有以下几个解决方案。
1、简单粗暴的使用<script>标签全局引入tinymceEditor
2、给tinymceEditor提一个PR，相关资料：http://www.cnblogs.com/rubylouvre/archive/2013/01/23/2872618.html （不过不知道人家会不会合我的代码）

**Comment by lyh2668** [comment]
@RenShine @lison16 我用import引入Tinymce的时候总是不行，会提示我没有‘themes/modern/theme.js’，看了ivews-admin也没用script的方式引入的，所以比较疑惑，希望能得到一些解答，谢谢。
有少许研究了Tinymce的源码并尝试修改，但是未果

**Comment by lison16** [comment]
iview-admin使用import的方式引入tinymce，如果要兼容firefox的话，可以暂时使用script标签引入的方式引入tinymce

**Comment by Teemwu** [comment]
我设置了`  tinymce.baseURL='/static/tinymce';`可以成功 加载，参考：[https://stackoverflow.com/questions/4412589/tinymce-paths-how-to-specify-where-to-load-things-like-editor-plugin-js](https://stackoverflow.com/questions/4412589/tinymce-paths-how-to-specify-where-to-load-things-like-editor-plugin-js)
