### ISSUE TITLE
[Bug Report]富文本编辑器层级问题导致不能改变内容

### ISSUE THREAD

**Issue by HighWarmModel** [iview/iview-admin#1202]
### Environment
macOs 10.14.2/谷歌浏览器版本 72.0.3626.109（正式版本） （64 位）

### Reproduction link
[https://admin.iviewui.com/components/editor_page](https://admin.iviewui.com/components/editor_page)

### Steps to reproduce
富文本编辑器移入字号、字体、文字颜色、背景色

### What is expected?
富文本编辑器能选中并改变

### What is actually happening?
富文本编辑器移入字号、字体、文字颜色、背景色等都不能选中，直接消失了，而且浮层在字体下面
目前看到是由这个
```
.editor-wrapper * {
    z-index: 100!important;
}
```
影响到的

**Comment by zxpsuper** [comment]
我也遇到这个问题，如何解决

**Comment by HighWarmModel** [comment]
> 我也遇到这个问题，如何解决
直接把我标出来的样式删掉就可以了

**Comment by stanNo1** [comment]
editor.vue加上
.w-e-text-container {
    z-index: 99 !important;
  }
