### ISSUE TITLE
能否提供一个常见的增删改列表，可以跳转页面的

### ISSUE THREAD

**Issue by yangzhenda11** [iview/iview-admin#121]
如题，列表内编辑的信息太少了，有些情况需要跳转页面进行处理，能否提供一个常见的增删改列表模板，可以跳转页面完成增改查，然后列表字段相应的刷新，谢谢！

**Comment by yangzhenda11** [comment]
列表内编辑的字段太少了，可否提供一

**Comment by lison16** [comment]
这个功能你如果有需求可以自己实现，涉及到的技术点无非是render函数、生命周期钩子
