### ISSUE TITLE
急求，为什么打包上线后，tag-nav切换或者侧边栏切换页面会导致页面卡死。。本地开发不会出现这个问题。

### ISSUE THREAD

**Issue by zengweigui** [iview/iview-admin#1239]
急求，为什么打包上线后，tag-nav切换或者侧边栏切换页面会导致页面卡死。。本地开发不会出现这个问题。好奇怪啊，没有规律，页面元素多的切换会卡，少的也会卡

**Comment by rewq11** [comment]
我本地开发也出现了这问题，同求
