### ISSUE TITLE
在vue.config.js中配置多页面报错RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by zj9495** [iview/iview-admin#1252]
项目是刚clone下来的，只对多页面pages做了配置
仓库地址 https://github.com/zj9495/iview-admin-pages
commit记录 https://github.com/zj9495/iview-admin-pages/commit/4e81ada93bd6f35768b3c07db6b2280d7ec0ba10
[![QQ20190423-0.png](https://i.loli.net/2019/04/23/5cbeba1be21b8.png)](https://i.loli.net/2019/04/23/5cbeba1be21b8.png)
[![QQ20190423-1.png](https://i.loli.net/2019/04/23/5cbeba1be6c5c.png)](https://i.loli.net/2019/04/23/5cbeba1be6c5c.png)
[![QQ20190423-2.png](https://i.loli.net/2019/04/23/5cbeba1bb8436.png)](https://i.loli.net/2019/04/23/5cbeba1bb8436.png)

**Comment by zj9495** [comment]
yarn run dev无法正常启动 报RangeError: Maximum call stack size exceeded

**Comment by wangchuankai** [comment]
你好，解决了么。我也是来找答案的 0.0

**Comment by zj9495** [comment]
> 你好，解决了么。我也是来找答案的 0.0

已经解决了 https://github.com/zj9495/iview-admin-pages/commit/ddea34bfccbfc07ab1caa1dd71bcd08228e275fd
