### ISSUE TITLE
源码运行后 缺少css文件.

### ISSUE THREAD

**Issue by dmoosocool** [iview/iview-admin#128]
```shell
npm run build //失败
```
![image](https://user-images.githubusercontent.com/30599141/32214252-35438258-bdec-11e7-954d-a0b7fef3f840.png)

```shell
npm run dev // 能成功跑起来, 但是css找不到.
```

- /dist/simplemde.min.css
- /dist/cropper.min.css

![image](https://user-images.githubusercontent.com/30599141/32214398-b3c8edca-bdec-11e7-8605-38075a176cd8.png)

请问有遇到这个问题么?

**Comment by lison16** [comment]
看下你对应的css文件存在不

**Comment by dmoosocool** [comment]
dist文件夹里没有这俩文件.

**Comment by lison16** [comment]
download一份
