### ISSUE TITLE
所有的拖拽效果在 Firefox 56 中都打开新页签

### ISSUE THREAD

**Issue by itpretty** [iview/iview-admin#13]
浏览器：Firefox 56.0.1 (64位)
控制台：每次操作可拖拽排序和可拖拽列表后，浏览器都打开一个新页签。

**Comment by lison16** [comment]
十分感谢，现已解决

**Comment by CharlesSong** [comment]
360极速浏览器极速模式下也是打开新标签页

**Comment by lison16** [comment]
拖拽打开新也签的情况在几大浏览器测试均不会出现

**Comment by egg-hero** [comment]
我的Firefox也会出现这种情况， Firefox64.0
![default](https://user-images.githubusercontent.com/27225478/50337396-f1dd2980-054b-11e9-8670-d66d6a529d3f.png)
