### ISSUE TITLE
theme: 请问修改默认theme的代码段在哪

### ISSUE THREAD

**Issue by HazyLiA** [iview/iview-admin#130]
个人问题没找到初始化theme的代码段，
原主题绿色太亮刺眼，全局修改后，现在想把绿色主题作为默认主题。

**Comment by lison16** [comment]
暂时你可以先把g.css里的绿色替换成你想要的颜色，后面我们会提供一个方便的方式

**Comment by HazyLiA** [comment]
那怎么设置默认主题啊

**Comment by lison16** [comment]
目前你可以在  iview-admin/node_modules/iview/dist/styles/iview.css  修改里面的主题色
