### ISSUE TITLE
支持ie浏览器的方法

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#133]
IE浏览器没有内置Promise对象。不仅如此，几乎所有的ES6新增的方法在IE都不能用，此时你需要babel Polyfill
1.首先npm install --save babel-polyfill
2.修改build/webpack.base.config.js

修改
entry: {
        main: './src/main',
        vendors: './src/vendors'
    },
为
entry: {
        main: ["babel-polyfill","./src/main"],
        vendors: './src/vendors'
    },
即可。

**Comment by lison16** [comment]
感谢你写出解决方法，对ie的支持需要根据业务需求，所以我们没有对IE做兼容处理，后面会对IE相关的兼容处理做个汇总，再次感谢

**Comment by hold-baby** [comment]
![image](https://user-images.githubusercontent.com/21041219/33356063-5dfe4000-d4f5-11e7-8512-4280fc0a8bc2.png)
![image](https://user-images.githubusercontent.com/21041219/33356081-7ef8f5b6-d4f5-11e7-9f2a-b35ec1382f8d.png)

我使用你的方法 但是还是要报语法错误 这个该怎么改呢？

**Comment by dolphinfine** [comment]
你一个字一个字看仔细我的方法，然后对照修改，如果再错，我也没办法。我这样做没有任何报错。如果你还做了其他修改，那我就不知道了。

**Comment by dolphinfine** [comment]
你一个字一个字看仔细我的方法，然后对照修改，如果再错，我也没办法。我这样做没有任何报错。如果你还做了其他修改，那我就不知道了。

**Comment by jakietwo** [comment]
我也想知道 @hold-baby  请问你 解决了吗

**Comment by xiongcao** [comment]
@jakietwo [看这里](https://github.com/iview/iview-admin/issues/450)

**Comment by jakietwo** [comment]
@xiongcao 我改了dev-server 版本 还是不行 报错依然是2个语法错误和1 个 jsonp呢

**Comment by lengyucc** [comment]
> IE浏览器没有内置Promise对象。不仅如此，几乎所有的ES6新增的方法在IE都不能用，此时你需要babel Polyfill
> 1.首先npm install --save babel-polyfill
> 2.修改build/webpack.base.config.js
> 
> 修改
> entry: {
> main: './src/main',
> vendors: './src/vendors'
> },
> 为
> entry: {
> main: ["babel-polyfill","./src/main"],
> vendors: './src/vendors'
> },
> 即可。

没有webpack.base.config.js怎么办？只有vue.config.js

**Comment by xiaohongzhou** [comment]
IE浏览器没有内置Promise对象。不仅如此，几乎所有的ES6新增的方法在IE都不能用，此时你需要babel Polyfill
1.首先npm install --save babel-polyfill
2.修改build/webpack.base.config.js

修改
entry: {
main: './src/main',
vendors: './src/vendors'
},
为
entry: {
main: ["babel-polyfill","./src/main"],
vendors: './src/vendors'
},
即可。

没有webpack.base.config.js怎么办？只有vue.config.js
