### ISSUE TITLE
iview这个框架是哪个sb设计的，问问题不回答就算了，还关闭，不如不要开issue好了

### ISSUE THREAD

**Issue by zhangwei900808** [iview/iview-admin#141]
activeName:'4-1',//一会int ,一会string，这是要整死人吗？
openNames:['3']//设置了还不起作用，github上面那么多人出现这个问题也不解决，直接关闭issue，我还以为这个框架有多好，star那么多，搞不好是有水军点上去的

**Comment by lison16** [comment]
所有关闭的issues都是解决了的，没有解决的或者有待排查的都没有关闭，建议你学习一下vue的相关知识或者html和css基础，然后再来进行前端开发。

**Comment by lison16** [comment]
还有，你所说的active-name是iview的菜单的属性，你指的active-name='4-1'也只是iview官方实例的用法，iview-admin里用的是路由的name来做的标识根本没用到4-1这样的形式；
open-names设置为['3']更是奇怪，这个数组中放的也是展开页面的name值，你搬个iview官方文档的例子说放到iview-admin中没有效果，怀疑你有没有用过iview-admin。
好了，问题解决了，close

**Comment by zhangwei900808** [comment]
你如果能够在我提问题也能这么积极主动该多好 ，我上面的话也是气话，目的只是让你们重视一下，至于你上面讲的，我确实遇到过这些问题，只是issuse上面没有找到解决办法，你们能不能在关闭issues的时候也能顺便把解决好的issue放到上面。

**Comment by lison16** [comment]
作为开源项目，我们尽可能的对不明白的有问题的使用者提供帮助，但是如果使用者把自己当做客户来指手画脚，这不是开源世界的人该有的表现。另外有些问题是iview-admin自身的缺陷的，我们会尽快修复，对于对vue都没有基础了解的，最好是学下基础再来入手iview-admin。对于你讲到的问题，这些都是你对Iview组件不了解的原因，再加上你对iview-admin的开发人员进行人身攻击，所以建议你暂时不要接触iview-admin

**Comment by zhangwei900808** [comment]
在github看到你们这些开源的人多了去了，所以你讲这些话也就见怪不怪了，希望你们好好做产品吧，其它的我就不多说了
