### ISSUE TITLE
v1.1.4版本退出: Error in nextTick: "TypeError: Cannot read property 'updateOpened' of undefined"

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#142]
![image](https://user-images.githubusercontent.com/27426130/32306238-28c1a9e0-bfb5-11e7-855c-1c388dd2e7e5.png)

**Comment by lison16** [comment]
更新到最新版本就没有了，这个bug昨天刚修复

**Comment by dolphinfine** [comment]
无论是你们的在线版还是我从git拉下来的版本，这个bug依然存在

**Comment by lison16** [comment]
在线版本因为是在每次小版本更新发布后才更新，git拉取最新的代码是没问题的，昨天刚修复的，你再试试，我刚试了没问题
