### ISSUE TITLE
select 下拉框默认值在下拉项中不存在时，表单验证还是能通过。

### ISSUE THREAD

**Issue by topli** [iview/iview-admin#143]

**Comment by lison16** [comment]
你说的是iview-admin中的示例吗

**Comment by topli** [comment]
是iview的组件

**Comment by lison16** [comment]
那你改到iview项目的主页提issue啊。。。

**Comment by jiangleiundo** [comment]
select下拉有数据，v-model也绑定了数据，一切都正常，_**就是校验不通过**_，string类型的数据
{required: true, message: '必输项不能为空', trigger: 'change'}

**Comment by manondidi** [comment]
> select下拉有数据，v-model也绑定了数据，一切都正常，_**就是校验不通过**_，string类型的数据
> {required: true, message: '必输项不能为空', trigger: 'change'}

怎么解决的 type:'number'吗 我加了也不能解决
