### ISSUE TITLE
dist目录的作用是什么

### ISSUE THREAD

**Issue by seawenzhu** [iview/iview-admin#144]
dist目录可以删除， 编译后重新生成么？

**Comment by lison16** [comment]
目前不能，下周预计处理一下

**Comment by ShawshankLin** [comment]
现在要怎么打包,发现一大包文件都生成到dist下面了,然后index.html在外面,,能不能脱离开来

**Comment by lison16** [comment]
把dist文件夹和外面的index_prod.html放到服务器就行，记着打包之前先修改webpack.config.prod.js里的output.publicPath的值
