### ISSUE TITLE
build里面少了一些文件,,不知道怎么改端口,不会webpack,,可以把vue-cli的配置文件加上吗?

### ISSUE THREAD

**Issue by ShawshankLin** [iview/iview-admin#145]
build里面少了一些文件,,不知道怎么改端口,不会webpack,,可以把vue-cli的配置文件加上吗?

**Comment by davecat** [comment]
@ShawshankLin   伸手党啊你。。。。webpack去官网看一下就自己配置了，建议把issues关了，这问题太low了，汗
