### ISSUE TITLE
页签可以保持当前状态吗

### ISSUE THREAD

**Issue by 5vbear** [iview/iview-admin#15]
业务需求要求可以切换tab的场景比较多，刚才试了一下demo，切换就是重新加载了

**Comment by lison16** [comment]
这种需求的话就不应该用路由了，应该用tabs选项卡形式，通过v-show来切换

**Comment by itpretty** [comment]
也发现这个问题了。测试富文本编辑器时，输入了些内容，切换tab后，再回来就清空了。

很多场景是：使用者在操作某个tab页签时会切换打开另一个页签复制某些内容，然后再回来粘贴到当前tab页签内。

**Comment by lison16** [comment]
如果是这个需求的话，可以做本地存储，设置定时存储或者监听tinymce的onchange然后存储，然后在编辑器页面初始化的时候将本地存储的内容加载到编辑器里

**Comment by williamwang2015** [comment]
多tab页目前大多数使用的应该还是iframe方式，不过这似乎违反了单页面应用的原则。如果采用动态加载内容，那么加载的内容片段里面的组件id要保证不同，理论上应该可以实现，建议考虑一下。目前实现的类似tab页的方式，容易给人误解。

**Comment by baiyunchen** [comment]
UI很漂亮，但这个确实是个问题，我也是发现了这个问题才进入到ISSUE中来的！~

**Comment by wakerman** [comment]
可以在标签页栏附加一个刷新当前页的按钮

**Comment by Shay0921** [comment]
@lison16 我用的就是tabs选项卡来做的，没有用router。如果这样的话，是不是url就不会改变？然后浏览器也无法进行前进后退了？还有一个问题就是，如果我用了多标签页，如果多标签页里面的内容，是订单列表页，可以点击某个订单查看详情，这种的应该怎么做呢？因为已经没有用router了，也就没办法用<router-view>吧？

**Comment by baiyunchen** [comment]
@Shay0921  用Tabs来做的话，router只能表示当前选中tab页的路由，而且需要在点击tabs时，自己去改变当前路由，仔细想想差不多把整个路由都重写了~~~~

**Comment by Shay0921** [comment]
@baiyunchen 比方说这个页面，上面跟左边都已经固定了，如果我想实现点击某个订单，让中间部分的主体内容有变化，这种实现的大概思路是什么呢？
![image](https://user-images.githubusercontent.com/26411912/31800895-dbe0c7e8-b576-11e7-8f84-47112e44bd0c.png)

**Comment by baiyunchen** [comment]
@Shay0921  我们内部的系统（Sliverlight项目）在这里的实现上，有两种模式，一种是同一个页面只能打开一个，再次点击菜单时，触发该页面的一个事件，你可以在事件里面重新加载数据什么的，但是页面不会刷新；另外一种模式是允许同一个页面打开很多个Tab页。具体实现没有深究过，感觉很麻烦~

**Comment by Shay0921** [comment]
@baiyunchen 感谢你的回答，我现在做的就是再次点击菜单时，会刷新同一个tabs，但是现在有一个疑问就是，在当前标签页中，比方说点击了第一个订单，日期为2016-05-03这个，按理说会有一个新的页面打开，那你们是会在当前页面进入新的页面，还是重新打开一个新的标签页呢？。如果是在当前页面刷新的话应该会比较难做把？

**Comment by baiyunchen** [comment]
@Shay0921  我们之前的SL项目新的页面都是一个新的Tab，或者是干脆弹个Modal框出来~既然你系统都设计多tab了，就不要让覆盖掉当前的页面了~因为你设计多tab就是为了防止新页面把旧页面给覆盖掉~

**Comment by Shay0921** [comment]
@baiyunchen 明白了，谢谢，我还有一个问题就是，如果用多标签页的话，也就不用路由了，只是加入很多组件，url也就不会有任何改变呢？也就没办法浏览器前进后退。然后我现在做的多标签，都是直接加入组件，会把点开的标签页内容添加到html中，这样设计是不是有问题，因为当多标签页比较多时，html片段也会很多。怎么才能很好的解决这个问题呢？

**Comment by baiyunchen** [comment]
@lison16  其实大家更希望的是，能把这个改成大家理解的那样子，其实并不缺少一款漂亮的单页应用的主题，但是缺少一款多TAB页的漂亮的单页应用的主题~

**Comment by Shay0921** [comment]
@lison16 哦哦，这样啊，所以url才会发生改变吧，也是router切换吧？

**Comment by Shay0921** [comment]
@baiyunchen 是的，现在感觉国内很多公司都开始做多标签应用了。但是不知道这样性能会怎么样。我用vue的时候解决了多标签主要内容，但是感觉有一些地方用jquery来做会更方便。我用vue+jquery，性能上应该不好吧，但是目前也没有找到很好的解决办法。

**Comment by lison16** [comment]
@Shay0921 了解，下一周期开始开发，感谢大家的支持

**Comment by Shay0921** [comment]
@lison16 棒棒哒！

**Comment by baiyunchen** [comment]
@Shay0921  现在的浏览器，你可以自己去控制地址栏显示的URL的~另外，前进后退你可以自己实现一个，做到页面上方

**Comment by Shay0921** [comment]
@baiyunchen 嗯呢，前阵子写了一个自己控制地址栏的url，但是在浏览器前进后退时有一些bug，只有自己填写的url可以后退，但不能前进。有考虑过自己写一个返回按钮之类的。但是如果按照你上面说的，已经做了多标签页了，就没必要新页面刷新。所以这样的话也就不需要返回按钮之类的。

**Comment by AndsteLyc** [comment]
我们也正好是这个需求，现在唯一能做的就是在用户有输入内容的情况下切换标签，给一个“这个时候切换，表单内容会丢失”的提示。。。

**Comment by lison16** [comment]
现已支持保存当前页状态，可更新到v1.1.0体验

**Comment by baiyunchen** [comment]
@lison16  尝试了一下，并不行，在线DEMO没有升级？

**Comment by lison16** [comment]
现已更新

**Comment by Rainnut** [comment]
通过一个路由已经打开一个tab页面，然后再通过相同路由，只是路由的参数不一样，再打开一个新的tab怎么实现？并且这个长得一模一样的页面，不会影响旧页面的数据展示？
