### ISSUE TITLE
build的一些问题，及建议

### ISSUE THREAD

**Issue by BATAKK** [iview/iview-admin#151]

**Comment by BATAKK** [comment]
clone下来的项目，在build的时候，最后显示69 to clone下来的项目，在build的时候，最后显示69%，然后直接91%，之后就打完包了？ 我修改 output.publicPath之后,启动还是有问题（可能我需要修改一些东西），dist中下载下来的字体什么的不是必须的吧，建议dist目录还是尽可能清晰

**Comment by lison16** [comment]
这个具体得看报错，dist文件夹里文件的处理确实是个问题，会尽快优化

**Comment by tong3jie** [comment]
@lison16 
build的时候，dist文件不会自动清空，html应该也在dist下输出。
