### ISSUE TITLE
按F11全屏 按按钮无法退出查询

### ISSUE THREAD

**Issue by kxw1059** [iview/iview-admin#152]
按F11全屏 按按钮无法退出查询

**Comment by lison16** [comment]
退出什么查询？

**Comment by kxw1059** [comment]
不好意思笔误，点击按钮无法退出全屏

**Comment by lison16** [comment]
麻烦说下系统，浏览器和iview-admin版本

**Comment by kxw1059** [comment]
https://iview.github.io/iview-admin/#/home  这个demo啊   win10  chrome 版本 62.0.3202.62（正式版本） （64 位）

**Comment by lison16** [comment]
刚刚找了个win10电脑，用chrome浏览器可以正常退出全屏，点击按钮和按esc都可以退出

**Comment by kxw1059** [comment]
我的意思是按F11进入全屏  然后点击全屏按钮退出全屏；
单独的使用F11进入退出可以
单独的使用全屏按钮也可以

**Comment by lison16** [comment]
还真是，你用的太细了哈哈，谢谢，马上修复

**Comment by kxw1059** [comment]
OK
