### ISSUE TITLE
切换主题色后，下拉菜单宽度异常

### ISSUE THREAD

**Issue by Sakuyakun** [iview/iview-admin#159]
正常状态：
![](https://i.loli.net/2017/11/06/5a002c4e09d84.png)

切换主题色后 下拉菜单宽度异常：
![](https://i.loli.net/2017/11/06/5a002c4e193eb.png)

**Comment by lison16** [comment]
你的iview-admin的版本是多少？

**Comment by Sakuyakun** [comment]
@lison16 版本1.1.4   chrome61.0.3163.100  我将项目clone下来后安装依赖运行就会有这种情况 但是在线预览项目demo地址却没这个问题

**Comment by lison16** [comment]
把iview升到最新

**Comment by Sakuyakun** [comment]
@lison16 更新到2.6.0后依旧是有这个问题 ， 是g.css的问题吗？

**Comment by Sakuyakun** [comment]
@lison16 我对比了主题色的样式后，发现切换后，`.ivu-select-dropdown`样式的`width: inherit;` 优先级比`.ivu-dropdown-transfer`高，导致width没有修改为`auto` 所导致，在自定义样式加上下面的代码就可以了
```css
.ivu-select-dropdown {
  width: auto !important;
}
```

**Comment by pfun** [comment]
我这边也遇到这个问题：mac   safari  版本 11.0.1 (13604.3.5)

**Comment by leegedan** [comment]
这个问题是因为iview 组件样式有更改，和iview-theme 模版不一致导致的，使用iview less 生成皮肤就好了。
@lison16

**Comment by lison16** [comment]
1.2.0版本已经修复了这个问题

**Comment by leegedan** [comment]
@lison16 使用过程还发现一个小问题，Tag 组件的小圆点颜色有限制，自定义皮肤颜色就没法一致了。
目前自己作如下处理。
``` vue
<template>
  <transition name="fade">
    <div :class="classes" @click.stop="check" :style="tagStyle">
      <span :class="dotClasses" v-if="showDot" :style="dotStyle"></span>
      <span :class="textClasses">
        <slot></slot>
      </span>
      <Icon v-if="closable" type="ios-close-empty" @click.native.stop="close"></Icon>
    </div>
  </transition>
</template>

<script>
import { Tag } from 'iview'

export default {
  name: 'Tag2',
  extends: Tag,
  props: {
    tagStyle: {
      type: Object,
      default: () => {
        return {}
      }
    },
    dotStyle: {
      type: Object,
      default: () => {
        return {}
      }
    }
  }
}
</script>
```
建议组件上放开这个颜色控制。

**Comment by lison16** [comment]
这个是iview组件的限制，实际还需要自己动手来实现。
