### ISSUE TITLE
关于权限控制

### ISSUE THREAD

**Issue by qiqizjl** [iview/iview-admin#163]
非常感谢iview提供了那么好用的后台管理和UI框架。关于这个后台管理，有个疑问：
我看到iview-admin自带了权限管理，那么对于这个权限管理是否可以根据Api返回的权限路由来匹配呢。我看到现在是用的是access是个int。看起是权限大小，但是我们需要做的是根据路由。可能每个人的权限是不一样的。那么如果有20个管理员，那么acces就有20个，这个将很难维护。请问有类似的解决方案么

**Comment by qiqizjl** [comment]
@lison16  能否帮忙看下这个问题。 非常感谢

**Comment by lison16** [comment]
这个确实没有考虑到，后面可能会重构下权限过滤

**Comment by qiqizjl** [comment]
@lison16  有大概的时间表么 多久可以做完。这将决定我们是否决定这款产品

**Comment by lison16** [comment]
Iview-admin并不是面向客户的产品，他需要大家共同参与进来让他更丰富，iview-admin使用MIT开源协议，你可以根据需求自行修改开发。

**Comment by calabash519** [comment]
权限其实可以在菜单上处理，登录的时候会有 roleId 和 groupId，菜单走接口传递前面两个参数，自动就会过滤

**Comment by linkypi** [comment]
> 非常感谢iview提供了那么好用的后台管理和UI框架。关于这个后台管理，有个疑问：
> 我看到iview-admin自带了权限管理，那么对于这个权限管理是否可以根据Api返回的权限路由来匹配呢。我看到现在是用的是access是个int。看起是权限大小，但是我们需要做的是根据路由。可能每个人的权限是不一样的。那么如果有20个管理员，那么acces就有20个，这个将很难维护。请问有类似的解决方案么

对，我也是发现有这个问题，正常的权限管理系统都是需要和路由菜单相关联
