### ISSUE TITLE
富文本编辑器不能传图片吗？

### ISSUE THREAD

**Issue by jiankian** [iview/iview-admin#164]
富文本编辑器只能插入图片链接，不能自己传吗？

**Comment by lison16** [comment]
上传功能需要自己结合业务实现，因为涉及到服务器接口，可以看下tinymce的文档

**Comment by ouzhenlin** [comment]
什么时候能集成百度富文本呀，感觉百度功能多点，我集成了进去，可是后端又说配这个上次文件很麻烦。。。。。

**Comment by lison16** [comment]
Iview-admin不可能集成多个编辑器进来，具体用什么富文本编辑器，你要根据业务自己定
