### ISSUE TITLE
darwin是啥，

### ISSUE THREAD

**Issue by asdf3309** [iview/iview-admin#165]
npm WARN eslint-config-google@0.9.1 requires a peer of eslint@>=4.1.1 but none was installed.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32"
,"arch":"x64"})

**Comment by lison16** [comment]
请自行google
