### ISSUE TITLE
后续版本如何更新？

### ISSUE THREAD

**Issue by lengkuwolf** [iview/iview-admin#172]
我在现有版本上开发好项目，那后续的版本应该如何更新升级？

**Comment by lison16** [comment]
现在正在进行大范围重构整理，重构之后，基本上所有的功能都会整理为组件，使用会更灵活。如果你现在使用的版本你不想大的改动的话，只需要以后使用npm install的方式安装Iview-admin新出的组件即可

**Comment by ranhuan** [comment]
赞，1.x我是先fork，然后用github的pull request合并后面的升级

**Comment by ranhuan** [comment]
vue不一切都是组件吗，你说得是全部封装为npm的package？

**Comment by lison16** [comment]
没错

**Comment by rainlysong** [comment]
请问下重构版本预计什么时候能发布呢？

**Comment by lison16** [comment]
预计下周

**Comment by hodgevk** [comment]
@lison16 1.2版什么时候发布？跟1.1版有什么差别，可以无缝升级还是需要手工调整？
