### ISSUE TITLE
执行npm run dev 进入首页报错

### ISSUE THREAD

**Issue by hrqde** [iview/iview-admin#174]
![image](https://user-images.githubusercontent.com/20411026/32609298-35fb2880-c59a-11e7-8e03-03a1842ebdb7.png)

**Comment by hrqde** [comment]
帮忙看下啊

**Comment by lison16** [comment]
装echarts

**Comment by hrqde** [comment]
echarts 安装的有啊还是这样

**Comment by hrqde** [comment]
@lison16

**Comment by hrqde** [comment]
@lison16 我重新安装echarts了还是有个报错
![image](https://user-images.githubusercontent.com/20411026/32646025-5c30153e-c625-11e7-8229-f648fa2357dd.png)
