### ISSUE TITLE
多次npm run build，旧文件不会删除？

### ISSUE THREAD

**Issue by Sakuyakun** [iview/iview-admin#175]
![](https://ooo.0o0.ooo/2017/11/10/5a050c2c2e4c3.png)

没有更好的解决方案吗？这样的打包处理一点都不方便，根本无法使用，目前dist文件夹遗留了很多旧打包后的文件

**Comment by lison16** [comment]
会在1.2.0版本解决

**Comment by Sakuyakun** [comment]
@lison16 了解了，目前只能将dist备份...

**Comment by lison16** [comment]
现已优化
