### ISSUE TITLE
刚运行进入首页的报错你们有么？？

### ISSUE THREAD

**Issue by hrqde** [iview/iview-admin#176]
![image](https://user-images.githubusercontent.com/20411026/32640895-fb57fa48-c605-11e7-9959-252a6827df31.png)

**Comment by ie7shop** [comment]
昨天路径反反复复的各种配置，还以为配置不对，今天实在是没看出究竟是哪出问题。刚把图截好，进来就看到同样的问题了。

**Comment by hrqde** [comment]
@ie7shop 这是啥原因啊求帮忙

**Comment by ranhuan** [comment]
npm不要升级包

**Comment by ie7shop** [comment]
这是echarts整包的问题，刚刚echarts作者升级3.8.3版本修复了这个问题。
npm update echarts ，更新到3.8.3版本问题就解决了
