### ISSUE TITLE
怎么拦截401错误

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#177]
在util.js增加如下代码

// 添加响应拦截器
axios.interceptors.response.use(function (response) {
    // 对响应数据做点什么
    return response;
}, function (error) {
    // 对响应错误做点什么
    if (error.response.status === 401) {
        Cookies.remove('user');
        Cookies.remove('password');
        Cookies.remove('hasGreet');
        Cookies.remove('access');
        Cookies.remove('token');
        window.location.href = '#/login';
    };
    return Promise.reject(error);
});
发现并不能拦截401错误？请问具体应该怎么配置？

**Comment by ysjsgzq** [comment]
我是直接加在main.js里面的，

**Comment by dolphinfine** [comment]
@ysjsgzq 请问能把配置贴出来吗

**Comment by lison16** [comment]
哦，你看下main.js里的路由跳转拦截逻辑就知道了，如果当前已经登录而且即将要跳转到的页面是登录页，那么默认跳到首页，你可以自己修改规则

**Comment by litcto** [comment]
在util中是可以的。你后台response放状态了么？

**Comment by dolphinfine** [comment]
@litcto 当然有啊。现在解决了。把post请求二次封装，在err里面的error.response.status判断。总感觉不是那么规范。

**Comment by cuiweiqiang** [comment]
@dolphinfine 我是这么实现的，所有api请求都实现在 `./src/api/api.js` 里面，在这面 `export{ axios }`，在`main.js`中`import {  axios } from './api/api';` ，将拦截器实现在`main.js`的`created()`方法中，这样就可以进行全局拦截了。
