### ISSUE TITLE
建议风格再简洁一些。主题仅仅换颜色，还可以换背景等。

### ISSUE THREAD

**Issue by wangtifang** [iview/iview-admin#18]
整体风格偏传统，有点类似传统的后台管理系统。个人觉得现在新兴的后台管理系整体风格、布局应该自由、可插拔应用。风格小清新等。
个人较喜欢类似：明道OA系统风格的。地址：https://www.mingdao.com/login.htm。
个人观点，望大神别见怪。

**Comment by lison16** [comment]
感谢您的建议，在后面的版本我们会考虑换风格
