### ISSUE TITLE
分页控件位于页面最下方时出现支撑页面问题

### ISSUE THREAD

**Issue by wond-z** [iview/iview-admin#185]
# 分页控件位于页面最下方时出现支撑页面问题
如下图所示：
![](http://chuantu.biz/t6/139/1510563354x606614969.png)
当分页控件位于页面最下方时会撑起页面，这种情况不应该是浮动在分页控件上方吗

**Comment by lison16** [comment]
你可以做个判断，这种情况时显示在上方

**Comment by wond-z** [comment]
我只是觉得这个控件可以更完美，之前用过类似kendo，essential这些控件感觉都很好

**Comment by lison16** [comment]
iview的分页组件是有这个属性的，如果有更好的建议可以到iview的github主页提issue或pr
<img width="547" alt="2017-11-13 7 32 11" src="https://user-images.githubusercontent.com/20942571/32723822-d75f6896-c8a9-11e7-8f8b-2ac1b97cb43b.png">
