### ISSUE TITLE
权限控制无法实现多身份共用部分菜单

### ISSUE THREAD

**Issue by nextdooroldwang** [iview/iview-admin#186]
this.$store.commit('updateMenulist')中
```
if (child.access === accessCode) {
                                        return child;
                                    }
```
这样判断只能一个页面匹配一种权限吧？如果出现多个身份共用部分页面应该如何实现？

**Comment by lison16** [comment]
你都没有试吧，代码没你写的这么简单啊
<img width="617" alt="2017-11-13 7 20 59" src="https://user-images.githubusercontent.com/20942571/32723344-1a53cbf8-c8a8-11e7-89fa-2c94393ab142.png">
而且WIKI里写了路由配置中的权限配置啊
https://github.com/iview/iview-admin/wiki/router
最下面
