### ISSUE TITLE
自己新建一个vue文件，使用this.$Message.info('This is a info tip');时出现Cannot read property '$Message' of undefined错误

### ISSUE THREAD

**Issue by hecomlilong** [iview/iview-admin#191]
views文件夹下的vue文件就可以用。
<style lang="less">
.bd {
  margin: 0 auto;
  width: 615px;
  height: 100%;
  position: relative;
}
</style>
<template>
<Tabs value="name_index">
    <Tab-pane label="新建任务" name="name_index">
        <div>
            <Row>
                <Card :style="cardStyle">
                    <Form class="task-form" ref="task1" :model="task" :rules="taskRules1" :label-width="140">
                        <FormItem label="扫描对象：" required>
                            <Row :gutter="colMargin">
                                <Col span="8">
                                    <RadioGroup v-model="targetType" @on-change="targetTypeChange">
                                        <Radio :disabled="hasSubmit" label="站点"></Radio>
                                        <Radio :disabled="hasSubmit" label="资产"></Radio>
                                    </RadioGroup>
                                </Col>
                                <Col span="12">
                                </Col>
                            </Row>
                        </FormItem>
                        <template v-if="targetType=='站点'">
                            <FormItem label="" prop="target" :error="targetError">
                                <Row :gutter="colMargin">
                                    <Col span="8">
                                        <Input :disabled="hasSubmit" @on-blur="handleTargetBlur" style="margin-left:8px" v-model="task.target" type="textarea" :autosize="{minRows: 2,maxRows: 5}" placeholder="请输入扫描对象" />
                                    </Col>
                                    <Col span="12">
                                    </Col>
                                </Row>
                            </FormItem>
                        </template>
                        <template v-else>
                            <FormItem label="" prop="asset" :error="assetError">
                                <Row :gutter="colMargin">
                                    <Col span="8">
                                        <Select  :disabled="hasSubmit" @on-blur="handleAssetBlur" style="margin-left:8px" v-model="task.asset_id" filterable>
                                            
                                            <Option v-for="item in assetList" :value="item.id" :key="item.id">{{ item.title}}</Option>
                                        </Select>
                                    </Col>
                                    <Col span="12">
                                    </Col>
                                </Row>
                            </FormItem>
                        </template>
                        
                        <FormItem label="">
                            <Button :disabled="hasSubmit" @click="handleSubmit" style="width:100px;float:right" type="primary">提交</Button>
                        </FormItem>
                    </Form>
                </Card>
            </Row>
        </div>
    </Tab-pane>
    <Tab-pane label="扫描任务" name="name_config">
        
    </Tab-pane>
    <Tab-pane label="高级设置" name="name_config_pro">
        
    </Tab-pane>
</Tabs>
</template>
<script>
import ajaxPost from "../../../api/ajaxPost";
import { ERR_OK } from "../../../api/config";
export default {
  name: "task_add",
  data() {
    const validTarget = (rule, value, callback) => {
      if (this.targetError !== "") {
        callback(new Error("请输入站点"));
      } else {
        callback();
      }
    };
    const validAsset = (rule, value, callback) => {
      if (this.targetType !== "站点" && this.task.asset_id == 0) {
        callback(new Error("请选择资产"));
      } else {
        callback();
      }
    };
    return {
      task: {
        name: "",
        target: "",
        asset_id: 0
        
      },
      protocols: [],
      typeList: [
        { key: 0, value: "立即执行" },
        { key: 1, value: "计划执行" },
        { key: 2, value: "每天" },
        { key: 3, value: "每周" },
        { key: 4, value: "每月" }
      ],
      clientList: [],
      clientStatus: {
        0: "空闲",
        1: "忙碌"
      },
      levelList: [
        { key: 0, value: "低" },
        { key: 1, value: "中" },
        { key: 2, value: "高" }
      ],
      assetList: [],
      hasSubmit: false,
      targetType: "站点",
      taskRules1: {
        target: [{ validator: validTarget }],
        asset: [{ validator: validAsset }]
      },
      taskRules2: {
        target: [{ required: true, message: "请填写扫描对象", trigger: "blur" }]
      },
      taskRules3: {
        target: [{ required: true, message: "请填写扫描对象", trigger: "blur" }]
      },
      selectWidth: { width: "30%" },
      cardStyle: {
        height: 888 + "px"
      },
      colMargin: 16,
      userAgentList: [],
      week: [
        { key: 1, value: "星期一" },
        { key: 2, value: "星期二" },
        { key: 3, value: "星期三" },
        { key: 4, value: "星期四" },
        { key: 5, value: "星期五" },
        { key: 6, value: "星期六" },
        { key: 7, value: "星期日" }
      ],
      month: [],
      targetError: "",
      assetError: ""
    };
  },
  methods: {
    handleTargetBlur: function() {
      if (this.targetType == "站点" && this.task.target.trim() == "") {
        this.targetError = "请输入站点";
      } else {
        this.targetError = "";
      }
    },
    handleAssetBlur: function() {},
    debugChange: function() {
      console.log(this.task.notice_type);
    },
    policyChange: function() {
      console.log(this.task.crawler_policy);
    },
    handleSubmit: function() {
      var isValid1, isValid2, isValid3;

      this.$refs["task1"].validate(valid => {
        isValid1 = valid;
      });
      this.$refs["task2"].validate(valid => {
        isValid2 = valid;
      });
      this.$refs["task3"].validate(valid => {
        isValid3 = valid;
      });
      if (isValid1 && isValid2 && isValid3) {
        this.hasSubmit = true;
        if (this.targetType !== "站点") {
          this.task.target = "";
        }
        this.task.protocol = this.protocol;
        ajaxPost({
          api: "addTask",
          data: this.task
        })
          .then(res => {
            console.log(res);
            this.$store.commit("closeCurrentPage", this);
            this.hasSubmit = false;
          })
          .catch(e => {
            console.log(e);
            this.hasSubmit = false;
          });
      }
    },
    getUserAgent: function() {
      ajaxPost({
        api: "getUserAgent",
        data: {}
      })
        .then(res => {
          this.userAgentList = res.data.list;
        })
        .catch(e => {
          console.log(e);
        });
    },
    getClientList: function() {
      ajaxPost({
        api: "getClientList",
        data: {}
      })
        .then(res => {
          this.clientList = res.data.list;
        })
        .catch(e => {});
    },
    getAssetList: function() {
      ajaxPost({
        api: "getAssetList",
        data: {}
      })
        .then(res => {
          this.assetList = res.data.list;
        })
        .catch(e => {});
    },
    initMonth: function() {
      for (var i = 1; i <= 31; i++) {
        this.month.push({ key: i, value: i });
      }
    },
    targetTypeChange: res => {
      console.log(res);
      **this.$Message.info('This is a info tip');**
    }
  },
  watch: {
    task: function(val) {
      console.log(val);
    },
    protocols: function(val) {
      console.log(this.protocol);
    }
  },
  computed: {
    protocol: function() {
      var result = 0;
      if (this.protocols.indexOf("HTTPS") !== -1) {
        result++;
        if (this.protocols.indexOf("HTTP") !== -1) {
          result++;
        }
      }
      return result;
    }
  },
  mounted: function() {
    this.getUserAgent();
    this.getClientList();
    this.getAssetList();
    this.initMonth();
  }
};
</script>

**Comment by lison16** [comment]
非iview-admin设计相关的知识性问题请自行解决
