### ISSUE TITLE
解决登陆后设置权限刷新后才能生效的bug

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#195]
在演示版本中，登陆的用户名是iview_admin，权限设置为0，可显示权限测试页。
退出后以其他用户名登录，权限测试页依然可见，刷新后消失。
问题出现的原因是cookie没有主动更新，需要commit updateMenulist来更新。
只需要在login.vue增加如下代码即可：
![image](https://user-images.githubusercontent.com/27426130/32814015-0eefff8e-c9e8-11e7-851f-00f28371194c.png)

**Comment by lison16** [comment]
现已修复，谢谢详细的反馈
