### ISSUE TITLE
两个css文件404

### ISSUE THREAD

**Issue by lightming** [iview/iview-admin#196]
刚拉下来的项目,直接run dev,打开浏览器有两个css文件404,估计MarkDown编辑器页面和图片裁剪页面是因为他
![tim 20171115094533](https://user-images.githubusercontent.com/13495056/32814459-482153fa-c9ea-11e7-80c5-9aca36969e84.png)

![tim 20171115094508](https://user-images.githubusercontent.com/13495056/32814456-4343a6c6-c9ea-11e7-83b9-dac257640134.png)

![tim 20171115094550](https://user-images.githubusercontent.com/13495056/32814444-3a4c4528-c9ea-11e7-8741-72a52d649efb.png)

**Comment by lison16** [comment]
升级到最新1.2.0版
