### ISSUE TITLE
Table 组件是否有单选某一行的函数（前面的selection打勾）

### ISSUE THREAD

**Issue by hecomlilong** [iview/iview-admin#197]
<Table @on-selection-change="handleSelectionChange" @on-row-click="handleRowClick" ref="taskTable" stripe :columns="taskColumn" :data="taskList"></Table>
handleRowClick: function(data, index) {
        this.$refs.taskTable.selectRow(index,true);//没有这样的函数
    }
文档里面没列出来，
我想实现单击某一行任意区域都可以选择该行。

**Comment by dolphinfine** [comment]
多选可以打勾，单选是通过行高亮实现的。具体可以看iview的文档。
![image](https://user-images.githubusercontent.com/27426130/32974444-181ee284-cc39-11e7-91cb-5c0e97a2e553.png)

**Comment by hecomlilong** [comment]
我是想单击某一行任意区域，让前面的选择框变成选中状态。[
![image](https://user-images.githubusercontent.com/18298423/33416521-fbd02824-d5d7-11e7-8cfc-be9c8c96765e.png)
](url)
