### ISSUE TITLE
#关于webpack配置#

### ISSUE THREAD

**Issue by iT-lijun** [iview/iview-admin#199]
0. 可以针对build/*.js配置，简明介绍一下项目的webpack配置麽？比如webpack开发流程和插件的作用等。

1. 刚刚接触webpack，看iview-admin的webpack项目配置很懵逼哈。

**Comment by lison16** [comment]
如果想学习webpack建议去看文档，比较详细系统

**Comment by NLLionel** [comment]
我下载下来的项目里面就没有wabpack配置文件，怎么回事？
