### ISSUE TITLE
填坑: 关于historyApiFallback的配置

### ISSUE THREAD

**Issue by juqkai** [iview/iview-admin#201]
打算开启html5 history功能. 以.html为后缀.
后端就不说了, 主要是webpackDevServer

npm run dev的配置是在package.json配置文件中的. 如下:
```
"dev": "webpack-dev-server --content-base ./ --open --inline --hot --host 0.0.0.0 --compress --history-api-fallback --config build/webpack.dev.config.js",
```
其中根据官方文档`--history-api-fallback `, 代表着开启html5 history功能. 然而文档中还有一句话, 需要拼接上`output.publicPath`的值. 在webpack.dev.config.js中output.publicPath的配置是/dist/.

坑来了, 一旦设置了--history-api-fallback, webpackDevServer会将options.historyApiFallback 设置成true; 而且不会与devServer中的historyApiFallback进行合并, 随便你怎么配置都无效.

所以, 建议取消--history-api-fallback, 将相关的配置放在devServer中

**Comment by lison16** [comment]
已移除

**Comment by lanyongmao** [comment]
移除  --history-api-fallback  后，如果开启history，刷新页面会报404
