### ISSUE TITLE
关于以 iview_admin登录后退出，再使用 iview_admin以外的用户名登录时，左边栏依然展示权限测试页的问题

### ISSUE THREAD

**Issue by qxqd1993** [iview/iview-admin#202]
发现此问题时使用的浏览器为 Microsoft Edge 40 和 Google Chrome 61.0.3163.79。
用户来到https://iview.github.io/iview-admin/#/login 页面，使用iview_admin登录后直接退出登录，再使用其他的用户名登录，左边栏依然会如同使用iview_admin登录时一样展示出【权限测试页】选项，在使用F5刷新页面后，该选项消失。
同样，以非管理员权限登录后退出，再重新以iview_admin登录回来，不使用F5刷新页面的前提下，无法看到【权限测试页】选项。
我想请教一下造成这个问题的原因有哪些可能性呢？

**Comment by dolphinfine** [comment]
#195

**Comment by qxqd1993** [comment]
不吝赐教，甚是感谢。
