### ISSUE TITLE
linux等类unix系统中npm run dev 或 npm run build无法通过编译

### ISSUE THREAD

**Issue by coopercoder** [iview/iview-admin#204]
![2017-11-16 22-08-14](https://user-images.githubusercontent.com/18130692/32895343-b04166ec-cb1a-11e7-8f4b-a2a4fe404fca.png)
图片如图所示，windows操作系统中没有该问题，linux系统中编译无法通过。
问题定位后发现是由于这个组件大小写有问题。
Main.vue中
    import fullScreen from './main_components/fullScreen.vue';

而main_components文件夹中只有fullscreen.vue文件。

windows能够编译通过是因为win系统不区分文件名大小写，而类unix系统对大小写敏感，所以无法编译通过，希望尽快修改文件名大小写，修复该问题。

**Comment by lison16** [comment]
这个确实是写的时候没注意，mac下没报错所以没发现，现已修改
