### ISSUE TITLE
权限管理建议增加树形结构的可视化界面，根据用户的权限配置不同的路由

### ISSUE THREAD

**Issue by tong3jie** [iview/iview-admin#21]
权限管理建议增加树形结构的可视化界面，根据用户的权限配置不同的路由

**Comment by lison16** [comment]
现在支持在路由里配置每个路由的权限，然后页面左侧的菜单栏是根据权限来筛选与当前登录账户权限相匹配的菜单的。您说的可视化界面是说管理员可视化地为下级用户配置可访问的页面吗？

**Comment by tong3jie** [comment]
@lison16 没错，作为通用的后台管理系统的基本功能。可参考JAVA版本的easyUI

**Comment by hodgevk** [comment]
现在权限太简单了，不支持动态权限（比如RBAC等）。希望可以添加进来。

**Comment by anywhy** [comment]
+1

**Comment by lison16** [comment]
后面会大量增加可视化操作的demo
