### ISSUE TITLE
build 后 *.chunk.js 文件404

### ISSUE THREAD

**Issue by woody-wu** [iview/iview-admin#210]
build完成后，所有的js文件在iview-admin/dist/dist目录下， 但是打开index.html页面会往一个 根目录下发送一个 *.chunk.js请求， 例： http://localhost:8081/1.7ea21f081c7f84e51f45.chunk.js

**Comment by lison16** [comment]
你是直接打开index.html文件？没有放到服务器吗？

**Comment by woody-wu** [comment]
我本地启动的web服务,
output: {
        publicPath: 'http://localhost:8081/dist',
        filename: '[name].[hash].js',
        chunkFilename: '[name].[hash].chunk.js'
    },
我就把publicPath改了

**Comment by woody-wu** [comment]
现在好了， 可能我之前改错了，  谢谢回复
