### ISSUE TITLE
离开页面，table组件chrome偶尔报错，火狐不会

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#211]
下面是错误信息
![image](https://user-images.githubusercontent.com/27426130/33009164-f212d5c6-ce10-11e7-8d7c-71b197798e5d.png)
定位到table组件的handleResize方法，在调用这个方法时出错。
只是偶尔会触发，chrome会触发，火狐不会。

**Comment by lison16** [comment]
请确认一下这个是iview组件的问题还是iview-admin的问题？

**Comment by dolphinfine** [comment]
应该是iview组件的问题的问题吧。那我去那边提issue

**Comment by lison16** [comment]
好的
