### ISSUE TITLE
关于otherRouter 钩子函数不生效的问题

### ISSUE THREAD

**Issue by xiaoxiemagic** [iview/iview-admin#213]
您好，使用过程中遇到一个问题，otherRouter中的页面中加入activated钩子，在切换到该标签（或者第一次打开该标签），并不会被执行。
具体测试页面在个人中心和消息中心，版本：v1.1.5

**Comment by xiaoxiemagic** [comment]
activated () {
      console.log('activated ！！');
}

**Comment by lison16** [comment]
查到原因了，是因为这两个页面的vue文件中name值与路由配置中name值不一致导致的，现已修改

**Comment by xiaoxiemagic** [comment]
嗯嗯，谢谢！
