### ISSUE TITLE
希望改进地方

### ISSUE THREAD

**Issue by luo772435545** [iview/iview-admin#217]
最近在找一个做后台系统的vue框架。之前用过element ui，然后发现了iview-admin，感觉挺好的。现在刚起步搭建，发现有几个问题。比如router,store放在main.js。这个问题今天已经修复。还有遇到这些问题。
1：router这块。otherRouter和appRouter可以导出，其他路由写在routers里面。
2：cookie 和权限管理这块。如果我不需要，不是很好去除。还有比如主题这个东西，可以有，但是不应和太多地方关联，想要一个干净的框架
3：Row Input  这种首字母大写的标签实在不是很喜欢，让我有种冲动把所有组件改掉
看了半天多的框架，如果说的不对 希望不要建议哈

**Comment by lison16** [comment]
建议收到，感谢反馈，我们会尽快做一个简化版的模板
