### ISSUE TITLE
npm run dev报错

### ISSUE THREAD

**Issue by jiangsuwwj1** [iview/iview-admin#22]
ERROR in ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/Main.vue
Module not found: Error: Can't resolve './main_components/tagsPageopened.vue' in '/home/iview-admin/src/views'
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/Main.vue 11:22-69
 @ ./src/views/Main.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./~/_webpack-dev-server@2.9.2@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

ERROR in ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/markdown-editor/markdown-editor.vue
Module not found: Error: Can't resolve 'SimpleMDE' in '/home/iview-admin/src/views/my_components/markdown-editor'
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/markdown-editor/markdown-editor.vue 7:17-37
 @ ./src/views/my_components/markdown-editor/markdown-editor.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./~/_webpack-dev-server@2.9.2@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

ERROR in ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/home/components/countUp.vue
Module not found: Error: Can't resolve 'countUp' in '/home/iview-admin/src/views/home/components'
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/home/components/countUp.vue 7:15-33
 @ ./src/views/home/components/countUp.vue
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/home/home.vue
 @ ./src/views/home/home.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./~/_webpack-dev-server@2.9.2@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

ERROR in ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/count-to/CountTo.vue
Module not found: Error: Can't resolve 'countUp' in '/home/iview-admin/src/views/my_components/count-to'
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/count-to/CountTo.vue 7:15-33
 @ ./src/views/my_components/count-to/CountTo.vue
 @ ./~/_babel-loader@6.4.1@babel-loader/lib!./~/_vue-loader@11.3.4@vue-loader/lib/selector.js?type=script&index=0!./src/views/my_components/count-to/count-to.vue
 @ ./src/views/my_components/count-to/count-to.vue
 @ ./src/router.js
 @ ./src/main.js
 @ multi ./~/_webpack-dev-server@2.9.2@webpack-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main

**Comment by lison16** [comment]
这应该是你本地的问题，你可以检查下你的npm或者其他配置

**Comment by feng003** [comment]
win下正常    linux报错  大小写问题吧。
