### ISSUE TITLE
登录成功之后获取权限动态生成路由，怎么添加到路由去

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#220]
现在做一个权限管理，登录之后返回对应权限菜单，默认的路由只有首页和404，登录成功之后后台会给哪些菜单可以访问，那么我如何填充到路由当中去呢？

**Comment by lison16** [comment]
看vue-router文档

**Comment by dolphinfine** [comment]
能再提示具体一点吗？弄了一下午没搞好

**Comment by lison16** [comment]
router.addRoutes(routes)

**Comment by dolphinfine** [comment]
![image](https://user-images.githubusercontent.com/27426130/33071679-75c2c228-cef7-11e7-8cb6-9b14732000cf.png)
我添加了提示这个错误，能告诉我什么原因吗？提示我重名，但是我并没添加重名的啊。

**Comment by 18342206489** [comment]
> 看vue-router文档

他写文档的目的在于去论坛提问，贡献money
