### ISSUE TITLE
notice  bug反馈

### ISSUE THREAD

**Issue by ysjsgzq** [iview/iview-admin#221]
点击右上角全屏以后，notice弹出的通知没有显示出来，恢复默认大小就能看到刚刚弹出的通知了

**Comment by lison16** [comment]
你的iview-admin版本是多少？我刚刚试了没问题

**Comment by ysjsgzq** [comment]
@lison16  1.1.3

**Comment by lison16** [comment]
https://github.com/iview/iview-admin/releases/tag/v1.1.4

**Comment by ysjsgzq** [comment]
@lison16  我直接下载的整个项目，然后在上面做的开发。我先有点懵，我应该怎么更新你们发布的版本

**Comment by lison16** [comment]
这种情况只能查看更新日志看修改了哪些文件了

**Comment by ysjsgzq** [comment]
@lison16 额，那有没有什么更好的方法我能不影响我自己写的代码，又能及时的把你们更新的代码整合到项目里面

**Comment by lison16** [comment]
因为iview-admin不像一个组件，他是集成的一套系统，所以没办法直接合并，你可以查看更新日志，或者提交记录，每次提交都有说明

**Comment by ysjsgzq** [comment]
@lison16  额，知道了。谢谢您！
