### ISSUE TITLE
如果用户既有0的权限，又有1的权限，怎么配置？0的权限不能配置为空

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#222]
现在的需求是这样的：
1.有一些人只有1的权限
2.有些人有全部权限
3.有些人只有0的权限
请问怎么配置路由？

**Comment by lison16** [comment]
https://github.com/iview/iview-admin/wiki/router
末尾

**Comment by dolphinfine** [comment]
谢谢。明白了。

**Comment by dolphinfine** [comment]
@lison16 配置数组为什么还是不行？
![image](https://user-images.githubusercontent.com/27426130/33106799-0af802c8-cf6f-11e7-94cc-c52fc823ec3d.png)
报的错误
![image](https://user-images.githubusercontent.com/27426130/33106815-18aa20cc-cf6f-11e7-8e46-73b3993b6812.png)

**Comment by lison16** [comment]
这个错误在1.2.1修复了，是用错了isArray()，你可以修改util.js里的showThisRoute方法中的 itAccess.isArray()  为  Array.isArray(itAccess)

**Comment by dolphinfine** [comment]
@lison16 我发现在路由配置并没有作用啊。如果只给1配置权限1，其他配置权限[0,1],跟其他默认不配置access是一样的效果。1还是拥有全部权限。只有对cookie配置这样的才对啊。但是这样配置之后，[0,1]的什么都没有。
![image](https://user-images.githubusercontent.com/27426130/33107240-47bdbdcc-cf71-11e7-9cb3-b74a610c7515.png)

**Comment by lison16** [comment]
您能不能看下说明，看下怎么用

**Comment by dolphinfine** [comment]
@lison16 抱歉，可能我的理解有问题。我这样做了
![image](https://user-images.githubusercontent.com/27426130/33107589-e8b7773a-cf72-11e7-9e51-559728b1b917.png)
但是我的问题是，我权限1的用户只有1这个权限，没有0的权限，而权限0的用户只有0的权限，管理员拥有0，1权限，如果我把权限1用户权限设置为1，那么权限1用户就拥有0，1权限而不是只有1权限了。如果权限的数组那个设置为0，那么管理员如何拥有1的权限？这一点我还是有困惑。麻烦你了。

**Comment by lison16** [comment]
你这样写实现的效果是：
登录的用户如果权限值是1，那么在左侧菜单栏会显示‘代收业务统计’和’手续费查询’两个菜单，该用户可以访问这两个页面。如果登录的用户权限值是0，他只能查看到‘代收业务统计’这一个页面

**Comment by dolphinfine** [comment]
@lison16 对的。我想让1就是1，0就是0，管理员就是0和1，怎么解决呢？

**Comment by lison16** [comment]
修改源码自行实现

**Comment by dolphinfine** [comment]
好吧。谢谢了。
