### ISSUE TITLE
如何使用addRoutes动态向appRouter添加菜单？

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#225]
vue-router有个动态添加路由的方法是addRoutes，如果直接this.$router.addrouters()并没有用，因为左侧菜单是在appRouter里面，尝试对appRouter.addrouters()报错，直接扩展appRouter会提示appRouter是只读的。另外用一个数组接收appRouter，登录成功返回菜单，通过updateMenulist去合并两个路由，菜单可以显示，但是报Route with name 'xxx' does not exist。，并且刷新就报错，请问这个问题有解决方案吗？

**Comment by lison16** [comment]
这不是iview-admin的问题了，请自行google

**Comment by codeItachi** [comment]
你的问题解决了？求指教啊

**Comment by dolphinfine** [comment]
@codeItachi 部分解决了。你进这个群大家一起讨论吧。361917044烟台前端交流群

**Comment by codeItachi** [comment]
求指教

**Comment by tower1229** [comment]
动态菜单和动态路由参考这里：http://refined-x.com/2017/09/01/%E7%94%A8addRoutes%E5%AE%9E%E7%8E%B0%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1/
虽然不是用的iview，但思路可以通用。
