### ISSUE TITLE
饼图，仪表盘，滚动的时候有问题

### ISSUE THREAD

**Issue by zlichao** [iview/iview-admin#226]
饼图，仪表盘，在首页垂直滚动条下拉时，脱离了div。
可能是什么引起的？

**Comment by lison16** [comment]
麻烦说下系统和浏览器

**Comment by zlichao** [comment]
win10，qq浏览器极速内核模式

**Comment by picnic-yu** [comment]
我也遇到了这样的问题，请问你是怎么解决的呢

**Comment by zlichao** [comment]
升级浏览器，尽量不要用国产浏览器，内核都或多或少有问题。直接使用Chrome。

**Comment by nceliy** [comment]
我也遇到了这个问题了，page页面在qq浏览器里出现了问题
