### ISSUE TITLE
有没有DnD或者动态配置界面的计划?

### ISSUE THREAD

**Issue by covering** [iview/iview-admin#230]
如果能够拖拽/配置控件直接设计界面的话, 就可以从"admin 模板" 变成一个 "产品".
只需要选择控件, 为控件选择数据源. 应该就能满足后台系统了.

像很多dashboard工具都提供自己设计dashboard界面一样, 网页都是DnD设计的一样.

我在尝试, 但是因为刚接触, 有点门槛, 所以先提出来问一下. 请问有没有建议

**Comment by lison16** [comment]
暂时没有这个计划
