### ISSUE TITLE
刷新浏览器后，其他之前打开的标签消失

### ISSUE THREAD

**Issue by longzhaobi** [iview/iview-admin#236]
今天发现这个问题一直解决不了，然后用你们的运行也发现是一样的问题（之前貌似没这个问题）。之前遇到都能解决就是给localStorage.pageOpenedList赋值即可，可这次赋值后，只要刷新浏览器又给初始化了，又找不到是哪里给初始化了。

**Comment by longzhaobi** [comment]
刚刚我把
this.$store.commit('setOpenedList');
代码写到main.js就可以了。

**Comment by lison16** [comment]
现已修复，谢谢反馈
