### ISSUE TITLE
ztree 拖动异常

### ISSUE THREAD

**Issue by lilili001** [iview/iview-admin#238]
当使用第三方ztree插件的时候 拖拽异常, 拖的时候副本消失了, 前面的拖拽的指示图标也消失,想问下可有解决方法

**Comment by lison16** [comment]
能截个图让我看下你用的是iview-admin的哪个组件吗

**Comment by lilili001** [comment]
![image](https://user-images.githubusercontent.com/8953052/33157802-ab301304-d03f-11e7-969b-3a4d43543ef8.png)

用的是第三方的插件 require进来用的, 感觉像是受tab和左侧菜单的哪个事件影响, 因为我自己在纯vue2+iview的环境中测了ztree好拖

**Comment by lison16** [comment]
请自行google
