### ISSUE TITLE
小小的建议，左侧导航切换加入过渡效果

### ISSUE THREAD

**Issue by ImloserLee** [iview/iview-admin#24]
你好，项目后台非常棒，但是希望能增加一下导航切换的过渡效果，这样会给人一种流畅的感觉

**Comment by lison16** [comment]
您指的是左侧菜单栏点击收缩时的过渡还是点击菜单中不同页面时的过渡呢？

**Comment by ImloserLee** [comment]
你好，我这边是指左侧菜单栏点击收缩时的过渡，因为目前宽度的变化有种过于突兀的感觉，觉得可以加个慢慢位移的动画过渡或者其他效果，当然这只是锦上添花。

**Comment by wangdabaoqq** [comment]
不加上动画收缩或者展开就显得特别快很突兀

**Comment by lison16** [comment]
感谢大家的建议，我们会优化相关体验

**Comment by lison16** [comment]
现已增加菜单收缩过渡动画
