### ISSUE TITLE
有一段代码有点问题

### ISSUE THREAD

**Issue by sharpfeel** [iview/iview-admin#251]
[这个页面](https://github.com/iview/iview-admin/blob/dev/src/views/main-components/tags-page-opened.vue)的 **closePage** 方法感觉有点问题
场景：当只有3个标签页（首页、带参数页面、购物详情）打开时，currentPage为带参数页面，这个时候关闭带参数页面购物详情的参数就会有了。
建议改成：（81行起）
```
if (this.currentPageName === name) {
        let item = '';
        if (pageOpenedList.length > 1) {
            item = pageOpenedList[1];
        } else {
            item = pageOpenedList[0];
        }
    this.linkTo(item);
}
```

**Comment by lison16** [comment]
这确实是个没有测试出的问题，现已修复，谢谢反馈
