### ISSUE TITLE
关于DatePicker的问题

### ISSUE THREAD

**Issue by lijiasusu** [iview/iview-admin#258]
动态改变DatePicker的type时，type值变了，但是选择器样式不变。

**Comment by lison16** [comment]
请到iview的github主页提issue，谢谢

**Comment by wushuang5112** [comment]
@lijiasusu 顺带补充一下，你提[iView Github](https://github.com/iview/iview/issues?page=1&q=is%3Aissue+is%3Aopen)时说页面刷新就没问题了，应该是他们某个data继承时有问题。
