### ISSUE TITLE
动态路由里的openNewPage有啥用？直接 push 感觉没什么差别

### ISSUE THREAD

**Issue by terranc** [iview/iview-admin#262]
RT

**Comment by lison16** [comment]
是为了创建一个对应的标签

**Comment by terranc** [comment]
观感上直接 push 也会创建一个标签

**Comment by lison16** [comment]
你可以试试

**Comment by Drfengjhoo** [comment]
@lison16 什么叫做"是为了创建一个对应的标签"，抱歉，不是很明白。我和@terranc 的观点一样。

$router.push()是创建并跳转，openNewPage()只是创建，但是不跳转。是这个意思吗
