### ISSUE TITLE
编译卡住

### ISSUE THREAD

**Issue by qiangguoguo** [iview/iview-admin#269]
win10 系统 重新安装了npm包还是这样，一只卡在这里 
![1212](https://user-images.githubusercontent.com/23370836/33304517-4b0b2dfc-d444-11e7-8464-08c34efc8c7c.png)

**Comment by lison16** [comment]
不知道你这个配图是要表达什么问题

**Comment by qiangguoguo** [comment]
换成官方的vue-cli就好了
