### ISSUE TITLE
富文本编辑器 使用TAB输入框焦点移除

### ISSUE THREAD

**Issue by kitochen** [iview/iview-admin#27]
浏览器： Chrome 61
在富文本编辑器和插入编辑代码实例两个输入栏中，使用tab，焦点移除。

**Comment by lison16** [comment]
不知道您想反馈的是什么

**Comment by wakerman** [comment]
@kitochen 这又不像Word文档那样，你想在富文本编辑器里 一个tab就直接输出一个制表符 缩进？

**Comment by kitochen** [comment]
@wakerman 是的，在使用代码编辑框的时候应该很多人会习惯性使用tab缩进。

@lison16  抱歉，没讲清楚。建议在富文本编辑器键入tab的时候添加缩进。
