### ISSUE TITLE
dist打包后font路径有问题，导致所有icon均不能正常显示

### ISSUE THREAD

**Issue by LouisGo** [iview/iview-admin#271]
下图是直接build之后运行的结果以及webpack.base.config.js中的相关loader设置：

![tim 20171128143617](https://user-images.githubusercontent.com/25026983/33305536-8a5fc7a6-d449-11e7-8a5b-eba9fc765fe1.png)
![tim 20171128143736](https://user-images.githubusercontent.com/25026983/33305565-b3c91c3c-d449-11e7-9940-83041dcd9036.png)

在console中可以看到font的路径因为没有进入fonts文件夹从而没有正常引入

![tim 20171128144004](https://user-images.githubusercontent.com/25026983/33305744-4be35c44-d44a-11e7-97c2-6df8fc2c6000.png)

我通过不太严谨的方法将这行rule进行如下拆分之后：
![1511851165](https://user-images.githubusercontent.com/25026983/33305638-f75bae06-d449-11e7-8823-c85157f3423a.png)

字体可以正常引入了：
![tim 20171128144529](https://user-images.githubusercontent.com/25026983/33305854-d199f622-d44a-11e7-8334-29dc8ba7d597.png)

**不知道有没有其他靠谱的方法能解决这个问题，之前google了好久都没能解决，自己抖了小机灵发现可行，希望大神们答疑解惑~**

**Comment by dangyanglim** [comment]
/dist/不要用相对路径，我的解决方法

**Comment by LouisGo** [comment]
@dangyanglim 路径用的是./dist，文字和样式都没问题，只有iconfont出了问题

**Comment by terranc** [comment]
遇到同样的问题。

**Comment by dangyanglim** [comment]
@LouisGo 改成/dist

**Comment by LouisGo** [comment]
@dangyanglim 经过反复测试已经发现问题所在了。
publicPath那块确实不能用./dist，用了之后用live-server打开iconfont会出问题。
应该跟你刚开始说的一样用/dist/，这样是不会有问题的，另外就是/dist是不行的，bundle的js路径不对，页面加载错误了。
感谢~

**Comment by duffiye** [comment]
>         publicPath: '/dist/'   这样到后的资源文件如下，应该是不正确吧


--
  | <script type="text/javascript" src="/dist/vender-exten.503ad3f448281766c2e9.js"></script>
  | <script type="text/javascript" src="/dist/main.503ad3f448281766c2e9.js"></script>

**Comment by hetianyi** [comment]
@LouisGo 你的这种方法可行，我的需求是把web挂载到'/console'下（根路径 '/' 被另一个应用挂载了），需要相对路径。作者应该改下，影响了这么多人。

**Comment by jianxiaoBai** [comment]
@LouisGo 可以，很6，感谢分享
