### ISSUE TITLE
二级菜单国际化没有效果

### ISSUE THREAD

**Issue by ricpi** [iview/iview-admin#273]
一级菜单国际化正常，二级菜单国际化没有效果，如下图
![issue](https://user-images.githubusercontent.com/5546157/33314824-b9f7f7e8-d469-11e7-809d-8ba478580714.png)
代码：
children: [
            {
                path: 'data-update',
                icon: '',
                name: 'data-update',
                title: {i18n: 'menuDataManage'},
                component: resolve => { require(['./views/data-manage/data-update.vue'], resolve); }
            },
            {
                path: 'data-query',
                icon: '',
                name: 'data-query',
                title: {i18n: 'submenuDataDownload'},
                component: resolve => { require(['./views/data-manage/data-query.vue'], resolve); }
            }
        ]

**Comment by lison16** [comment]
这是个失误，现已修复，你也可以自己修改sidebarMenu.vue里21行的{{ child.title }}为{{ itemTitle(child) }}，谢谢反馈
