### ISSUE TITLE
点击城市级联后切换页面，城市级联没关闭

### ISSUE THREAD

**Issue by lanyongmao** [iview/iview-admin#279]
![image](https://user-images.githubusercontent.com/6235776/33356994-b56d5d26-d4fa-11e7-8512-b4f920ccbd4c.png)

**Comment by lison16** [comment]
我这测试当切换其他页面后城市及联的下拉框消失了，不知道你是怎样操作的，能说下怎么复现吗

**Comment by lanyongmao** [comment]
可能我的是前几个版本的原因吧
