### ISSUE TITLE
从github上原封不动的clone下来，然后执行npm install，然后执行 npm run build 结果无法打包

### ISSUE THREAD

**Issue by hihuangwei** [iview/iview-admin#281]
一直卡在91%

**Comment by fsjdfz** [comment]
#278

**Comment by fsjdfz** [comment]
是的 #278

**Comment by lettywiterock** [comment]
嗯，都一样，虽然我有解决方案，但是不想说，毕竟搞了半天才解决，加油吧，看到你也踩坑，莫名兴奋。

**Comment by tong3jie** [comment]
cnpm install

**Comment by hihuangwei** [comment]
![_20171129205118](https://user-images.githubusercontent.com/3166799/33415511-1add972a-d5d2-11e7-99b1-1ecd0812abe3.png)

**Comment by lison16** [comment]
在mac和win10上均试了下，都成功build了 ，如果还有问题，请看错误信息解决

**Comment by ChenWeiDi** [comment]
请提供一下可以build成功的webpack版本

**Comment by chenjunCodingGit** [comment]
@lison16 没有错误提示，Build一直卡在91%，环境是win7，其他mac  win10环境就可以
