### ISSUE TITLE
请问下要实现多个标签页共存怎么实现

### ISSUE THREAD

**Issue by 540240126** [iview/iview-admin#282]
比如说打开两个或多个富文本编辑页面，各自都能保存各自的编辑状态，切换的时候各自不影响? 请问一下要怎么实现?

**Comment by tong3jie** [comment]
main.js里面的把需要缓存的页面加入cachePage里面就可以了。

哈哈，不仔细阅读源码

**Comment by 540240126** [comment]
你说的是不同的页面当然可以，我说的是同一个页面打开多个，比如富文本编辑这个菜单可以同时打开多个标签页, 同时各自的编辑状态独立的那种

**Comment by lison16** [comment]
使用localStorage
