### ISSUE TITLE
全屏模式下锁屏的BUG

### ISSUE THREAD

**Issue by alin155** [iview/iview-admin#284]
BUG重现方式：进入全屏模式，点击锁屏。然后按esc退出全屏。此时，再去点击头像解锁，无法弹出密码输入框了，如果不刷新页面，无法再解锁。

**Comment by lison16** [comment]
暂时还未找到解决方法

**Comment by 1483799920** [comment]
解决办法 给unlock-con类添加宽高就可以了
src>main-components>lockscreen>styles>unlock.less
.unlock-con{
    width: 100%;
    height: 100%;
    ......

**Comment by lison16** [comment]
已修复
