### ISSUE TITLE
生态admin

### ISSUE THREAD

**Issue by YoungEffort** [iview/iview-admin#288]
左侧导航为什么增加个数后，路由配置会出错，就是用的iview-admin-template模板，没得错误信息，但是路由配置好了后，路由地址只有前两个后正确，后面的全部和前面的路由地址一样，相当于路由的path失效了
![094jkux cax2me 0ov z2](https://user-images.githubusercontent.com/33588367/33474115-19420576-d6b4-11e7-872f-69db74a1cfbf.png)

**Comment by lison16** [comment]
你这样连报错信息都不贴怎么知道你什么问题
