### ISSUE TITLE
1.2.1版本还能打包  1.2.2和1.2.3打包会卡住

### ISSUE THREAD

**Issue by NaClyxp** [iview/iview-admin#292]
1.2.2  1.2.3打包卡在 91% additional asset processing
不知道是不是我的问题，我下载下来直接npm install和npm run build都还是卡在 91% additional asset processing。

**Comment by lison16** [comment]
如果出现这个问题，暂时先用这个webpack.base.config.js的配置替换现在的该文件的配置：https://github.com/iview/iview-admin/blob/1cf1b34e79150632115874e7860f235634d0231b/build/webpack.base.config.js

**Comment by oleorz** [comment]
win10 v.1.23 node: 6.9.4  替换了文件还是卡住
