### ISSUE TITLE
无法编译es6的模板字符串

### ISSUE THREAD

**Issue by Avolons** [iview/iview-admin#293]
修改了babelrc的配置，使用table组件的render函数无法渲染出dom，被转义成了string

**Comment by lison16** [comment]
你这样说我没办法知道你改了什么，请参考babel文档自行解决

**Comment by Avolons** [comment]
没有修改之前也无法渲染出来，所以将presets设置为["es2017", "stage-0"]，依然无效

**Comment by lison16** [comment]
如果没有修改配置是不可能无法渲染的
