### ISSUE TITLE
win7 在npm run build时一直停留在91% additional asset processing

### ISSUE THREAD

**Issue by chenjunCodingGit** [iview/iview-admin#295]
试了很多win7都不行，翻墙npm install 或者不翻墙cnpm install都不行

**Comment by lison16** [comment]
找了个windows电脑试了下，在91%的地方确实会停顿一小会，但是几秒之后就成功了，能把命令行信息截图发来看一下吗

**Comment by xtaia** [comment]
![91%卡死](http://p067lehn1.bkt.clouddn.com/17-12-4/99208810.jpg)

**Comment by lison16** [comment]
如果出现这个问题，暂时先用这个webpack.base.config.js的配置替换现在的该文件的配置：https://github.com/iview/iview-admin/blob/1cf1b34e79150632115874e7860f235634d0231b/build/webpack.base.config.js

**Comment by xtaia** [comment]
替换以后还是一样的问题91%卡住，这个是我install的日志
![](http://p067lehn1.bkt.clouddn.com/17-12-4/21831887.jpg)

**Comment by lison16** [comment]
错误信息很明显，稍后我们会进行一个微调

**Comment by richartan** [comment]
我也刚遇到这个一模一样的问题。

**Comment by lison16** [comment]
大家node版本是多少？

**Comment by xtaia** [comment]
V8.9.0

**Comment by richartan** [comment]
v8.7.0

**Comment by chenjunCodingGit** [comment]
node的版本  v8.9.1

**Comment by lison16** [comment]
mac下是没问题的，不知道windows下是因为什么原因，还在排查，如果大家找到原因请在这里说一下

**Comment by NaClyxp** [comment]
我的8.4.0  替换了也不行

**Comment by bsdgo** [comment]
@lison16 centos下91%等了几十秒后过去了

**Comment by lison16** [comment]
目测现在就是windows系统下过不去，待我先把windows电脑修好，部门唯一的一台windows电脑，大家有解决办法先提出来~

**Comment by koiding** [comment]
正好我也出现了这个问题

系统centos
`
Linux iZbp197ylvxrbt7vmq2pbdZ 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`

NPM版本5.5.1
Node版本v8.4.0

**Comment by lison16** [comment]
个人感觉应该是使用的某个依赖的问题

**Comment by danceink123** [comment]
![image](https://user-images.githubusercontent.com/20551958/33644922-fb3f6ef6-da82-11e7-8a72-50eb42ddf042.png)
同样的问题。。。win10

**Comment by yuzhengbo** [comment]
一样的问题

**Comment by RobinGitHub** [comment]
同样的问题
![default](https://user-images.githubusercontent.com/3375920/33651164-cd0abf96-da9f-11e7-979f-f8fc82b268eb.png)

**Comment by Teemwu** [comment]
试了用node9.20、8.9.1、8.2.1、8.0.0进行打包都还是出现以下警告，虽然不影响程序运行，不过看着这堆警告提示还是好不爽的
![image](https://user-images.githubusercontent.com/16522288/33696033-4b19e6e6-db3b-11e7-9c23-2147ae5d4172.png)

**Comment by lison16** [comment]
你这个打包成功了吗

**Comment by Teemwu** [comment]
@lison16 以上node版本均打包成功，我也试了你们旧版本iview-admin-1.0.0也是还是提示这些警告的，开始以为是happypack的问题，可是1.0版本好像没有引入happypack的

**Comment by lison16** [comment]
最近很多人反馈windows下打包卡住不动，部门唯一一台windows电脑有点问题今天才能修好，所以一直没测，今天看一下这个问题

**Comment by dontcry** [comment]
win10卡在91%

**Comment by oleorz** [comment]
什么时候能修复啊 。或者新建一个分支回退一个版本给windows 发布？

**Comment by lison16** [comment]
最晚下周一吧

**Comment by nicholasyum** [comment]
new UglifyJsParallelPlugin({
            workers: os.cpus().length,
            mangle: true,
            compressor: {
                warnings: false,
                drop_console: true,
                drop_debugger: true
            }
        }),
暂时先把这个插件屏蔽掉，windows就可以打包了

**Comment by dongruinan** [comment]
坐等周一。。。求给力

**Comment by yongzhian** [comment]
同求

**Comment by yongzhian** [comment]
![tim 20171211141458](https://user-images.githubusercontent.com/6252341/33818031-b868bf48-de7d-11e7-871a-91559214f3dc.png)

**Comment by yongzhian** [comment]
确实屏蔽后可以执行

**Comment by lison16** [comment]
现在做了更新，去掉了happypack，大家根据自己的电脑性能自行选择使用happypack吧，MAC下可以使用。

**Comment by 544751779** [comment]
简化版的还不行啊   @lison16
