### ISSUE TITLE
菜单国际化

### ISSUE THREAD

**Issue by xiaojuner** [iview/iview-admin#298]
![dls 1dcie m8u86aoc8](https://user-images.githubusercontent.com/18304330/33541822-90159b14-d90b-11e7-8556-cbe271d99df0.png)
左侧菜单国际化，这个是不是没完善呢

**Comment by lison16** [comment]
二级菜单多语言bug已经修复了https://github.com/iview/iview-admin/commit/27f16d571cd14eb15f90277a534bd0737157c9dd
