### ISSUE TITLE
建议增加关闭标签操作

### ISSUE THREAD

**Issue by wakerman** [iview/iview-admin#3]
![image](https://user-images.githubusercontent.com/3078413/31654918-06c49624-b2ed-11e7-8385-a21b1a33fc5c.png) 【效果】
比如页面打开太多标签的情况，要一个个去x掉 有点累 啊
![image](https://user-images.githubusercontent.com/3078413/31654957-1ffe1f7a-b2ed-11e7-9e6e-210173066514.png)

**Comment by lison16** [comment]
谢谢提的建议，很实用的功能，很快会加入

**Comment by lison16** [comment]
现已增加‘关闭所有’和‘关闭其他’功能

**Comment by janchengwang** [comment]
感觉这个右键关闭比较好吧，多一个标签选项感觉很占地方

**Comment by wakerman** [comment]
@janchengwang 右键关闭从体验角度来说不好。如果一个新人使用会一脸懵逼

**Comment by lison16** [comment]
所以说需求是各异的，iview-admin提供功能实现的方法和接口，至于业务中如何设计那要自己去修改了
