### ISSUE TITLE
ubuntu 环境下运行报错

### ISSUE THREAD

**Issue by feng003** [iview/iview-admin#30]
![image](https://user-images.githubusercontent.com/3939670/31751579-bd099ef8-b4b8-11e7-88e4-2d34cfb813f4.png)

是文件权限问题？ 还是 node（v7.7） 版本问题？

**Comment by lison16** [comment]
找不到countup这个依赖包，您可以重新运行一下npm install

**Comment by wangdabaoqq** [comment]
我重新npm install 还是不可以

**Comment by feng003** [comment]
![image](https://user-images.githubusercontent.com/3939670/31752172-3fb6a910-b4bc-11e7-93ea-b5230b2a2218.png)

是有两个依赖没有安装上，手动安装后，图片最上部的错误是什么情况？会不会存在大小写的错误？在win下跑一遍没有任何问题

**Comment by lison16** [comment]
您好，我们在mac和win下都运行过，可以正常运行，请您检查下自己的环境，和相关依赖，感谢您的支持

**Comment by feng003** [comment]
是有四个文件的引入存在大小写的问题。Main.vue  79行 

![image](https://user-images.githubusercontent.com/3939670/31752553-1a2913f2-b4be-11e7-881f-3187f6cd1199.png)

这三个文件引入都存在大小写问题，在ubuntu  编译的时候报错，修改了就可以了。

**Comment by lison16** [comment]
好的，有其他问题欢迎反馈

**Comment by janchengwang** [comment]
我是deepin系统，报错一样，那四个文件是自己写的，不是npm install的问题。不知道为什么linux会出现大小写问题。。

**Comment by feng003** [comment]
跟npm 没有关系吧。是 运行的到时候  webpack 编译失败了
