### ISSUE TITLE
npm run dev 开发环境下 修改.vue单文件的style,LESS 样式不发生变化 必须重新刷新

### ISSUE THREAD

**Issue by Eunknight** [iview/iview-admin#301]
如题

npm run dev 运行开发环境，
修改 html 有热加载，
修改vue单文件的style 和 less 样式没有热加载。
必须重新刷新，新的样式才起作用。
该如何修改配置？
谢谢。

补充细节：
iview-admin 1.2.3 依然不起作用 (刚刚测试确认).
template模板也有这个问题.

F12 console 提示

> [WDS] Hot Module Replacement enabled.
client?c877:80 [WDS] App updated. Recompiling...
client?c877:212 [WDS] App hot update...
dev-server.js:45 [HMR] Checking for updates on the server...
**log-apply-result.js:18 [HMR] Nothing hot updated.**
dev-server.js:27 [HMR] App is up to date.

vue-cli 的提示。

> [WDS] App updated. Recompiling...
18:40:50.741 vconsole.min.js:11 [WDS] App hot update...
18:40:50.741 vconsole.min.js:11 [HMR] Checking for updates on the server...
18:40:51.062 vconsole.min.js:11 [HMR] Updated modules:
18:40:51.066 vconsole.min.js:11 [HMR]  - 2
18:40:51.067 vconsole.min.js:11 [HMR] Consider using the NamedModulesPlugin for module names.
18:40:51.068 vconsole.min.js:11 [HMR] App is up to date.

**Comment by lison16** [comment]
更新代码，这个问题已经修复了

**Comment by Eunknight** [comment]
刚刚测试, 依然有这个问题.

**Comment by Eunknight** [comment]
谢谢
https://github.com/iview/iview-admin/commit/6aa98fdcbe54cdacc3bd71ca920b52433742b810
