### ISSUE TITLE
请问如何在当前标签页跳转页面？

### ISSUE THREAD

**Issue by xiaoxiemagic** [iview/iview-admin#306]
您好，问题如上，该功能主要应用在中央主体页面中如果存在父子级的页面切换，页面示例如下：
![image](https://user-images.githubusercontent.com/12682954/33594564-5edb0cb8-d9cf-11e7-858a-73ec712b50f6.png)

**Comment by lison16** [comment]
你这个比较偏业务了，需要自行根据需求修改iview-admin源码

**Comment by xiaoxiemagic** [comment]
好吧，谢谢。图示只是一个应用方面，真实想实现的是当前标签页跳转页面

**Comment by xiaoxiemagic** [comment]
之前想过在**appRouter**下面增加三级路由，但是三级路由并不在左侧显示（ 三级路由只标识为子路由，这样就不用全部写在**otherRouter**中，项目持续开发导致**otherRouter**过大且比较乱），在二级路由页面中跳转三级路由时可以选择是否打开新标签页跳转页面。
---
纯个人见解。。。

**Comment by lison16** [comment]
iview-admin只是基础，比较偏业务的实现还是需要自己来决定

**Comment by xiaoxiemagic** [comment]
好的，没这个功能会让标签很容易开启很多，我自己处理一下吧，谢谢
