### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by Pluuuto** [iview/iview-admin#308]
系统：MacOS 10.13.1
node: v8.9.0
npm: 5.5.1

执行 npm install 后，报错如下：

> 10404 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ependencies":{"babel-'
> 10404 verbose stack     at JSON.parse (<anonymous>)
> 10404 verbose stack     at parseJson (/Users/luke/.nvm/versions/node/v8.9.0/lib/node_modules/npm/node_modules/pacote/no      de_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
> 10404 verbose stack     at consumeBody.call.then.buffer (/Users/luke/.nvm/versions/node/v8.9.0/lib/node_modules/npm/nod      e_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
> 10404 verbose stack     at <anonymous>
> 10404 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
> 10405 verbose cwd /Users/luke/Code/vue/iview-admin
> 10406 verbose Darwin 17.2.0
> 10407 verbose argv "/Users/luke/.nvm/versions/node/v8.9.0/bin/node" "/Users/luke/.nvm/versions/node/v8.9.0/bin/npm" "i"
> 10408 verbose node v8.9.0
> 10409 verbose npm  v5.5.1
> 10410 error Unexpected end of JSON input while parsing near '...ependencies":{"babel-'
> 10411 verbose exit [ 1, true ]
>

**Comment by Pluuuto** [comment]
补充，npm镜像使用的是taobao

> $ nrm ls
> 
>   npm ---- https://registry.npmjs.org/
>   cnpm --- http://r.cnpmjs.org/
>   *taobao - https://registry.npm.taobao.org/
>   nj ----- https://registry.nodejitsu.com/
>   rednpm - http://registry.mirror.cqupt.edu.cn/
>   npmMirror  https://skimdb.npmjs.com/registry/
>   edunpm - http://registry.enpmjs.org/
>

**Comment by lison16** [comment]
我试了对应版本下install没有问题，你用npm不要用cnpm装再试试

[cid:D3B36A5C-DA82-422A-866E-0E7046385137]

**Comment by linziguan** [comment]
先用npm update，更新一下，然后再npm install
