### ISSUE TITLE
能否提供一个空白的项目脚手架

### ISSUE THREAD

**Issue by my3157** [iview/iview-admin#31]
可否提供一个只包含登录页和菜单布局, 以及空白页的admin脚手架,   现在里面集成了很多东西,  用的时候得先把不用的删掉,

**Comment by lison16** [comment]
很快会出一套iview-admin的模板，现在上线的iview-admin应该说是一套后台管理方案，做模板用的话确实不适合，所以我们很快会出简化版的模板，敬请期待
