### ISSUE TITLE
文章发布富文本编辑器不能编辑问题是如何修复的？

### ISSUE THREAD

**Issue by DragonT** [iview/iview-admin#310]
请问新版本的文章发布富文本编辑器不能编辑问题是如何修复的可以说下吗？因为之前的版本已经用在项目里了，谢谢！[#166](https://github.com/iview/iview-admin/issues/166)

**Comment by lison16** [comment]
暂时的做法是关闭缓存带有富文本编辑器的页面，也就是在store的dontCache数组中添加此页面的name值
