### ISSUE TITLE
开发环境下的端口号在哪配置的，找了好久没有找到。。。

### ISSUE THREAD

**Issue by xuweimeng** [iview/iview-admin#312]

**Comment by yakun0622** [comment]
webpack.dev.config.js中，增加如下配置：
```
devServer: {
        port: ${port},  // 指定端口号
        proxy: ${proxyTable:{}}  // 这里可以增加代理配置
}
```

或者在package.json中增加启动参数：--port 8080
`"dev": "webpack-dev-server --content-base ./ --open --inline --hot --port 8080 --compress --config build/webpack.dev.config.js",`

**Comment by xuweimeng** [comment]
可以的，谢谢
