### ISSUE TITLE
为什么ivew的样式scoped不能覆盖全局样式

### ISSUE THREAD

**Issue by YoungEffort** [iview/iview-admin#313]
为什么ivew的样式scoped不能覆盖全局样式，我用了!important也不能覆盖原来的iview样式

**Comment by ForeveHG** [comment]
你要覆盖iview组件的样式就不能用scoped，scoped只能修改当前组件的样式，子组件的改不了

**Comment by liuqi07** [comment]
可是如果我只想在当前组件内生效，比如修改table组件中的thead的样式，就不生效，请问是怎么解决的？

**Comment by ForeveHG** [comment]
@liuqi07 不太明白你的意思，你是想只在某个组件里覆盖iview组件的样式，其他时候还是iview组件的默认样式么？？

**Comment by king7329178** [comment]
这个问题很简单  如果要修改样式  你在组件头部 加入
 <style lang="less">
  @import './role.less';
  @import '../../../styles/common.less';
</style>

role.less内容
.自己起的class   .ivu-card-head {
  border-bottom: 1px solid #e9eaec;
  padding: 20px 16px;
  line-height: 1;
  background-color: lightsteelblue;
}
