### ISSUE TITLE
二级菜单只有一个的时候，一级菜单标题应该显示二级菜单标题

### ISSUE THREAD

**Issue by mangyusisha** [iview/iview-admin#318]
二级菜单只有一个的时候，一级菜单标题应该显示二级菜单标题
下图有二级菜单有三个，但是设置开放权限的时候 只开放一个管理组设置，然后一级菜单还是显示系统设置标题
![image](https://user-images.githubusercontent.com/21302769/33703813-ae340e18-db64-11e7-9875-97eec0702785.png)
![image](https://user-images.githubusercontent.com/21302769/33703853-e0dae864-db64-11e7-8031-a3a78b0ebd4e.png)

**Comment by lison16** [comment]
这个可以根据自己需求自己修改源码
