### ISSUE TITLE
Util.inOf 方法错误

### ISSUE THREAD

**Issue by GuoYingxu** [iview/iview-admin#321]
阅读源码的时候发现 Util.inOf 方法貌似写错了。虽然，项目中并没有用到这个方法。

源代码为

      `util.inOf = function(arr, targetArr) {
         let res = true;
         arr.map(item => {
           if (targetArr.indexOf(item) < 0) {
            res =  false;
           }
         })
         return res
       }`

应当改为  res = res && false

      `util.inOf = function(arr, targetArr) {
         let res = true;
         arr.map(item => {
           if (targetArr.indexOf(item) < 0) {
             res = res && false;
           }
         })
         return res
       }`

**Comment by lvpython** [comment]
确实有问题，可以发个PR

**Comment by smartymoon** [comment]
不理解 res && false 的意义何在，望赐教

**Comment by GuoYingxu** [comment]
@smartymoon  && 符号是 与的意思，true  && true  == true         true && false == false,
这里在循环中使用res && false ，保证只要有一次 是false  ，返回结果就是false 。所有的结果为true ，最后结果才是true 。

**Comment by smartymoon** [comment]
@GuoYingxu 谢谢

**Comment by GuoYingxu** [comment]
@smartymoon  这里其实源代码 并没有什么问题。 循环过程中， res 并没有赋值true 可能。 所以一但res ＝ false 最后结果就是false 。源代码没有问题。这里不用改。是我想错了
