### ISSUE TITLE
iview-admin   字体文件相对路径的问题

### ISSUE THREAD

**Issue by Leslie-Luo** [iview/iview-admin#323]
我在`webpack.prod.config.js`中修改 `publicPath: './dist/',` 为相对路径，但是在localhost进入对应文件夹后，网站icon字体引入失败，请问怎么解决
[![QQ20171210-225930.png](https://i.loli.net/2017/12/10/5a2d4be7478d6.png)](https://i.loli.net/2017/12/10/5a2d4be7478d6.png)

**Comment by coopercoder** [comment]
同问。。。不太会玩。。。谁来帮帮我们

**Comment by leeson8888** [comment]
通常publicPath 都不能用相对路径，报错vue-cli生成的项目。
你换成绝对路径，然后放在网站根目录就可以了。
如果一定要用绝对路径，可以自己修改 webpack 的关于字体文件的loader 配置

**Comment by fighthorse** [comment]
publicPath 都不能用相对路径，用绝对路径 就可以解决了
