### ISSUE TITLE
运行dev  提示api废弃  我该怎么解决

### ISSUE THREAD

**Issue by lee134134134** [iview/iview-admin#33]
环境  nodejs 8.7.0  npm 5.4.2

运行dev 报错如下：

(node:22545) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRNOTAVAIL 172.16.52.134:8080
    at Object._errnoException (util.js:1021:11)
    at _exceptionWithHostPort (util.js:1043:20)
    at Server.setupListenHandle [as _listen2] (net.js:1327:19)
    at listenInCluster (net.js:1385:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1494:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:100:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iview-admin@1.0.0 dev: `webpack-dev-server --content-base ./ --open --inline --hot --compress --history-api-fallback --config build/webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the iview-admin@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/leemuzi/.npm/_logs/2017-10-19T06_07_11_265Z-debug.log

**Comment by baidawei20170717** [comment]
同问

**Comment by lee134134134** [comment]
"eslint": "^4.9.0"   这里修改一下  重新npm i
