### ISSUE TITLE
求助。组件注册的代码在哪里

### ISSUE THREAD

**Issue by easyfast** [iview/iview-admin#333]
仿照iviewadmin在写界面，发现路由跳转了，但是组件没加载，此时意识到应该是组件没有注册原因，回头看iviewadmin的源码，在man.js中，也没有发现注册组件的源码，求助，注册组件的代码在哪里？

**Comment by HazyLiA** [comment]
好像在父组件的script里，看components

**Comment by dontcry** [comment]
`// 不作为Main组件的子页面展示的页面单独写，如下
export const loginRouter = {
    path: '/login',
    name: 'login',
    meta: {
        title: 'Login - 登录'
    },
    component: resolve => { require(['@/views/login.vue'], resolve); }
};
`
iview的路由里面不是直接引入vue文件做为组件了吗？

**Comment by dontcry** [comment]
你是不是引用的组件路径有问题。
