### ISSUE TITLE
更新后的vue-warn

### ISSUE THREAD

**Issue by guowangsheng** [iview/iview-admin#334]
更新后提示了一堆警告 vue.esm.js:574 [Vue warn]: Duplicate keys detected: 'table-to-image'. 之类的
还有[Vue warn]: Do not use built-in or reserved HTML elements as component id: Button等等

**Comment by dontcry** [comment]
同提示

**Comment by qianzhicheng** [comment]
今天还想把项目更新来着，看到一堆的vue-warn还是再等等好了...

**Comment by dontcry** [comment]
把vue降级就好了，看官网提示。

**Comment by lison16** [comment]
这个主要是因为vue升级到2.5.10之后iview组件使用了html标签名的原因，看Iview官网的提示

**Comment by chenyucheng** [comment]
vue  降级到 多少

**Comment by chenyucheng** [comment]
@lison16  能贴一下   iview 官网的 提示  网址吗？没找到。降级到多少？

**Comment by cverymuch** [comment]
![image](https://user-images.githubusercontent.com/24564316/42621028-31af469c-85ef-11e8-877f-dc77c8f71245.png)
这样能解决
