### ISSUE TITLE
包要升级?打开页面出错

### ISSUE THREAD

**Issue by hulord** [iview/iview-admin#339]
![t9gtazq 9z j9jvv e_u](https://user-images.githubusercontent.com/19884284/34028796-1878b288-e1a0-11e7-9f7d-719458604d1f.png)
安装提示说是几个组件要更新
但是run没提示什么错误
![zzw79lcpn1m svn_e 4f37c](https://user-images.githubusercontent.com/19884284/34028864-727f1e98-e1a0-11e7-8f48-ca23542515d9.png)
打开项目功能可以用但是console一堆错误

**Comment by liushaokun** [comment]
关注中

**Comment by coopercoder** [comment]
key重复的问题 改一下sidebarMenu.vue,把里面的key自己改成不重复的就可以了。或者等iview-admin更新吧

**Comment by chenyucheng** [comment]
关注中。昨天也在解决这个问题，还没解决。。

**Comment by liushaokun** [comment]
二楼说得对，我也解决了 就是key重复问题
 <template v-for="item in menuList">
            <MenuItem v-if="item.children.length<=1" :name="item.children[0].name" :key="item.path">
                <Icon :type="item.icon" :size="iconSize" :key="item.path"></Icon>
                <span class="layout-text" :key="item.name">{{ itemTitle(item) }}</span>
            </MenuItem>

            <Submenu v-if="item.children.length > 1" :name="item.name" :key="item.path">
                <template slot="title">
                    <Icon :type="item.icon" :size="iconSize"></Icon>
                    <span class="layout-text">{{ itemTitle(item) }}</span>
                </template>
                <template v-for="child in item.children">
                    <MenuItem :name="child.name" :key="child.name">
                        <Icon :type="child.icon" :size="iconSize" :key="child.name"></Icon>
                        <span class="layout-text" :key="child.name+1">{{ child.title }}</span>
                    </MenuItem>
                </template>
            </Submenu>
        </template>


我把sidebarMenu.vue  改成如上就好了

**Comment by chenyucheng** [comment]
Do not use built-in or reserved HTML elements as component id: Circle
 Do not use built-in or reserved HTML elements as component id: Switch
@lison16

**Comment by lison16** [comment]
最新版已修复， @chenyucheng 你的问题可以更新最新的iview

**Comment by zhaoli-Git** [comment]
用了liushaokun的方法，还是没解决问题

**Comment by liushaokun** [comment]
Do not use built-in or reserved HTML elements as component id: Circle
Do not use built-in or reserved HTML elements as component id: Switch

ivew 2.8.0版本 解决了如上问题呀  现在已经OK了
