### ISSUE TITLE
当前tab页怎么刷新？

### ISSUE THREAD

**Issue by xiaoxiemagic** [iview/iview-admin#340]
你好，怎么js控制刷新该tab

**Comment by leeson8888** [comment]
具体点。
如果是菜单切换，你可以watch 路由变化即可

**Comment by xiaoxiemagic** [comment]
嗯嗯，路由不变化，但需要手动刷新当前tab页

**Comment by xiaoxiemagic** [comment]
比如，打开了a，b两个页面，在a页面中操作了数据，该数据也在b中显示，切换回b时候（路由并不产生变化），显示的还是未操作之前的数据

这种情况只能通过activated钩子函数来实现吗？

**Comment by lison16** [comment]
那你可以通过vuex实现

**Comment by xiaoxiemagic** [comment]
@lison16 你好，这个问题怎么直接关闭了呢，，，

vuex只是本地状态管理，更新数据实在服务器端。你意思是通过vuex管理页面数据是否已更新的tag，然后相关页面再监听这个值判断是否去更新本页的数据？

**Comment by chanhz** [comment]
你好，我认为你的问题，再请求一次就好了...

**Comment by shawon1220** [comment]
provide / inject  控制，具体参考 https://blog.csdn.net/qq_16772725/article/details/80467492
