### ISSUE TITLE
npm安装和cnpm效果不同

### ISSUE THREAD

**Issue by wond-z** [iview/iview-admin#341]
## 1. 当使用npm安装时，tree的render函数无效果，cnpm安装正常
![img](https://github.com/wond-z/Pic/blob/master/TIM%E5%9B%BE%E7%89%8720171218091139.png?raw=true)
## 2. 当使用npm安装时，控制台不会报标签警告，cnpm会显示vue warn

使用cnpm安装后
![img](https://github.com/wond-z/Pic/blob/master/vue-warn.png?raw=true)

**Comment by lison16** [comment]
所以建议用npm 安装

**Comment by wond-z** [comment]
问题已解决，是安装依赖的版本不同导致的，使用cnpm安装的是package.json中定义的依赖，而使用npm安装会优先安装之前生成的package-lock.json中定义的依赖，所以最好的安装依赖方式是先删除package-lock.json文件，然后使用npm安装

**Comment by liuqi07** [comment]
遇到了相同的问题，使用npm安装依然有这个问题，删除了package-lock.json后解决，感谢
