### ISSUE TITLE
建议：项目客户化改造以及IE兼容方案

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview-admin#343]
前端时间copy了项目，满心欢喜的改造
先声明文笔较乱，以后修改，因为忙着开发，太急了
先说截止到现在改造了哪些内容
1、css预处理器从less改为了sass
2、登录页（采用antd的方案，好处：加载速度快、页面简洁符合大众）
![default](https://user-images.githubusercontent.com/30425581/34096569-ca900e54-e410-11e7-94e9-97a3bc22f4a6.png)
3、左侧导航（页面背景色更改，页面加宽，去除了恶心的滚动条，是不是显得高端了）
![default](https://user-images.githubusercontent.com/30425581/34096589-e528986c-e410-11e7-884b-97906bbeb1e8.png)
4、整理布局（现在是antd的方案，就是页头和左侧导航一起滚动，后期考虑用状态管理灵活切换）
![default](https://user-images.githubusercontent.com/30425581/34096741-7652932e-e411-11e7-8ac6-dbd6380e9e30.png)
5、构建配置（用的最新的vue-cli webpack template大坑啊，这个等会说）
没有用官方的这个是因为，代码规范实在不习惯，还有就是我们有其他项目希望统一构建配置
而且构建配置中存在iview的代码（汗）
6、废弃掉了axios的集成，自己做的，跨域什么的都可以（现在请求中也调用loadbar）
7、添加了日期处理等一些工具类，也自己写了method的混合，用来处理男或则女啊，后台过来的翻译

最后说说兼容性的情况
我们目标兼容ie10
添加了babel-polyfill，但是还是不能成功
ie一直提示语法错误
最后得知vue-cli已从最开始的express服务器转为了wepack-dev-server，这个没办法只用采用express的方式或则是用wepack-dev-server的低版本
然后发现主题不能更改了，算了，干掉吧，毕竟锦上添花的东西，可能是构建配置改了，还没来得及看
而且主题色不用过于更改，左侧导航背景色能改就行，毕竟绿色和红色都算是系统保留色吧，最好不要改这个
然后又满心开心的启项目
完了，还是不行，我的天啊，只想唱一句：你还想我怎样 还想我怎样
算了接着弄吧
这个时候发现是多语言的问题
admin中直接import的这个
![default](https://user-images.githubusercontent.com/30425581/34097173-0ef82552-e413-11e7-9c75-547dfef49b1d.png)
然后就是webpack没有从es6转到es5（可能和我webpack引入的babel-polyfill方式有关，没有继续看）
`import zhLocale from 'iview/dist/locale/zh-CN'`
结果项目正常启动
最后提醒的是vue-i18n只能5.0.3版本，后面的版本有问题，始终提示i18n未定义，我都new对象了，也按照说明文档的就是不行
至于提示这个得问题
![default](https://user-images.githubusercontent.com/30425581/34098018-ffbd1f90-e415-11e7-8a77-e0c824f749a5.png)
可以参照这个 https://github.com/iview/iview/issues/2057

而且首页的加载速度确实太慢了，现在正在用占位组件或则其他方式延迟渲染，类似antd的pro

**Comment by 613660067** [comment]
也刚刚遇到IE兼容问题，我们是兼容IE11就可以，但是也有不少坑

**Comment by EdikWang** [comment]
昨天搞一半天不行，今天准备自己重构了。。。。

**Comment by gitzhangfugui** [comment]
@613660067 兼容ie11应该好弄 主要配置就几个 还有有些样式要更改

**Comment by gitzhangfugui** [comment]
@EdikWang 。。。。。。。 其实只有src的代码有用 构建配置用自己的就行

**Comment by EdikWang** [comment]
嗯，我再试试

**Comment by Fea-Sin** [comment]
vue  国际化（iview, vue-i18n） 不支持 IE 10， IE 9 不支持，之前我没加 国际化之前能够兼 ie 9 之上的浏览器

**Comment by 15994028931** [comment]
已经按照步骤改过了，还是不能兼容ie10和ie9，报语法错误
![image](https://user-images.githubusercontent.com/29727795/39904550-1a8dec94-550b-11e8-9d4b-10ff04f82458.png)

**Comment by coolerTang** [comment]
我们要用iview兼容ie8，我打算换工作了，有坑吗

**Comment by sunhongjian** [comment]
说来说去最关键的其实是wepack-dev-server
