### ISSUE TITLE
Spin组件，在绿，红，黄三种主题下面显示不正常

### ISSUE THREAD

**Issue by xiaopanghhh** [iview/iview-admin#347]
Spin组件，在绿，红，黄三种主题下面显示不正常。
背景颜色不是半透明的，提示消息和图标在最顶部。

**Comment by lison16** [comment]
现已修复，更新最新g.css、y.css和r.css样式文件

**Comment by xiaopanghhh** [comment]
经过测试,发现问题还是没有解决。在 火狐下面正常了。 但是 Chrome 和 Safari 下还是不正常。Safari 的版本是 11.0.2 ， Chrome 的版本是62.0.3202.94。

**Comment by lison16** [comment]
你替换最新的样式文件了吗

**Comment by xiaopanghhh** [comment]
替换了，替换之前火狐也不能正常使用。替换了以后火狐正常了，但是 Chrome 和 Safari 不正常。
