### ISSUE TITLE
希望加入模态窗

### ISSUE THREAD

**Issue by YouNOFish** [iview/iview-admin#35]
很常见的需求，比如说处理表单的时候，点击查看弹出详情。

**Comment by lison16** [comment]
模态框在iview组件库里有，你可以查看iview官方文档来使用，在iview-admin首页当中也用到了模态框，点击待办事项中的添加新的事项时会弹出模态框来添加事项。

**Comment by YouNOFish** [comment]
谢谢，看到了。
