### ISSUE TITLE
页面加载完第一个TabPane标签disabled属性不能生效

### ISSUE THREAD

**Issue by hecomlilong** [iview/iview-admin#351]
<Tabs type="card" @on-click="handleTabClick">
<TabPane label="忙碌客户端" :disabled="!tabBusy">
</TabPane>
<TabPane label="空闲客户端" :disabled="!tabIdle">
</TabPane>
<TabPane label="下载客户端">
</TabPane>
</Tabs>

当页面初始化完成后tabBusy为false，因此，!tabBusy为true，也就是disabled属性为true，但是第一个Tab，也就是《忙碌客户端》这个Tab并没有被disable掉，需要点一下其他Tab才会刷新成disabled状态，而tabIdle同样为false，第二个Tab 空闲客户端 就会正确显示成disabled状态

**Comment by lison16** [comment]
你这个是iview组件的问题吧，请到iview的github主页提issue
