### ISSUE TITLE
Shrinkable-Menu 键重复

### ISSUE THREAD

**Issue by traineeyang** [iview/iview-admin#352]
[Vue warn]: Duplicate keys detected: 'person'. This may cause an update error.

found in

---> <SidebarMenu> at src/views/main-components/shrinkable-menu/components/sidebarMenu.vue
       <ShrinkableMenu> at src/views/main-components/shrinkable-menu/shrinkable-menu.vue
         <Main> at src/views/Main.vue
           <App> at src/app.vue
             <Root>

登录进去之后，控制台报 key 重复的错误，请问是什么原因？

**Comment by gao1383979** [comment]
同问，我的也报这个错误

**Comment by traineeyang** [comment]
可能是我执行了npm update的原因吧，我把 package.json 还原回去之后，问题消失了。

**Comment by yyman001** [comment]
@traineeyang 可以发下 `package.json` 的信息吗？vue 用的什么版本？我用 `electron` 封装的页面也会出现这个问题，"vue": "^2.3.3"

**Comment by wangweilica** [comment]
[修改sidebarMenu.vue文件](https://sfault-image.b0.upaiyun.com/194/485/1944856817-5a38a88bda9ad)

**Comment by yyman001** [comment]
听说是新版本vue更换代理模式导致的，最近用一个vddl拖着插件也是会有这种问题，问了作者，说是版本问题，只能暂时做降级vue版本。。。蛋疼

**Comment by lison16** [comment]
已修复

**Comment by Eunknight** [comment]
如何手动修复?
