### ISSUE TITLE
打开多个tab，关闭当前tab时没有重新计算left值，导致整个tab栏并没有移动到视野范围中

### ISSUE THREAD

**Issue by LouisGo** [iview/iview-admin#356]
问题产生时机：
![image](https://user-images.githubusercontent.com/25026983/34283711-621a1112-e708-11e7-805e-2af53d6c836c.png)

问题出现：
![image](https://user-images.githubusercontent.com/25026983/34283736-81ca00b2-e708-11e7-855b-a104a0c5a76a.png)

感觉应该是moveToView方法判断条件没有包含这种情况：
![image](https://user-images.githubusercontent.com/25026983/34283755-9789ff4c-e708-11e7-9f3a-0bc45fc8ce69.png)

**Comment by lison16** [comment]
thank u

**Comment by LouisGo** [comment]
@lison16 感谢大佬才是~

**Comment by lison16** [comment]
现已修复
