### ISSUE TITLE
请教Select 组件怎样加图标？

### ISSUE THREAD

**Issue by jjwangel** [iview/iview-admin#358]
就像Input那样：
<FormItem prop="user">
            <Input type="text" v-model="formInline.user" placeholder="Username">
                <Icon type="ios-person-outline" slot="prepend"></Icon>
            </Input>
        </FormItem>

请教Select 组件怎样加图标？

**Comment by jjwangel** [comment]
`<FormItem prop="user">
            <Input type="text" v-model="formInline.user" placeholder="Username">
                <Icon type="ios-person-outline" slot="prepend"></Icon>
            </Input>
        </FormItem>`

**Comment by lison16** [comment]
虽然这不是admin的问题范围，但是可以回答你一下，select组件没有这个api，你如果有这个需求，可以修改iview源码然后打包替换你的node_module里的iview
