### ISSUE TITLE
github 提示依赖到库有漏洞，这个有哪个版本更换了依赖版本吗？

### ISSUE THREAD

**Issue by gitors** [iview/iview-admin#360]
因为我自己打算改一些东西来用了，为了更好到控制我自己到修改版本，我没有fork，而是自己完全复制了一份出来， 在上传到github 上之后，github 提示依赖有漏洞，我应该忽略还是怎么处理呢？

![image](https://user-images.githubusercontent.com/31715318/34319415-ec3ff39c-e81c-11e7-97b8-5b0d423879b0.png)

**Comment by lison16** [comment]
开发没有遇到这个问题，请根据提示自己更新依赖
