### ISSUE TITLE
找不到iview-area这个版本

### ISSUE THREAD

**Issue by Afbt** [iview/iview-admin#362]
![snipaste_20171225_150942](https://user-images.githubusercontent.com/33228256/34334941-0f283c6a-e986-11e7-8759-784fdfccf405.png)

**Comment by Afbt** [comment]
解决了   修改package.json里  iview-area版本改成1.5.12  还有修改package-lock.json里iview-area版本修改成1.5.12

**Comment by lison16** [comment]
使用npm 安装iview-area@1.5.14安装不了吗

**Comment by Afbt** [comment]
是版本没有更新把使用npm安装iview-area@1.5.14下载不了

**Comment by lison16** [comment]
不会吧，我刚试过可以啊，https://www.npmjs.com/package/iview-area 最新版本也是1.5.14啊

**Comment by Afbt** [comment]
晕  我要吐血 弄了一天 才发现 自己选 cnpm的路径没切回来  我这只菜鸟啥时候能跟上你们的步伐

**Comment by SingularityXD** [comment]
只有从npm才能下iview-area@1.5.14,cnpm或者淘宝镜像或者yarn都找不到这个包

**Comment by Teemwu** [comment]
用nrm进行版本检测的时候也没发现iview-area@1.5.14这个版本，后来直接npm install iview-area@1.5.14就可以了，iview@2.8.0同理

**Comment by cqgsm** [comment]
不行啊，怎么试都找不到这个包

**Comment by lison16** [comment]
用npm装

**Comment by cqgsm** [comment]
就是npm啊

**Comment by Afbt** [comment]
你用的淘宝路径 或是其他路径把  要切换回npm 的下载路径

**Comment by cqgsm** [comment]
npm config set registry https://registry.npmjs.org/   好了，谢谢！能拉个群交流下么？

**Comment by BerlinChan** [comment]
我clone下来iView-admin v1.2.3，Win10，Node9.2.1，npm5.5.1
npm库无论用taobao、npmjs、cnpm，install都报错：iview-area版本不对，无法解析webpack/babel-loader/style-loder...。npm run dev也错

**我的笨办法：**

1. 安装yarn
2. 将package.json中dependencies、devDependencies指定的依赖全部删掉
3. 将依赖的版本全部手动安装一遍，类似下面

`yarn add area-data@1.0.0 axios@0.17.1 clipboard@1.7.1 countup@1.8.2 cropperjs@1.1.3 echarts@3.8.5 html2canvas@0.5.0-beta4 iview@2.8.0 iview-are
a@1.5.14 js-cookie@2.2.0 rasterizehtml@1.2.4 simplemde@1.11.2 sortablejs@1.7.0 tinymce@4.7.3 vue@2.5.13 vue-router@3.0.1 vuex@3.0.1 autoprefixer-loader@3.2.0 babel@6.23
.0 babel-core@6.23.1 babel-eslint@8.0.3 babel-loader@7.1.2 babel-plugin-transform-runtime@6.12.0 babel-preset-env@1.6.1 babel-preset-es2015@6.9.0 babel-preset-stage-3@6
.24.1 babel-runtime@6.11.6 clean-webpack-plugin@0.1.17 copy-webpack-plugin@4.2.3 css-hot-loader@1.3.4 css-loader@0.28.7 eslint@4.12.1 eslint-config-google@0.9.1 eslint-
config-standard@10.2.1 eslint-plugin-html@4.0.1 eslint-plugin-import@2.8.0 eslint-plugin-node@5.2.1 eslint-plugin-promise@3.6.0 eslint-plugin-standard@3.0.1 extract-tex
t-webpack-plugin@3.0.2 file-loader@1.1.5 happypack@4.0.0 html-loader@0.5.1 html-webpack-plugin@2.28.0 less@2.7.3 less-loader@4.0.5 semver@5.4.1 style-loader@0.19.0 unsu
pported@1.1.0 url-loader@0.6.2 vue-hot-reload-api@2.2.4 vue-html-loader@1.2.3 vue-i18n@5.0.3 vue-loader@13.5.0 vue-style-loader@3.0.3 vue-template-compiler@2.5.13 webpa
ck@3.10.0 webpack-dev-server@2.9.5 webpack-merge@4.1.1 webpack-uglify-parallel@0.1.4`

5.还原package.json
6.npm run dev
7.Done.

后面也没再分析根本是什么问题了，有谁知道吗？
