### ISSUE TITLE
求编辑器内容样式与全局样式冲突造成渲染混乱的解决办法

### ISSUE THREAD

**Issue by smartymoon** [iview/iview-admin#364]
在使用 `iview-admin` 的编辑器时发现了这个很麻烦的问题。由编辑器编辑出来的文本样式会受到其他全局样式的影响，比如：在富文本中，`li` 表示有圆点的列表，但是在 `iview-admin` 的框架下，这个圆点会消失。尝试借力 normalize.css ,不能解决。使用 iframe 的话成本太高，而且 low 。在尝试搜索引擎后依然没有发现好的办法。各位同仁们，有好的建议么？

**Comment by lison16** [comment]
这个没有遇到，遇到的同学可以在这里说下解决办法

**Comment by html5manong** [comment]
我想问一下   我是用view做项目，但是用到了ivew admin里面的富文本组件，怎么引入该组件
