### ISSUE TITLE
请教一下各位大神，未登陆重定向到登陆界面是在哪里判断到啊，没找到

### ISSUE THREAD

**Issue by gitors** [iview/iview-admin#366]
各位大神，小弟做服务端到，前端不是很熟，iview-admin 没有登陆就重定向到 login 界面到代码是在哪里啊？我找了半天没有找到，哪位大神指点下

**Comment by tanshaoxiaoji** [comment]
没人回答吗？据我了解，一般登录判断不是应该在后台拦截器校验再重定向的吗？

**Comment by gitors** [comment]
@tanshaoxiaoji  我自己已经找到了，在 路由那里， router/index.js 里面，
```router.beforeEach```  代码块里面，自己加就可以了，iview-admin 是这样的，我不过我全拿过来会报错，在后面遍历的时候就有问题了，我只是加了登陆的拦截。

**Comment by tanshaoxiaoji** [comment]
我是菜鸟，在我的经验里登录验证都是后台处理的。现在到我请教你了，请问你这个项目是一个什么项目，为什么登录校验是前端校验的？这样做安全吗？

**Comment by tanshaoxiaoji** [comment]
我是比较好奇，我邮箱是464037833@qq.com，可以私聊一下吗？

**Comment by gitors** [comment]
@tanshaoxiaoji  最终的登陆验证肯定是要在数据库验证的啊，前端只是控制跳转到什么界面而已。我也是做服务端的，前端的不太懂，不过现在前端都是工程化了，你说的后台校验再重定向那是以前的做法，现在都是restful 接口，前端在登陆后会存一个登陆状态在cookis 中，然后前端都是在cookie 里面判断是否已经登陆的，如果cookie 被清空或者已经过期，就会判定为未登陆，访问就会被重定向到login 页面。
我是这么理解到

**Comment by gitors** [comment]
@tanshaoxiaoji  我也是一个菜鸟，现在用都还不会用，还在琢磨中

**Comment by tanshaoxiaoji** [comment]
谢谢，解释的很详细
