### ISSUE TITLE
可编辑表格数据问题

### ISSUE THREAD

**Issue by zhangyundoc** [iview/iview-admin#37]
不支持异步获取表格的数据

**Comment by lison16** [comment]
您好，您是想反馈bug还是需求？

**Comment by zhangyundoc** [comment]
bug。

data () {
        return {
            columns: [],
            thisTableData: this.tableData,  // 异步的数据，set后取不到
            edittingStore: []
        };
    },
异步获取数据set后，页面未更新，复现可以在demo中Timeout一下

**Comment by lison16** [comment]
现已修复，感谢您的支持
