### ISSUE TITLE
npm run build 的 index.html 有问题。

### ISSUE THREAD

**Issue by xiaopanghhh** [iview/iview-admin#381]
用npm run build .导出来在 disk 目录下面的 index.html 和 index.ejs 是一样的。原因是在 
webpack.base.config.js 当中，把 |ejs 去掉就好了。让 .ejs 不要走 html-loader
把
{
    test: /\.(html|tpl|ejs)$/,
    loader: 'html-loader'
}
修改为
{
    test: /\.(html|tpl)$/,
    loader: 'html-loader'
}

**Comment by NaClyxp** [comment]
正解   感谢老铁

**Comment by terranc** [comment]
遇到同样问题

**Comment by lison16** [comment]
现已修复
