### ISSUE TITLE
Bug 未收缩菜单情况下，某一菜单组中只有一个子菜单满足权限时，菜单显示错误

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview-admin#383]
此处团队菜单存在2个子菜单，此时只有一个子菜单可以显示（权限通过），面包屑却正常，但菜单显示错误
![default](https://user-images.githubusercontent.com/30425581/34483745-73d96e92-effb-11e7-9f67-78f907195cf5.png)
![default](https://user-images.githubusercontent.com/30425581/34483658-e76626a8-effa-11e7-9a28-96818c918557.png)

此外，收缩菜单时，菜单标题正常
同理需要检查所有情况下图标的正确性
![default](https://user-images.githubusercontent.com/30425581/34483759-8a93eb8a-effb-11e7-9f4e-eecc4d661912.png)

红色框的代码是经过调整后的
![default](https://user-images.githubusercontent.com/30425581/34659190-f026627e-f470-11e7-9dd3-8bba22b508df.png)

**Comment by lison16** [comment]
现已修复，谢谢
