### ISSUE TITLE
Bug 动态路由菜单控制错误的问题

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview-admin#384]
如下代码，当此菜单组下2个子菜单需要分别控制权限时，菜单组不可能设置access属性，
但是忽略设置access后，如果一个子菜单的权限都没有，系统控制台会出现异常，这是由于有父组件（main），但是没有定义当前待显示的组件
![default](https://user-images.githubusercontent.com/30425581/34483896-47903a36-effc-11e7-8ff1-f6902941e3b8.png)

解决如下store下app.js updateMenulist方法
![default](https://user-images.githubusercontent.com/30425581/34484205-379e8112-effe-11e7-930d-c8525197e9a1.png)

**Comment by lison16** [comment]
已修复，感谢~
