### ISSUE TITLE
建议 多语言引用不使用src目录，使用dist目录，这可以防止babel兼容错误

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview-admin#385]
多语言引用不使用src目录，使用dist目录，这可以防止babel兼容错误
![default](https://user-images.githubusercontent.com/30425581/34484081-622232a4-effd-11e7-8d12-c386133a2516.png)

**Comment by lison16** [comment]
你开发过程中遇到报错了吗

**Comment by gitzhangfugui** [comment]
@lison16 有 主要是ie兼容 使用babel后，这部分代码也没有从es6转es5 ie显示语法错误，但是dist目录就可以

**Comment by lison16** [comment]
好的，后面优化一下
