### ISSUE TITLE
建议 菜单权限进行判断重构，不使用cookie的方式，直接把个人权限通过vuex进行管理

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview-admin#386]
因为一个系统不会只动态控制一个菜单，现在access只能在cookie中设置一个，但是实际一个人所拥有的菜单权限都会以一个组的方式进行设置，如menus： [0, 1, 2...]
建议不使用cookie的方式，直接把个人权限通过vuex进行管理

**Comment by lison16** [comment]
使用cookie只是为了做示例，这个不是重点，自己结合自己的项目自行对这部分改造
