### ISSUE TITLE
左侧菜单的子页面

### ISSUE THREAD

**Issue by chenweigit** [iview/iview-admin#387]
# 面包屑显示问题
> 问题是左侧子菜单有一个列表，列表中有详情操作按钮，当点击详情后跳转到详情页面，同事面包屑也需要更新。首页 >员工管理 > 列表 > 详情。目前是把详情写在Main 的子组件

**Comment by chenweigit** [comment]
问题已经解决，在 原有的 util.js 做跳转

**Comment by ma6566966** [comment]
请问怎么改的
