### ISSUE TITLE
如何重载已打开过的页面/页签?

### ISSUE THREAD

**Issue by terranc** [iview/iview-admin#393]
场景：
在列表（`name: 'xxx-list'`）中点击一条记录进入编辑页面，编辑提交成功后`this.$router.push({ name: 'xxx-list' })`，这是仅仅是切换到之前打开的列表页，并且因为 keep-alive 缘故，并不会去刷新列表，特来找作者赐教一些黑科技。

如若是用 store 就不必了，太多页面间的跳转，这种列表数据也不适合都放 store 里去。

**Comment by gaocz** [comment]
activated()

**Comment by terranc** [comment]
了解，但延伸了另一个 issue 出来，麻烦看看。 #413
