### ISSUE TITLE
npm run build失败

### ISSUE THREAD

**Issue by yiwukun** [iview/iview-admin#399]
Hello,

我每次执行npm run build就会在“91% additional asset processing ”的地方卡死， 能否帮忙查查什么原因呢？

如下是日志：

$ npm run build

> iview-admin@1.2.2 build C:\phpStudy\WWW\iview-admin
> webpack --progress --hide-modules --config build/webpack.prod.config.js

clean-webpack-plugin: C:\phpStudy\WWW\iview-admin\dist\* has been removed.
Happy[happybabel]: Version: 4.0.0. Threads: 4 (shared pool)
(node:21296) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Happy[happybabel]: All set; signaling webpack to proceed.
 19% building modules 82/99 modules 17 active ...ode_modules\querystring-es3\encode.jsContainer#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Node#style() is deprecated. Use Node#raw()
Container#remove is deprecated. Use Container#removeChild
Node#_value was deprecated. Use Node#raws.value                                                            91% additional asset processing

**Comment by lison16** [comment]
在关闭的解决的issue中有解决办法请自己找一下
