### ISSUE TITLE
build 报错

### ISSUE THREAD

**Issue by ScorpioRen** [iview/iview-admin#400]
ERROR in js/11.61779b4e8bcbe1fb5182.chunk.js from UglifyJs
Unexpected token name «i», expected punc «;»  
在 base.config.js 里面添加如下解决:
{
   test: /iview.src.*?js$/,
   loader: 'babel-loader'
}
是不是源代码忘记写了?? 我这么写有必要吗?有没有其他的方法

**Comment by lison16** [comment]
对于打包问题今天会排查所有问题
