### ISSUE TITLE
项目无法构建

### ISSUE THREAD

**Issue by Kavonne** [iview/iview-admin#405]
以下版本都试了，均可通过npm/cnpm install，但无法通过npm run dev。 
Node8.9.4(npm5.6.0)
Node7.10.1(npm4.2.0)
Node6.12.3(npm3.10.10)

报错（npm run dev）：
Missing argument values: config-name, context, entry, module-bind, module-bind-p
ost, module-bind-pre, output-path, output-filename, output-chunk-filename, outpu
t-source-map-filename, output-public-path, output-jsonp-function, output-library
, output-library-target, records-input-path, records-output-path, records-path,
define, target, watch-aggregate-timeout, devtool, resolve-alias, resolve-extensi
ons, resolve-loader-alias, optimize-max-chunks, optimize-min-chunk-size, prefetc
h, provide, plugin, open-page

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! iview-admin@1.3.0 dev: `webpack-dev-server --content-base ./ --open --i
nline --hot --compress --config build/webpack.dev.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iview-admin@1.3.0 dev script 'webpack-dev-server --conten
t-base ./ --open --inline --hot --compress --config build/webpack.dev.config.js'
.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the iview-admin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --content-base ./ --open --inline --hot --compre
ss --config build/webpack.dev.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs iview-admin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls iview-admin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Kavonne\Git\iview-admin\npm-debug.log

日志（npm-debug.log）：
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'owner',
1 verbose cli   'ls',
1 verbose cli   'iview-admin' ]
2 info using npm@3.10.10
3 info using node@v6.12.3
4 silly mapToRegistry name iview-admin
5 silly mapToRegistry using default registry
6 silly mapToRegistry registry https://registry.npmjs.org/
7 silly mapToRegistry data Result {
7 silly mapToRegistry   raw: 'iview-admin',
7 silly mapToRegistry   scope: null,
7 silly mapToRegistry   escapedName: 'iview-admin',
7 silly mapToRegistry   name: 'iview-admin',
7 silly mapToRegistry   rawSpec: '',
7 silly mapToRegistry   spec: 'latest',
7 silly mapToRegistry   type: 'tag' }
8 silly mapToRegistry uri https://registry.npmjs.org/iview-admin
9 verbose request uri https://registry.npmjs.org/iview-admin
10 verbose request no auth needed
11 info attempt registry request try #1 at 09:54:11
12 verbose request id 76346731adb8dfaf
13 http request GET https://registry.npmjs.org/iview-admin
14 http 404 https://registry.npmjs.org/iview-admin
15 verbose headers { 'content-type': 'application/json',
15 verbose headers   'cache-control': 'max-age=0',
15 verbose headers   'content-length': '2',
15 verbose headers   'accept-ranges': 'bytes',
15 verbose headers   date: 'Wed, 10 Jan 2018 01:54:09 GMT',
15 verbose headers   via: '1.1 varnish',
15 verbose headers   connection: 'keep-alive',
15 verbose headers   'x-served-by': 'cache-hnd18740-HND',
15 verbose headers   'x-cache': 'MISS',
15 verbose headers   'x-cache-hits': '0',
15 verbose headers   'x-timer': 'S1515549248.213163,VS0,VE1436',
15 verbose headers   vary: 'Accept-Encoding' }
16 silly get cb [ 404,
16 silly get   { 'content-type': 'application/json',
16 silly get     'cache-control': 'max-age=0',
16 silly get     'content-length': '2',
16 silly get     'accept-ranges': 'bytes',
16 silly get     date: 'Wed, 10 Jan 2018 01:54:09 GMT',
16 silly get     via: '1.1 varnish',
16 silly get     connection: 'keep-alive',
16 silly get     'x-served-by': 'cache-hnd18740-HND',
16 silly get     'x-cache': 'MISS',
16 silly get     'x-cache-hits': '0',
16 silly get     'x-timer': 'S1515549248.213163,VS0,VE1436',
16 silly get     vary: 'Accept-Encoding' } ]
17 error owner ls Couldn't get owner data iview-admin
18 verbose stack Error: Registry returned 404 for GET on https://registry.npmjs.org/iview-admin
18 verbose stack     at makeError (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:302:12)
18 verbose stack     at CachingRegistryClient.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:280:14)
18 verbose stack     at Request._callback (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-registry-client\lib\request.js:210:14)
18 verbose stack     at Request.self.callback (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:187:22)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at Request.emit (events.js:191:7)
18 verbose stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1048:10)
18 verbose stack     at emitOne (events.js:96:13)
18 verbose stack     at Request.emit (events.js:188:7)
18 verbose stack     at IncomingMessage.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:969:12)
19 verbose statusCode 404
20 verbose pkgid iview-admin
21 verbose cwd D:\Kavonne\Git\iview-admin
22 error Windows_NT 6.1.7601
23 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "owner" "ls" "iview-admin"
24 error node v6.12.3
25 error npm  v3.10.10
26 error code E404
27 error 404 Registry returned 404 for GET on https://registry.npmjs.org/iview-admin
28 error 404
29 error 404 'iview-admin' is not in the npm registry.
30 error 404 You should bug the author to publish it (or use the name yourself!)
31 error 404 Note that you can also install from a
32 error 404 tarball, folder, http url, or git url.
33 verbose exit [ 1, true ]

**Comment by Kavonne** [comment]
顺带问一下iview-admin对npm的版本要求

**Comment by imfengzi** [comment]
webpack-dev-server  2.10.0的bug，npm update 把webpack-dev-server更新到2.10.1就可以了
