### ISSUE TITLE
TAB切换时如何禁止刷新

### ISSUE THREAD

**Issue by SparkZXP2018** [iview/iview-admin#407]
1. 点击用户列表管理，产生第一个TAB
2. 在用户列表中添加好查询条件，比如昵称查询，此时正常查询出结果
3. 在查出的用户中，点击一条查看详情，此时产生第2个TAB
4. 再次点击第1个TAB，此时用户列表自动刷新了，且未保留之前的查询条件

有什么办法在切换TAB的时候，不自动刷新？

**Comment by woshixiaoqianbi** [comment]
第二个跳转路由到的tab页面，应该有watch，你注释掉看看

**Comment by SparkZXP2018** [comment]
watch是用于监控VUE值的变化的，没想明白和TAB刷新有什么关系。是想让我用session或者cookie自己把查询条件缓存起来吗？

可是现在不止是查询条件，还有排序条件，分页条件；除了列表页，还有编辑页面，也有TAB切换后重新刷新的问题，这样要缓存的东西实在太多了，一个个保存不太现实。

**Comment by lison16** [comment]
iview-admin做了页面状态保持的
