### ISSUE TITLE
modal中使用upload，上传完成后文件名无法显示

### ISSUE THREAD

**Issue by woshixiaoqianbi** [iview/iview-admin#408]
文件名已经生成在html中了

**Comment by lison16** [comment]
不明白你的问题是什么导致的，但是我觉得你在控制台看一下然后运用自己的专业知识应该能解决

**Comment by woshixiaoqianbi** [comment]
![image](https://user-images.githubusercontent.com/18699589/34865126-7dbe3b9a-f7b2-11e7-9f4f-7aae98f5cf3f.png)
upload上传完成的名字继承了这个step的样式，建议加个fix
