### ISSUE TITLE
标签问题

### ISSUE THREAD

**Issue by zboMa** [iview/iview-admin#409]
在打开大量标签导致一些标签挤到左边后，关闭一些标签不会让左边隐藏的标签弹回。
![22](https://user-images.githubusercontent.com/26337768/34760321-57b5162e-f61a-11e7-96b0-e6c1de267fd6.png)

**Comment by SparkZXP2018** [comment]
有人提了类似的问题，你看下。[链接跳转](https://github.com/iview/iview-admin/issues/356)

**Comment by lison16** [comment]
@zboMa 最新的iview-admin已经修复了
