### ISSUE TITLE
换肤问题

### ISSUE THREAD

**Issue by LuxPax** [iview/iview-admin#412]
请问换肤是怎样实现的，
![image](https://user-images.githubusercontent.com/23111937/34807483-00045c6e-f6c4-11e7-97ae-e9b2d73798d9.png)
这里的三个less文件是在哪里引用的，实现思路是官网的变量覆盖方法吗
请指教，谢谢

**Comment by lison16** [comment]
请自己看源码

**Comment by LuxPax** [comment]
好的，提个建议：每个模块如果有对应的文档会比较好，对于经验少的开发者会比较友好，如果不考虑这些开发者请忽略

**Comment by lison16** [comment]
文档确实有必要，但是最近在做项目时间不够

**Comment by LuxPax** [comment]
能开源这个项目就已经很感谢你了，只不过是自身能力欠缺
