### ISSUE TITLE
换肤功能中,loading出现错误

### ISSUE THREAD

**Issue by h-wanli** [iview/iview-admin#415]
基础主题皮肤下,loading是正常的,但是换成其他几个皮肤效果后,loading图标会跑到页面顶部,经测试,问题在.ivu-spin-fix .ivu-spin-main{display:table-cell;vertical-align:middle;width:inherit;/*height:inherit*/}这条里面的height,注销掉就会正常。

**Comment by lison16** [comment]
https://github.com/iview/iview-admin/issues/347
