### ISSUE TITLE
当左侧导航栏向左收起时，Table组件右侧会出现“空白断裂”现象

### ISSUE THREAD

**Issue by cnyet** [iview/iview-admin#417]
当左侧导航栏向左收起时，也就是首页shrinkable-menu组件显示时，由于Table组件里面的table元素的width是动态计算的，没有及时更新，会出现“空白断裂”现象。左侧导航栏向右展开时会消失这种现象。所有的Table组件都存在这种现象。
``` 
<div class="ivu-table-header">
<table cellspacing="0" cellpadding="0" border="0" style="width: 443px;"></table>
</div> 
```

**Comment by lison16** [comment]
这个应该是iview组件table的问题，欢迎到iview的github主页提issue
