### ISSUE TITLE
render函数 渲染出来的Dropdown模块问题

### ISSUE THREAD

**Issue by chinesetian** [iview/iview-admin#419]
![456 zk jlpzlugdxe3s m](https://user-images.githubusercontent.com/29392154/34819446-bb427ef0-f6f8-11e7-8f12-1197d49d0659.png)
![6y1k vn e lzd9simxrfn5r](https://user-images.githubusercontent.com/29392154/34819450-bc6a39a8-f6f8-11e7-974c-42a3f345b4b0.png)

**Comment by lison16** [comment]
你先仔细看下vue文档slot这个属性该写在什么位置，如果还有问题再提问

**Comment by chinesetian** [comment]
找到了，render的data对象有用例，感谢，感谢
