### ISSUE TITLE
开始做登录的login.vue,引入 this.$Message.info会报Cannot read property '$Message' of undefined错误

### ISSUE THREAD

**Issue by lyseky** [iview/iview-admin#421]
$Message不是在main.js全局添加了吗，为什么还会报错，求解，部分代码如下

axios.post(userUrl, data)
                        .then(function (res) {
                            console.log(res.data);
                            const data = res.data;
                            if (data.code === '200') {
                                if (name === 'admin') {
                                    Cookies.set('user', name);
                                    Cookies.set('access', 0);
                                    Cookies.set('token', data.data.token);
                                    this.$Message.info(data.msg)
                                } else {
                                    Cookies.set('access', 1);
                                }
                            }else {
                                console.log(data.msg)
                                this.$Message.info(data.msg)
                            }
                        })
                        .catch(function (error) {
                            console.log(error)
                        })

**Comment by lison16** [comment]
问下，你把this打印出来看过吗

**Comment by lyseky** [comment]
console.log(this)
console.log(this.$Message)
都可以打印出来，分别是
VueComponent
Message方法

**Comment by lison16** [comment]
你再哪儿打印的

**Comment by lyseky** [comment]
@lison16 
methods: {
        handleSubmit () {
            this.$refs.loginForm.validate((valid) => {
                if (valid) {
                    this.$store.commit('setAvator', 'https://ss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=3448484253,3685836170&fm=27&gp=0.jpg');
                    /*if (this.form.userName === 'admin') {
                        Cookies.set('access', 0);
                    } else {
                        Cookies.set('access', 1);
                    }
                    this.$router.push({
                        name: 'home_index'
                    });*/
                    console.log(this)
                    console.log(this.$Message)
                    console.log(this.$Message.info)
                    const name = this.form.userName;
                    const password = this.form.password;
                    const data = Qs.stringify({
                        name: name,
                        password: password,
                    });
                    axios.post(userUrl, data)
                        .then(function (res) {
                            console.log(res.data);
                            const data = res.data;
                            if (data.code === '200') {
                                if (name === 'admin') {
                                    Cookies.set('user', name);
                                    Cookies.set('access', 0);
                                    Cookies.set('token', data.data.token);
                                } else {
                                    Cookies.set('access', 1);
                                }
                            }else {
                                console.log(data.msg)
                                // alert(data.msg)
                                this.$Message.info('123')
                            }
                        })
                        .catch(function (error) {
                            console.log(error)
                        })
                }
            });
        }
    }

**Comment by lison16** [comment]
我觉得你该了解下js里关于this的知识

**Comment by lyseky** [comment]
@lison16 我错了，没看到在this.$refs.loginForm里，搞定
