### ISSUE TITLE
打正式包 报错 

### ISSUE THREAD

**Issue by hardphp** [iview/iview-admin#427]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iview-admin@1.3.1 build: `webpack --progress --hide-modules --config build/webpack.prod.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the iview-admin@1.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2018-01-15T0
9_28_58_078Z-debug.log

**Comment by lison16** [comment]
刚刚试了下成功打包，如果你还是打包出错请自行搜索下解决办法

**Comment by 544751779** [comment]
我也遇到这个问题了 @lison16

**Comment by gavincilp** [comment]
遇到了同样的问题，之前还没有

**Comment by gavincilp** [comment]
1.3.1， 之前没有，怀疑是加了有es6语法的module

**Comment by gavincilp** [comment]
ERROR in 0.75433b59fec893c68a7b.chunk.js from UglifyJs
Unexpected token: name (e) [0.75433b59fec893c68a7b.chunk.js:28625,8]
Child html-webpack-plugin for "..\index.html":
     1 asset
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js?minimize!node_modules/autoprefixer-loader/index.js!node_modules/iview/dist/styles/iview.css:
                                    Asset     Size  Chunks                    Chunk Names
     2c2ae068be3b089e0a5b59abb1831550.eot   121 kB          [emitted]
     24712f6c47821394fba7942fbb52c3b2.ttf   189 kB          [emitted]
    05acfdb568b3df49ad31355b19495d4a.woff  67.9 kB          [emitted]
     621bd386841f74e0053cb8e67f8a0604.svg   334 kB          [emitted]  [big]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! iview-admin@1.3.1 build: `webpack --progress --hide-modules --config build/webpack.prod.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the iview-admin@1.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2018-07-27T08_53_06_709Z-debug.log
