### ISSUE TITLE
为什么localhost可以访问，输入本地IP不行啊

### ISSUE THREAD

**Issue by picnic-yu** [iview/iview-admin#429]
为什么localhost可以访问，输入本地IP不行啊

**Comment by lison16** [comment]
<img width="617" alt="screen shot 2018-01-16 at 12 37 49 pm" src="https://user-images.githubusercontent.com/20942571/34972142-82ef586e-faba-11e7-8171-9575c89bad94.png">
检查下你是不是开了其他服务器
