### ISSUE TITLE
请教一下作者和大家，如何设置在切换tab页的时候，tab页内内容不刷新

### ISSUE THREAD

**Issue by LSmile1994** [iview/iview-admin#445]
如题，现在用到了iview-admin，遇到了如下问题。

1、如何设置才能tab页切换时刷新页面内的内容呢？

2、iview中的table表格能不能支持，用鼠标拖动调整列宽。

**Comment by lison16** [comment]
现在的iview-admin默认就是打开的tab页内容不刷新，用了keep-alive组件；
iview表格目前不支持拖动调整列宽

**Comment by wangpeng1478** [comment]
我也遇到了 这个问题 请问你解决了吗

**Comment by lison16** [comment]
1.x版本中，在store/modules/app.js中，state.dontCache是用来控制哪些页面不缓存，即切换到其他标签再切换回来，内容刷新。
2.x版本中，每个页面是否缓存是在路由里配置的
