### ISSUE TITLE
win7下iview-admin 1.2.3执行npm run build卡在了 91% additional asset processing

### ISSUE THREAD

**Issue by lengkuwolf** [iview/iview-admin#449]
win7下iview-admin 1.2.3执行npm run build卡在了
> iview-admin@1.2.3 build E:\Node\iview-webpc
> webpack --progress --hide-modules --config build/webpack.prod.config.js

clean-webpack-plugin: E:\Node\iview-webpc\dist\* has been removed.
Happy[happybabel]: Version: 4.0.0. Threads: 4 (shared pool)
Happy[happybabel]: All set; signaling webpack to proceed.
 91% additional asset processing

**Comment by lison16** [comment]
这个问题早已经解决了，请自己看issue和升级日志
