### ISSUE TITLE
之前已经做了兼容IE 处理 升级了最近的两个版本后  IE11就报错了

### ISSUE THREAD

**Issue by oleorz** [iview/iview-admin#450]
错误1：“webpackJsonp”未定义
  self.postMessage({
      type: `webpack${type}`,  错误2：无效字符
      data
    }, '*');

**Comment by pliao** [comment]
更改webpack-dev-server版本为2.71
npm install --save-dev webpack-dev-server@2.7.1

**Comment by xiongcao** [comment]
@pliao 老哥真是6，这个问题搞了快两天了，头快炸了，本来想放弃了，还是想试一下你这个结果还真的可以了，感谢大神！
