### ISSUE TITLE
proxyTable在哪里配置啊

### ISSUE THREAD

**Issue by yangzichen987046** [iview/iview-admin#46]

**Comment by lison16** [comment]
您指的是什么？

**Comment by yangzichen987046** [comment]
![image](https://user-images.githubusercontent.com/18715050/31811297-a076ea62-b5b1-11e7-94ab-aa0ede770270.png)，在vue-cil里可以这样解决跨域

**Comment by davecat** [comment]
有文档以后，应该会详细说明各个文件的作用。这个项目结构跟vue-cli还不一样，希望下周一能看到viki

**Comment by yangzichen987046** [comment]
解决了：参考文档http://webpack.github.io/docs/webpack-dev-server.html
1.npm install http-proxy-middleware --save
2.在webpack.base.config下添加
```
devServer: {
        proxy: {
            '/api': {
                target: 'http://localhost:8088',
                pathRewrite: {'^/api' : ''},
                secure: false
            }
        }
    }
```
