### ISSUE TITLE
在表格组件中的表头使用renderHeader有个bug请问如何解决

### ISSUE THREAD

**Issue by liuqi07** [iview/iview-admin#473]
版本："version": "1.1.4",
问题描述：在表格的表头中，想加入Tooltip组件，如果Tooltip组件不使用slot插槽是正常显示的，但当要展示的内容过多的时候，根据文档使用slot就会产生问题，请问有什么方法可以解决吗，十分感谢。
代码部分：
1，如果要展示内容一行能展示开这么写就没有问题
`
{ title: '注册充值人数', key: 'RechageCount', align: 'center', renderHeader: (h, params) => {
    return h('Tooltip', {
        props: {
            content: '当天/周/月注册当天/周/月充值的人数',
            placement: 'top'
        }
    }, '注册充值人数')
} }
`

2，当要展示的内容过长时，这么写，有bug，悬浮提示层没有任何内容，而表头会把这两个标签的内容全部展示出来，是因为slot不能作为属性写在props里面吗？求正确写法
`
return h('Tooltip', {
    props: {
        placement: 'top'
    }
}, [
    h('span', '整体成交折标'),
    h('div', {
        props: {
            slot: 'content'
        },
        style: {
            widthSpace: 'normal'
        }
    }, '整体成交金额中，每笔投资金额*对应投资期限的折标系数后的加总')
])
`

**Comment by lison16** [comment]
我觉得你应该好好看看vue文档render函数的slot应该写在哪

**Comment by liuqi07** [comment]
额。。好吧，感谢，我再看一下
