### ISSUE TITLE
子栏目在进行权限切换时会不起作用，是否应该属于深拷贝？

### ISSUE THREAD

**Issue by sowork** [iview/iview-admin#479]
https://github.com/iview/iview-admin/blob/5b3de41bc10e2bb31a23e8ccf997e4fd7ae7a41f/src/store/modules/app.js#L60

**Comment by LouisGo** [comment]
遇到同样的问题，的确应该进行深拷贝

**Comment by lison16** [comment]
权限控制还会随着多级嵌套菜单重构
