### ISSUE TITLE
从table进入详情页，能否让详情页不显示在菜单列表中

### ISSUE THREAD

**Issue by NicholasMing** [iview/iview-admin#48]
比如：首页 / 会员管理/会员详情
这个路径，我不希望会员详情显示在左边的菜单栏中

![image](https://user-images.githubusercontent.com/20468003/31811996-2ae360ce-b547-11e7-8e19-16bf47bad3f5.png)

**Comment by lison16** [comment]
这样的话你把会员详情这个页面的路由写在otherRouter的children里即可，最新版的iview-admin里写了注释。
