### ISSUE TITLE
ie11下不兼容的问题

### ISSUE THREAD

**Issue by wwjhsh** [iview/iview-admin#480]
一次改太多了不确定是什么原因，我按照https://github.com/iview/iview-admin/commit/3166ca2949cbc2e97bd8f5e0f0cbd56ab85a7c6a?diff=split改了

**Comment by lison16** [comment]
你是说之前IE11没问题，按这个配置了iview-admin之后有问题了？

**Comment by wwjhsh** [comment]
不是，我之前不行，普通文件里es6语句都被转换成es5了，但是main.js里面转换不了，我那次改了我上条提的东西，和把webpack的main加上引号，后面这个我测了不是这个原因。

**Comment by lison16** [comment]
参考这个
https://github.com/iview/iview-admin/issues/14
https://github.com/iview/iview-admin/issues/343
