### ISSUE TITLE
在后续版本是否会增加父菜单高亮并展开？

### ISSUE THREAD

**Issue by gt0012** [iview/iview-admin#481]
目前菜单支持1级和2级，假设2级菜单的内容是一个列表页面，那么点击列表中的数据会动态跳转到详情页面，这个时候刷新的话，菜单会全部收起，因为他的父菜单不会高亮并展开，关于菜单这块，后续版本会改进吗？因为目前1 2级菜单不是很够用，菜单的实现方式目前也是单层循环查找的 而不是有一个方法专门递归去查找并高亮父级菜单，在router中children属性只支持1层children

**Comment by gt0012** [comment]
目前菜单都是根据name来匹配的

**Comment by lison16** [comment]
之前iview菜单不支持多级目录，所以没有做三级及更多级菜单展示 ，也没有处理多级路由逻辑，iview2.9.0版本实现了菜单多级嵌套，所以下个版本的iview admin会优化路由和菜单这块

**Comment by gt0012** [comment]
@lison16 会考虑像腾讯云控制台一样吗？因为目前看起来 云服务的菜单的管理方式是支持无限扩展

**Comment by lison16** [comment]
会支持多级嵌套，至于你说的腾讯云的，你可以自己实现
