### ISSUE TITLE
1.3.1版本跨域404错误，详细描述，求助

### ISSUE THREAD

**Issue by easyfast** [iview/iview-admin#482]
版本：1.3.1
package.json：
  "scripts": {
    "init": "webpack --progress --config build/webpack.dev.config.js",
    "dev": "webpack-dev-server --content-base ./ --open --inline --hot --compress --config build/webpack.dev.config.js",
    "build": "webpack --progress --hide-modules --config build/webpack.prod.config.js",
    "lint": "eslint --fix --ext .js,.vue src",
    "test": "npm run lint"
  },

/build/webpack.dev.config.js配置：
module.exports = merge(webpackBaseConfig, {
  devtool: '#source-map',
  output: {
    publicPath: '/dist/',
    filename: '[name].js',
    chunkFilename: '[name].chunk.js'
  },
  plugins: [
    new ExtractTextPlugin({
      filename: '[name].css',
      allChunks: true
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: ['vender-exten', 'vender-base'],
      minChunks: Infinity
    }),
    new HtmlWebpackPlugin({
      title: 'iView admin v' + package.version,
      filename: '../index.html',
      inject: false
    }),
    new CopyWebpackPlugin(
      [
        {
          from: 'src/views/main-components/theme-switch/theme'
        },
        {
          from: 'src/views/my-components/text-editor/tinymce'
        }
      ],
      {
        ignore: ['text-editor.vue']
      }
    )
  ],
  devServer: {
    port: '8866',
    historyApiFallback: true,
    hot: true,
    inline: true,
    stats: { colors: true },
    proxy: {
      '/api': {
        // 目标服务器地址
        target: 'http://localhost/',
        pathRewrite: { '^/api': '' },
        changeOrigin: true
      }
    }
  }
})

login页面代码：
import axios from 'axios';
export default {
    data () {
        return {
            form: {
                userNameOrEmailAddress: '',
                password: '',
                rememberClient: ''
            },
            rules: {
                userName: [
                    { required: true, message: '账号不能为空', trigger: 'blur' }
                ],
                password: [
                    { required: true, message: '密码不能为空', trigger: 'blur' }
                ]
            }
        };
    },
    methods: {
        handleSubmit () {
            this.$refs.loginForm.validate((valid) => {
                if (valid) {
                    if (this.form.rememberClient === '') {
                        this.form.rememberClient = false;
                    }
                    let formData = JSON.stringify(this.form);
                    let data = JSON.parse(formData);
                    axios
                        .post('/api/TokenAuth/Authenticate', data, {
                            headers: { 'Abp.TenantId': 1 }
                        })
                        .then(response => {
                            if (response.status === 200) {
                                this.$cookies.set('token', response.data.result.accessToken);
                                localStorage['a'] = response.data.result.accessToken;
                                this.$router.push('/index');
                            } else {
                                // 由后端抛出的错误
                            }
                        })
                        .catch(error => {
                            if (error) {
                                this.$Notice.error({
                                    title: '提醒',
                                    desc: '用户名密码错误'
                                });
                            }
                        });
                }
            });
        }
    }
};

返回结果：
Request URL:http://localhost:8080/api/TokenAuth/Authenticate
Request Method:POST
Status Code:404 Not Found
Remote Address:127.0.0.1:8080
Response Headers
view source
connection:close
content-length:0
date:Sun, 04 Feb 2018 11:33:15 GMT
server:Kestrel
x-powered-by:ASP.NET
x-sourcefiles:=?UTF-8?B?RDpcRWFzeUZhc3RcT0FcU2VydmVyXHNyY1xFYXN5RmFzdC5XZWIuSG9zdFxUb2tlbkF1dGhcQXV0aGVudGljYXRl?=
Request Headers
view source
Abp.TenantId:1
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8,en;q=0.6
Connection:keep-alive
Content-Length:80
Content-Type:application/json;charset=UTF-8
Cookie:C6Hd_2132_ulastactivity=acb2Zm%2FZsHUarU%2ByrvrIau6OSkqOcOGo18cRCiRCEiRN0%2FPMPiAj; C6Hd_2132_lastcheckfeed=1%7C1499867835; C6Hd_2132_nofavfid=1; Abp.Localization.CultureName=zh-CN; _ga=GA1.1.79506242.1490451813; UM_distinctid=15fc568e97e8d-0c679e1cd543d8-3e64430f-384000-15fc568e97f30c; CNZZDATA1253255703=1838435403-1490514417-%7C1510845507
Host:localhost:8080
Origin:http://localhost:8080
Referer:http://localhost:8080/
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Request Payload
view source
{userNameOrEmailAddress: "iview_admin", password: "123", rememberClient: false}
password
:
"123"
rememberClient
:
false
userNameOrEmailAddress
:
"iview_admin"

求助，具体哪里错了，反复尝试多次，始终404。 其中反复尝试加“/”与减“/”，始终不对

**Comment by lison16** [comment]
跨域问题请自行在issue里查找
