### ISSUE TITLE
关于 route 的 access 的代码逻辑bug

### ISSUE THREAD

**Issue by liu1023953303** [iview/iview-admin#485]
>  1.获取 access 权限
<pre>
// 在函数 updateMenulist 中，通过了 parseInt 来获取 权限，并强制转换为 Number 类型
let accessCode = parseInt(Cookies.get('access'));
</pre>

> 2. 根据 access 实施权限
<pre>
// 在函数 util.showThisRoute  中，通过了 access 来 控制菜单的显示以及访问权限
util.showThisRoute = function (itAccess, currentAccess) {
    if (typeof itAccess === 'object' && Array.isArray(itAccess)) {
        return util.oneOf(currentAccess, itAccess);
    } else {
        return itAccess === currentAccess;
    }
};
// 很显然，access 最初的设计就是通过一个数组或数字形式来控制，Route 访问权限。
// 但是这里的 currentAccess 已经被强制转换成 Number 应该是一个 bug 
</pre>

**Comment by lison16** [comment]
你没有看懂这的逻辑，let accessCode = parseInt(Cookies.get('access'));  这是当前登录用户的权限值
