### ISSUE TITLE
npm run build 报严重bug

### ISSUE THREAD

**Issue by BiYuqi** [iview/iview-admin#489]
[](http://oiukswkar.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180208182939.png)

npm run build index.html 页面链接全部失败

**Comment by BiYuqi** [comment]
http://oiukswkar.bkt.clouddn.com/%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_20180208182939.png

**Comment by Miku-Zeng** [comment]
我也是 请问你解决了吗

**Comment by Lance-Layne** [comment]
没有，不能  git clone
在2018年3月26日 10:30，Zeng<notifications@github.com> 写道：

我也是 请问你解决了吗
