### ISSUE TITLE
npm run build 之后发布到iis出现ttf，woff文件路径错误导致找不到

### ISSUE THREAD

**Issue by vikholdon** [iview/iview-admin#49]
更改webpack.prod.config.js的output.publicPath为'/dist/'，之后网站正常运行，就是字体出现/dist/dist的路径，导致访问不了

**Comment by lison16** [comment]
要改为' 服务器域名/dist/' 的格式，然后放到服务器

**Comment by zhouboluo** [comment]
一样，其它文件路径都是正确的，只有字体文件出现了/dist/dist两层目录
