### ISSUE TITLE
多级菜单权限问题

### ISSUE THREAD

**Issue by JonChanGit** [iview/iview-admin#505]
如图所示：
![image](https://user-images.githubusercontent.com/20020550/36656731-9c62dfa4-1b04-11e8-8a71-713ddfb2f9e3.png)
1及和二级菜单都配置权限值时，
![image](https://user-images.githubusercontent.com/20020550/36656671-68f62252-1b04-11e8-8aa2-ee744a34bd31.png)
在登陆代码如下：
![image](https://user-images.githubusercontent.com/20020550/36656828-fc0fe51e-1b04-11e8-85bb-6efde289933d.png)

会爆权限不足
![image](https://user-images.githubusercontent.com/20020550/36656816-eb55f34e-1b04-11e8-9747-773d6ae8965a.png)

**Comment by HazyLiA** [comment]
#410 
应该有帮助

**Comment by HazyLiA** [comment]
iview-admin/src/router/index.js  源码41行，在多权限状态下，权限对象的属性是Object，和Int对象的判断永远是false啊
把access: [1, 2, .....]对象里的数据遍历一遍咯

**Comment by Huangshunq** [comment]
我使用的版本是v1.2.3，也遇到了相似的问题：

![1519973844 1](https://user-images.githubusercontent.com/25452858/36887009-11e18406-1e2a-11e8-85e4-243e39507c99.png)

我在所有页面都配置了多个权限，权限的判断不符合预期。

然后我在router/index.js 第41行修改，改用现有的函数判断数组或数字，使得在不触发`Util.toDefaultPage` 替换路由名的条件下避开403页面：

![1519974493 1](https://user-images.githubusercontent.com/25452858/36887372-de27cdbc-1e2b-11e8-884f-46ff2db94266.png)

在store/modules/app.js 第53行作相同修改，为了正常显示菜单：

![1519974311 1](https://user-images.githubusercontent.com/25452858/36887364-d2856488-1e2b-11e8-9064-2b06f0b423c9.png)

希望能得到更完善或官方的权限使用做法。

**Comment by JonChanGit** [comment]
已经把权限全部改掉了

**Comment by smokeman** [comment]
util.showThisRoute中的
if (typeof itAccess === 'object' && Array.isArray(itAccess)) {
应改为if (typeof itAccess === 'object' || Array.isArray(itAccess)) {
此处BUG很有意思！哈哈

**Comment by Everan-1994** [comment]
大家可别听楼上说的，我照着他的改了结果是错误的。原版 ‘&&’ 才是对的。
