### ISSUE TITLE
[Bug Report]ie浏览器打不开

### ISSUE THREAD

**Issue by h-wanli** [iview/iview-admin#509]
### Environment
win 10操作系统,ie 11浏览器

### Reproduction link
[https://iview.github.io/iview-admin/](https://iview.github.io/iview-admin/)

### Steps to reproduce
在ie浏览器中打开iview admin

### What is expected?
希望可以兼容ie 9  10  11。

### What is actually happening?
ie中不能打开。

---
使用iview admin做的开发   开发了好多发现ie浏览器不能使用。很绝望有没有。

**Comment by h-wanli** [comment]
想知道iview admin是否会考虑兼容ie 9  10  11，如果会支持ie的话，就用iview admin继续开发,如果没有兼容ie的考虑,只能及早改UI框架,客户需要兼容ie。希望能给出一个答复,谢谢。

**Comment by lison16** [comment]
不会兼容，如果你有这个需求，自己可以加polyfill

**Comment by xiongcao** [comment]
@h-wanli 您好，请问这个兼容问题您解决没有

**Comment by xiongcao** [comment]
这个可以[](https://github.com/iview/iview-admin/issues/450)

**Comment by xiongcao** [comment]
[这个可以解决](https://github.com/iview/iview-admin/issues/450)
