### ISSUE TITLE
关于富文本框插件JS异常的问题 

### ISSUE THREAD

**Issue by Gzoye** [iview/iview-admin#51]
git iview-admin包本地起的服务可以正常使用富文本框插件

但是自己用vue脚手架新建一个项目后 利用npm下了同版本的tinymce包
复制avatorEditer.vue到新项目 启动页面的时候直接报错 
![qq 20171020165918](https://user-images.githubusercontent.com/16913605/31813194-193aaa14-b5b8-11e7-81c3-a0cb8dfe3732.png)

然后看了下webpack的配置 也暂未发现问题所在
求大神指点   么么哒

**Comment by jiangshunxin** [comment]
你解决了吗

**Comment by lison16** [comment]
把tinymce的主题包放进去了吗

**Comment by jiangshunxin** [comment]
这个是不是可以指定base路径的？

**Comment by lison16** [comment]
是的，可以参考下tinymce文档

**Comment by jiangshunxin** [comment]
需不需要webpack.config配置一下呢？

**Comment by lison16** [comment]
在tinymce的初始化配置里
