### ISSUE TITLE
多标签不能保存当前页面状态

### ISSUE THREAD

**Issue by doocal** [iview/iview-admin#511]
多标签切换页面是不错的，但是不能保存页面状态，每次点击是重新加载。这样多标签的意义就不大了。

**Comment by lison16** [comment]
需要给你的页面组件添加name属性

**Comment by doocal** [comment]
@lison16  我是指官方的例子应该体现，比如在编辑器里输入的内容，在来回切换的时候不丢失。

**Comment by lison16** [comment]
看工作流页面

**Comment by sotoup** [comment]
@lison16  是以下这个name属性吗  article-publish.vue 组件也有这个属性 但是来回切换  数据还是会丢失

`<script>
export default {
    name: 'workflow',
    data () { .. `

**Comment by lison16** [comment]
@sotoup 这的name要和路由里配置的name一致

**Comment by sotoup** [comment]
@lison16 非常感谢您的协助  好像name的值不能包含- (连字符)，文章编辑页面就是个特例，那么name 是
 artical-publish的时候页面状态不会保存  但是改成artical_publish后标题的数据在切换后会保留，页面编辑框的数据仍然会丢失

**Comment by tosslife** [comment]
@lison16 没懂您的意思，对比了下 工作流 和 文章发布 两个 name 值和 router 里的 name 值 都是一样的呀。可文章发布 就没法保存输入内容
