### ISSUE TITLE
请问如何正确使用iview-admin正确开发项目？

### ISSUE THREAD

**Issue by WindSpread** [iview/iview-admin#53]
您好，第一次使用。说明文档上说：‘不要在原项目上做修改’。那请问如何使用它来开发项目啦？我是新手，还望各位大佬指点迷津。。

**Comment by lison16** [comment]
您好，可能这样的描述给您造成误导了，意思是iview-admin不是库或者插件，它是一套实例demo，而且更新速度较快，如果您直接在原iview-admin上做修改，之后Iview-admin有升级可能会给您造成影响。所以建议您再clone一份进行自己的修改，

**Comment by WindSpread** [comment]
感谢大佬深夜解答！那我clone之后新建了一个项目，Iview-admin有更新，那我只能在把你们更新的部分在clone到我自己的项目里去？或者说Iview-admin就是让我们借鉴架构和里面的部分组件来开发新项目？抱歉，我开发经验还不足所以问的问题比较奇怪。我这里主要是不清楚当Iview-admin更新后如果去更新自己的项目。希望您能帮忙解答一下。O(∩_∩)O

**Comment by lison16** [comment]
其实iview-admin更多是希望给大家提供 美观的UI，丰富的功能，最佳的方案，所以个人建议了解了iview-admin的实现原理后自己去实现

**Comment by WindSpread** [comment]
原来如此！终于解开了心中的疑惑。最后真心感谢您能半夜还能给与回复，希望iview和iview-admin能做的越来越好，使用的人也越来越多。晚安。。。
