### ISSUE TITLE
建议标签栏在标签过多的情况下增加水平滚动条

### ISSUE THREAD

**Issue by one2threexm** [iview/iview-admin#54]
最近在密切关注iview-admin，打算近期投入到工作中使用
iview-admin风格我比较喜欢，但估计要需要进一步完善
今天发现标签栏更新了滚动功能和标签选项，感觉很不错，但如果再改善一下应该会更好
vscode的标签栏本人用起来感觉很爽，建议参考一下
对了，希望iview可以新增一种右键菜单的组件，因为在某些情况下，右键菜单确实是很方便的

**Comment by ranhuan** [comment]
打开新标签，老的标签全部缩回到左边里面去了，新的标签成为第一个，没法点回老标签，必须滚鼠标，这是bug吧？

**Comment by one2threexm** [comment]
现在的标签展示确实有点别扭

**Comment by ranhuan** [comment]
建议的方案：
打开标签时，如果该标签处于不可见区域，滚动标签栏，让该标签可见即可，尽量少滚动
点击一个标签，如果改标签的区域不是全部可视，滚动到该标签全部可见即可
然后左边当有隐藏按钮时，多一个往回箭头，点击，往左滚动到该标签完全可见，右边同理
关闭标签时选中标签坐标的标签，第一个dashboard失踪存在的

**Comment by lison16** [comment]
现已更新标签栏滚动方式，优化了体验，谢谢大家的建议，感谢大家的支持，希望共同进步

**Comment by ranhuan** [comment]
赞, 好勤快!
