### ISSUE TITLE
哎，好难受

### ISSUE THREAD

**Issue by SamoZ** [iview/iview-admin#541]
表示已经研究好几天了，我就想实现一个点击左侧菜单出现对应的tag标签，怎么那么难？
我不知道是不是我的基础太差了，总感觉这个项目的一个功能拆分的很不友好，
我照着源码一点一点的将有关联的代码拷贝到简化版的项目里，
但是死活出不来效果，真的很崩溃，哎

**Comment by djkloop** [comment]
Util.openNewPage(router.app, to.name, to.params, to.query);去看路由里面的这个方法。 @SamoZ
