### ISSUE TITLE
怎么在laravel里接入iviewadmin呀

### ISSUE THREAD

**Issue by 330132662** [iview/iview-admin#543]
如题，我们laravel的新项目 想用它做后台的前端页面，可是不知道怎么接入

**Comment by eugeneCN** [comment]
laravel接入vue??老铁你是这么想的？
首先你要搞清楚laravel和vue是做什么的。

**Comment by moxiaonai** [comment]
@330132662 前后端分离呗，后端只提供接口

**Comment by 330132662** [comment]
@moxiaonai   嗯，，那天我也明白如何操作了。。通过api交互数据 ，直接不用blade引擎了 ，有点刷新我这个伪全栈屌丝的视界
