### ISSUE TITLE
不认识<Layout>标签？

### ISSUE THREAD

**Issue by Var-iazioni** [iview/iview-admin#547]
从iview官网demo上复制过来布局的代码。。
表示认不出Layout标签。。大家有遇到这个问题么。。
F12提示：
[Vue warn]: Unknown custom element: <Layout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by lison16** [comment]
升级iview版本

**Comment by Var-iazioni** [comment]
搞定。。果然是iview版本的问题。。2.7.4就有layout了。。。
