### ISSUE TITLE
使用select组件时候开启multiple多选后,选择就会报错multiple

### ISSUE THREAD

**Issue by Ghjsw** [iview/iview-admin#567]
_this7.model.push is not a function

Error in event handler for "on-select-selected": "TypeError: _this7.model.push is not a function"

**Comment by Ghjsw** [comment]
数据下拉列表可以显示,就是点选就会报错:_this7.model.push is not a function

**Comment by Ghjsw** [comment]
这是我的数据:[{"value":"1","label":"测试超级管理update"},{"value":"7bfQIEV8IU4","label":"测试超级管理2"},{"value":"7bfQN1XV7bs","label":"test12"},{"value":"7bfQV61R1ma","label":"test1111"},{"value":"7bfQXN6ds6i","label":"test1333"},{"value":"7bfSCHMjh68","label":"add"},{"value":"7bfSL58pF56","label":"add1"},{"value":"7bfSTOOki00","label":"add11"},{"value":"7bfSYGLPWYy","label":"add1111"},{"value":"7bfTySQxeyG","label":"测试超级管理"},{"value":"7bfbVfy0IzI","label":"123"},{"value":"7bfbwaTsSzg","label":"12323"}]

**Comment by Ghjsw** [comment]
单选没问题,多选就报错

**Comment by Cloud-Dragon** [comment]
你好，问题解决了么？我遇到了同样的问题

**Comment by Ghjsw** [comment]
mounted 方法里不要写方法

**Comment by vincywindy** [comment]
我也遇到了这个问题，该怎么解决呢？

**Comment by yuanmingCD** [comment]
检查v-model绑定的数据是不是数组类型

**Comment by Mr0Sun** [comment]
我也遇到了这个问题，有解决方法吗

**Comment by vincywindy** [comment]
> 我也遇到了这个问题，有解决方法吗

最新版的iview已经解决了这个问题,奇怪的是这个issue一直不关

**Comment by Mr0Sun** [comment]
> > 我也遇到了这个问题，有解决方法吗
> 
> 最新版的iview已经解决了这个问题,奇怪的是这个issue一直不关
大佬，我们现在用的是老版本的，没法升新版本啊，之前版本有解决办法吗，急求

**Comment by vincywindy** [comment]
> > > 我也遇到了这个问题，有解决方法吗
> > 
> > 
> > 最新版的iview已经解决了这个问题,奇怪的是这个issue一直不关
> > 大佬，我们现在用的是老版本的，没法升新版本啊，之前版本有解决办法吗，急求

那就不知道了,我已经改用Angular了

**Comment by Ghjsw** [comment]
mounted
