### ISSUE TITLE
导航的手风琴效果不起作用

### ISSUE THREAD

**Issue by anLl** [iview/iview-admin#574]

**Comment by qutz** [comment]
更新到最新版的iview就可以

**Comment by anLl** [comment]
nice,更新到2.12.0确实解决了

**Comment by anLl** [comment]
package.json中改iview的版本号，然后在sidebarMenu.vue组件中的<Menu></Menu>加上accordion就行，但是还有点问题，点击标签手风琴还是不行，解决办法参考Pull question的方法
