### ISSUE TITLE
把login.vue、login.less的代码放自己项目为啥布局跟官方的不一样呢图片还显示不出来

### ISSUE THREAD

**Issue by songxing10000** [iview/iview-admin#582]
求解，弄了一下午，不知道为啥

**Comment by anLl** [comment]
1. 组件引入了吗？
2. 是不是用的render方法渲染的页面，不是的话<Form><FormItem>这种大写开头标签不能用
3. 没了~

**Comment by songxing10000** [comment]
登录界面都 没有其他组件，最后搞定了，把app.vue里的代码弄过去就好了
