### ISSUE TITLE
iViewAdmin开发时，localhost可以启动，本机ip就不行

### ISSUE THREAD

**Issue by anLl** [iview/iview-admin#584]
iViewAdmin开发时，localhost可以启动，本机ip就不行，又不想在package.json中用--host写死ip。

本来可以配置host 0.0.0.0 但是iviewAdmin在哪里配置呀

**Comment by anLl** [comment]
我知道了,配置一个devserver

**Comment by Li-Xin-xyz** [comment]
大佬，请教一下，如何配置的？

**Comment by anLl** [comment]
在webpack.dev.config中，添加一个devserver:{host:'0.0.0.0',port:8888,hot:true}就行，和output,devtool平级的

**Comment by Li-Xin-xyz** [comment]
如果是在云服务器上面部署的话，要怎么配置IP？已经调试好几天了，都不成功
