### ISSUE TITLE
选中tootip当中的文字,鼠标移出按钮再移入后tootip当中文字还是被选中了

### ISSUE THREAD

**Issue by ChasLui** [iview/iview-admin#59]
在图片预览编辑当中,选中tootip当中的文字,光标移出按钮再移入后tootip当中文字还是被选中了,体验不是很好, 期望是光标移出之后tootip文字选中状态也相应取消.

**Comment by lison16** [comment]
这个是iview组件的问题了，我会和Aresn说一下，谢谢反馈
