### ISSUE TITLE
当在首页标签时，鼠标移动到标签关闭下拉菜单无法选中，短暂闪烁。

### ISSUE THREAD

**Issue by maysoft** [iview/iview-admin#60]

**Comment by lison16** [comment]
在本地和在线测试都未出现这个现象，能详细说下如何复现吗

**Comment by maysoft** [comment]
不知道怎么弄动态图，用的360浏览器最新版（内核55）就有这个问题，edge没问题

**Comment by lison16** [comment]
找个了windows电脑装了360测试，确实存在这个问题，给dropdown加个transfer属性即可，现已更新，在线版本会在下个小版本更新
