### ISSUE TITLE
iview-admin 2.0版啥时候出来？

### ISSUE THREAD

**Issue by dingdingtop** [iview/iview-admin#626]
iview-admin 2.0版啥时候出来？

**Comment by wangbuhui** [comment]
同问。好期待2.0版本

**Comment by huangjianke** [comment]
同问。好期待2.0版本

**Comment by Thlq** [comment]
同问,非常期待

**Comment by hodgevk** [comment]
同问,异常期待

**Comment by zhengsonglin** [comment]
啥时候出来啊

**Comment by enuma0** [comment]
![image](https://user-images.githubusercontent.com/3970620/39953386-847b0fba-55dd-11e8-9e66-88fe703a8e12.png)
可能是5月底吧

**Comment by Dianwoung** [comment]
萌新决定还是直接等2.0版本吧

**Comment by aubdiy** [comment]
等 2.0  ，  期待中。。。 希望上 webpack 4.0
