### ISSUE TITLE
如何打JS打开新的标签页

### ISSUE THREAD

**Issue by FourLeafClover** [iview/iview-admin#646]
应用场景: 比如tab里面进行了订单查询, 然后点击订单编号可以跳转到订单详情页。是否支持打开多个订单详情页标签。

**Comment by vtoo** [comment]
同问，一个路由带参数可不可以 打开两个tags标签
比如 users/123   users/456

**Comment by weickdev** [comment]
为什么没有结论就close了？

**Comment by weickdev** [comment]
为什么没有结论就close了？你解决了吗？ @FourLeafClover
