### ISSUE TITLE
菜单栏主题颜色变更，在线demo上为可行，git down下来的出现下半部无法更变

### ISSUE THREAD

**Issue by aiyay** [iview/iview-admin#660]
1. 菜单栏主题颜色变更，在线demo上为可行，git down下来的出现下半部无法更变
2. 文件“iview-admin/src/views/main-components/shrinkable-menu/components/sidebarMenu.vue”
中第6行 “width="auto"z @on-select="changeMenu"” 多了个”z“

**Comment by Adummyprogrammer** [comment]
同问

**Comment by aiyay** [comment]
我是这么解决的：
在“iview-admin\src\views\Main.vue”文件中的第6行“ `<div class="sidebar-menu-con" :style="{width: shrink?'60px':'200px', overflow: shrink ? 'visible' : 'auto', background: menuTheme === 'dark'? '#495060' : '#ffffff' }">`”加了“**background: menuTheme === 'dark'? '#495060' : '#ffffff'**”
