### ISSUE TITLE
In english please ? 

### ISSUE THREAD

**Issue by Epistol** [iview/iview-admin#67]
Can you put the repo in english ? 

It's not possible to read without translating.

**Comment by xiaoxintiaoda** [comment]
0_0

**Comment by Epistol** [comment]
What ? Is it surprising ? You develop in english, so keep it in english for everyone to understand. 

That's something that every developer in the world know.

**Comment by lison16** [comment]
We considered the most of developers who use iview are Chines, so we writ Chinese introduction first. 
If you are willing to help us translate document, welcome and thank you, if you can not, please wait for us to write.

**Comment by xiaoxintiaoda** [comment]
这些老外简直了，不写中文还不乐意了，呵呵

**Comment by lantian1024** [comment]
Please believe that your wait is worth it !

**Comment by itpretty** [comment]
Read the codes directly then. Orz!

**Comment by lison16** [comment]
@Epistol we will put Eglish document soon

**Comment by rafailml** [comment]
Come on guys! This is great package, it should be translated.
