### ISSUE TITLE
看着挺好用起来蛮费劲的，期望考虑多角色用户菜单加载的情况

### ISSUE THREAD

**Issue by maoxinrong** [iview/iview-admin#694]
系统往往会会根据角色权限来加载菜单，一个 access判断不够，可能需要根据用户角色的不同权限来显示不同菜单，这点完全前端做不到吧？   得改很多代码！！  

一个框架最好能够不该写框架源码的情况下就能使用！ 否则改写了框架源码日后升级也是大问题

**Comment by lison16** [comment]
兄台你理解错了，这本来就不是一个框架，而是一个管理系统前端解决方案，它是一个基础，需要开发者自己根据需求做修改，做二次开发，而不是一点都不需要自己动手就能满足自己的所有需求。

**Comment by maoxinrong** [comment]
OK 谢谢！ 是我理解的懒了，明白了。
