### ISSUE TITLE
富文本全屏功能bug

### ISSUE THREAD

**Issue by ljybill** [iview/iview-admin#7]
在富文本页面点击全屏，会有bug，并且此时回到首页tab，页面无法滚动

**Comment by lison16** [comment]
富文本编辑器插件点击全屏是可以正常全屏，只不过因为iview的menu设置了z-index值，且高于富文本编辑器所在容器，所以编辑器被遮住了。这是个待解决的问题，谢谢提出

**Comment by Xiphin** [comment]
在富文本页面编辑内容时，切换tab到别的页面再切回富文本页面会出现编辑内容丢失及不可编辑的问题

**Comment by lison16** [comment]
升级到最新版iview-admin试试，最新版添加了本地存储演示，解决了编辑器不可编辑的bug

**Comment by lison16** [comment]
iview-admin去掉了tinymce的全屏功能，因为tinymce在single-page容器内，它的z-index的值是1，低于菜单栏和顶部导航栏，如果点击tinymce的全屏，需要将single-page的z-index调整到高于菜单栏和顶部导航栏。如果需要富文本编辑器全屏功能，可以自定义全屏按钮，然后在点击全屏后执行一个方法，设置single-page的z-index值。

**Comment by gx1727** [comment]
https://github.com/iview/iview-admin/issues/424
