### ISSUE TITLE
希望支持多级菜单

### ISSUE THREAD

**Issue by felixcoon** [iview/iview-admin#70]
iView的菜单只支持3级（submenu中套menugroup，然后再套menuitem），并且menugroup是不能被折叠的。在企业级应用中菜单会非常多，而且层级也会不止3级。

希望可以支持多级菜单（即submenu中可以再套submenu）

望考虑～

**Comment by lison16** [comment]
之前和Aresn沟通过，因为目前iview的menu菜单不支持更多级菜单，所以如果要用嵌套的菜单是可以实现多级菜单，只不过样式上会有bug，但是不影响使用，如果你业务上有需求，可以使用嵌套菜单
