### ISSUE TITLE
简化版使用table时报错

### ISSUE THREAD

**Issue by tinnkm** [iview/iview-admin#700]
![image](https://user-images.githubusercontent.com/13992692/41084086-b43ee522-6a65-11e8-925e-479532661acc.png)

**Comment by lison16** [comment]
这个是iview对vuei18n 6.x不兼容造成的，你可以看下2.0分支最新代码 src/locale/index.js

**Comment by tinnkm** [comment]
感谢提供思路，在国际化配置里加了如下代码就可以使用了
Vue.use(iview, {
  i18n: (key, value) => i18n.t(key, value)
})

**Comment by lison16** [comment]
采用了你的写法，赞

**Comment by XiaoFang9191** [comment]
@tinnkm 为什么我加上去之后还是报错呢
