### ISSUE TITLE
树形下拉框

### ISSUE THREAD

**Issue by aiyay** [iview/iview-admin#702]
后期是否能支持树形下拉框这样的模板控件

**Comment by lison16** [comment]
能给个截图看下什么样嘛

**Comment by aiyay** [comment]
我目前涉及到的是这两种：
1) 单选 （单选我用select组件与tree ，利用render 可以实现）
![tim 20180608152011](https://user-images.githubusercontent.com/27837058/41145028-5457ea92-6b31-11e8-80b3-6b8efac1e4a8.png)
2) 多选（多选目前还在研究）
![tim 20180608151921](https://user-images.githubusercontent.com/27837058/41145017-4e3dec2e-6b31-11e8-8813-4e65ff94991e.png)

**Comment by HejinYo** [comment]
大神，求实现的源码，看看思路，我是用树和selece组合实现，但没你这个好看，哈哈哈

**Comment by aiyay** [comment]
单选框的：
主要用到iview 中提供的 render来绑定 事件，实现虚拟DOM
![tim 20180616162519](https://user-images.githubusercontent.com/27837058/41497134-e68acbe0-7181-11e8-9b1c-fd63de7eaa83.png)
**methods** 中定义函数
![tim 20180616162626](https://user-images.githubusercontent.com/27837058/41497138-0b4f0ba8-7182-11e8-91fe-d1165bf0c561.png)
多选框的实现效果不是很理想 ，有两种。
一种和单选类似只是开启了select的多选，不过由于select的多选会导致select框随着值得变多变宽 影响美观
还有一种，也存在些问题：
![tim 20180616163346](https://user-images.githubusercontent.com/27837058/41497190-180833be-7183-11e8-885c-d8e1817de1be.png)
希望能帮到你。。

**Comment by gitors** [comment]
@HejinYo 哈哈，竟然看到你。我做菜单管理 选上级菜单的时候，也搞了一个。顺便问一下，树组件复选框多选的时候，怎么做到 不全选的时候 父节点也选到？
![image](https://user-images.githubusercontent.com/31715318/42194827-5f8f7bca-7ea8-11e8-9d56-88a6baf30439.png)
像这样，全选的时候，选中的节点是5个，但是去掉一个子节点以后，就是三个了，我想这个时候父节点也被选中。
我记得饿了么 里面 有一个属性加上就可以了，
![image](https://user-images.githubusercontent.com/31715318/42194952-14c12476-7ea9-11e8-886e-bdca07a30fb8.png)
不知道ivew 是否也有这样的属性。求大神，

**Comment by dengdengdengpan** [comment]
> 单选框的：
> 主要用到iview tree中提供的 render来绑定 事件，实现虚拟DOM
> ![tim 20180616162519](https://user-images.githubusercontent.com/27837058/41497134-e68acbe0-7181-11e8-9b1c-fd63de7eaa83.png)
> **methods** 中定义函数
> ![tim 20180616162626](https://user-images.githubusercontent.com/27837058/41497138-0b4f0ba8-7182-11e8-91fe-d1165bf0c561.png)
> 多选框的实现效果不是很理想 ，有两种。
> 一种和单选类似只是开启了select的多选，不过由于select的多选会导致select框随着值得变多变宽 影响美观
> 还有一种，也存在些问题：
> ![tim 20180616163346](https://user-images.githubusercontent.com/27837058/41497190-180833be-7183-11e8-885c-d8e1817de1be.png)
> 希望能帮到你。。
-------------------------------
下面这是我按照你的写法来的，但是下拉框无法选中选项，能否问下这是什么原因呢
![image](https://user-images.githubusercontent.com/20408773/49114720-e04d8c80-f2d3-11e8-8694-755070ddc3e2.png)
----------------------------------
![image](https://user-images.githubusercontent.com/20408773/49114816-1723a280-f2d4-11e8-93f7-d4e1226ba283.png)
-------------------------------------
![image](https://user-images.githubusercontent.com/20408773/49114837-27d41880-f2d4-11e8-9cf1-cf7b436b811c.png)

**Comment by aiyay** [comment]
> > 单选框的：
> > 主要用到iview tree中提供的 render来绑定 事件，实现虚拟DOM
> > ![tim 20180616162519](https://user-images.githubusercontent.com/27837058/41497134-e68acbe0-7181-11e8-9b1c-fd63de7eaa83.png)
> > **methods** 中定义函数
> > ![tim 20180616162626](https://user-images.githubusercontent.com/27837058/41497138-0b4f0ba8-7182-11e8-91fe-d1165bf0c561.png)
> > 多选框的实现效果不是很理想 ，有两种。
> > 一种和单选类似只是开启了select的多选，不过由于select的多选会导致select框随着值得变多变宽 影响美观
> > 还有一种，也存在些问题：
> > ![tim 20180616163346](https://user-images.githubusercontent.com/27837058/41497190-180833be-7183-11e8-885c-d8e1817de1be.png)
> > 希望能帮到你。。
> 
> 大神，加载数据的时候如何设置值呢，达到选中的效果

就按文档的用例来，在数组对象中设置选中字段
![image](https://user-images.githubusercontent.com/27837058/49122549-d9cd0e00-f2ef-11e8-8a5d-5159b874119a.png)

**Comment by aiyay** [comment]
> > 单选框的：
> > 主要用到iview tree中提供的 render来绑定 事件，实现虚拟DOM
> > ![tim 20180616162519](https://user-images.githubusercontent.com/27837058/41497134-e68acbe0-7181-11e8-9b1c-fd63de7eaa83.png)
> > **methods** 中定义函数
> > ![tim 20180616162626](https://user-images.githubusercontent.com/27837058/41497138-0b4f0ba8-7182-11e8-91fe-d1165bf0c561.png)
> > 多选框的实现效果不是很理想 ，有两种。
> > 一种和单选类似只是开启了select的多选，不过由于select的多选会导致select框随着值得变多变宽 影响美观
> > 还有一种，也存在些问题：
> > ![tim 20180616163346](https://user-images.githubusercontent.com/27837058/41497190-180833be-7183-11e8-885c-d8e1817de1be.png)
> > 希望能帮到你。。
> 
> ## 下面这是我按照你的写法来的，但是下拉框无法选中选项，能否问下这是什么原因呢
> ![image](https://user-images.githubusercontent.com/20408773/49114720-e04d8c80-f2d3-11e8-8694-755070ddc3e2.png)
> ## ![image](https://user-images.githubusercontent.com/20408773/49114816-1723a280-f2d4-11e8-93f7-d4e1226ba283.png)
> ![image](https://user-images.githubusercontent.com/20408773/49114837-27d41880-f2d4-11e8-9cf1-cf7b436b811c.png)

我不太明白你说的无法选择是什么场景，可以给个效果图嘛。 如果是这样子
![image](https://user-images.githubusercontent.com/27837058/49123341-3aaa1580-f2f3-11e8-85f9-a81864bc1733.png)
没有选择框选中的话 要在：
![image](https://user-images.githubusercontent.com/27837058/49123468-a68c7e00-f2f3-11e8-8e0c-8a3d22b1ecfd.png)
设置开启字段 ，如果是 无法回显选中数据是要在这里**data4**中设置**selected:true**用以表示回显选中
![image](https://user-images.githubusercontent.com/27837058/49123526-d89de000-f2f3-11e8-9dec-e21e1754ffd2.png)

**Comment by dengdengdengpan** [comment]
@aiyay 就是下面这种效果。比如，当选中车队管理，再点击菜单录入按钮时，弹出的对话框中父菜单(这个父菜单是一个树形下拉框)会显示当前你选择到的车队管理
![qq20181128-142842-hd](https://user-images.githubusercontent.com/20408773/49133556-896ba580-f31b-11e8-8219-aac2da99967d.gif)

**Comment by aiyay** [comment]
> 选中车队管理，再点击菜单录入按钮时，

那你需要在你的treeTableData里面 找到你要设置选中的字段 加上check:ture字段
![image](https://user-images.githubusercontent.com/27837058/49139735-84175680-f32d-11e8-8056-359131593a28.png) 
![image](https://user-images.githubusercontent.com/27837058/49139940-f720cd00-f32d-11e8-856b-bfb2fe60e7f1.png)

**Comment by dengdengdengpan** [comment]
@aiyay 好的，我去试一试，谢谢

**Comment by aliujb** [comment]
@aiyay 老哥，我严格按照你的方式写的，就是选不中，不知道是怎么回事，麻烦指导下呗，谢谢



![image](https://user-images.githubusercontent.com/46563786/50968827-4e15e680-1517-11e9-80c5-655bb9ada0ba.png)
![image](https://user-images.githubusercontent.com/46563786/50968843-5d952f80-1517-11e9-99af-c696f4ce1013.png)

![image](https://user-images.githubusercontent.com/46563786/50968850-671e9780-1517-11e9-87b2-64e4521c2de0.png)

**Comment by aliujb** [comment]
@dengdengdengpan 这个问题你解决了吗？

**Comment by dengdengdengpan** [comment]
> @dengdengdengpan 这个问题你解决了吗？

https://vue-treeselect.js.org/，你看看这个能满足不你的需求不

**Comment by dengdengdengpan** [comment]
> @dengdengdengpan 这个问题你解决了吗？

你看看这个能满足你的需求不，https://vue-treeselect.js.org/
