### ISSUE TITLE
table的render使用问题 渲染结果为字符串

### ISSUE THREAD

**Issue by Mrli2016** [iview/iview-admin#705]
直接用iview的官方示例的写法是不可行的吗？render渲染出来的组件是字符串，而且render (row, column, index)里面的参数是underdefine，只有通过this.row,this.column,this.index才能正常获取，是iview那边的文档跟这边的使用方法有区别吗？
iview示例：
![shili](https://user-images.githubusercontent.com/27286851/41186489-057b01cc-6bca-11e8-8998-470bda950919.png)

运行结果：
![jieguo](https://user-images.githubusercontent.com/27286851/41186492-0d5c7e02-6bca-11e8-9ac8-e6d1064ddf80.png)

**Comment by lison16** [comment]
你检查下你的写法吧

**Comment by Mrli2016** [comment]
@lison16 我这个是直接将iview官方示例完整复制过来使用的，新建一个.vue文件 直接运行 然后就发现不能正常渲染

**Comment by Mrli2016** [comment]
明白了 最新的iview-admin用的iview已经是2.8.0 而我看的是iview 1.0的文档  现在的渲染方式已经变了 我看了iview 2.0的文档才知道
