### ISSUE TITLE
npm install 报错

### ISSUE THREAD

**Issue by WGKLoveStudy** [iview/iview-admin#708]
下载下项目，npm insinstall报错，具体错误信息如下：
![image](https://user-images.githubusercontent.com/20789962/41218554-1bafd4fc-6d8e-11e8-95b0-311dc48f3a0c.png)

百度了一下，说是可能npm node 版本问题，我的npm 和node 版本信息如下：
![image](https://user-images.githubusercontent.com/20789962/41218491-dd2f39ca-6d8d-11e8-8ed8-ae05f7241e07.png)

前端小白，麻烦帮忙看下，谢谢了~

**Comment by liuhaosheng** [comment]
在webpack.dev.config.js 文件下，第12行  根据你的node 版本自己选择


// fs.write(fd, buf, 0, buf.length, 0, function(err, written, buffer) {}); // node --version > v10.1.0
fs.write(fd, buf, function (err, written, buffer) {}); // node --version < v10.1.0


发自网易邮箱大师


在2018年06月11日 15:43，WGKLoveStudy<notifications@github.com> 写道：

下载下项目，npm insinstall报错，具体错误信息如下：


百度了一下，说是可能npm node 版本问题，我的npm 和node 版本信息如下：


前端小白，麻烦帮忙看下，谢谢了~

**Comment by WGKLoveStudy** [comment]
![image](https://user-images.githubusercontent.com/20789962/41218920-564ccefc-6d8f-11e8-8961-dfdd9df69e62.png)
我看新下的项目里，直接就是这v10.1.0 之上的版本了，和我node版本看起来是匹配的

**Comment by liuhaosheng** [comment]
我刚才就是一直报 这个错，我也是看被人的改的，改完之后我的就可以运行，要不你把 node 的版本降到10 以下试试，
fs.write(fd, buf, function (err, written, buffer) {}); // node --version < v10.1.0




发自网易邮箱大师


在2018年06月11日 15:52，WGKLoveStudy<notifications@github.com> 写道：


我看新下的项目里，直接就是这v10.1.0 之上的版本了，和我node版本看起来是匹配的

**Comment by WGKLoveStudy** [comment]
照着别人的改了下，虽然install 还是报上面的错，但是项目能跑起来了= =！ 谢谢了~

**Comment by chenjichuan** [comment]
我也是新安装，mac系统。多次测试后，node > 10 以上的版本就不要用了，降一下用 8的版本，就不会出现安装不上或者run dev报错问题
