### ISSUE TITLE
Table组件导致浏览器刷新按钮闪烁

### ISSUE THREAD

**Issue by roc-young** [iview/iview-admin#71]
有Table组件的页面加载时，浏览器的刷新按钮和网页title图标会闪烁，表格越多闪烁越多，当页面有多个表格严重影响用户体验。

**Comment by lison16** [comment]
目前没有发现这个现象，有待排查

**Comment by roc-young** [comment]
官方示例就能看到这个现象，https://iview.github.io/iview-admin/#/tables/editableTable，打开这个页面时有明显闪烁，不含有Table组件的页面则不闪烁。
