### ISSUE TITLE
nginx部署问题

### ISSUE THREAD

**Issue by WGKLoveStudy** [iview/iview-admin#715]
按照步骤nginx 部署访问一直出现空白页，各项配置如下：
1. webpack中的public path配置
![image](https://user-images.githubusercontent.com/20789962/41352312-bd3e68ec-6f4b-11e8-8d4d-93ab5bc7264b.png)

2. 打包生成的dist目录结构：
![image](https://user-images.githubusercontent.com/20789962/41352366-e17df65a-6f4b-11e8-90c9-c9c82372a8c4.png)

3.nginx的配置：
![image](https://user-images.githubusercontent.com/20789962/41352399-f5da293e-6f4b-11e8-890d-c2835a153e39.png)

也曾试过把root放到location /中配置 tong'y同样不生效；

4.访问出现的空白页，不报错，nginx access 有日志：
![image](https://user-images.githubusercontent.com/20789962/41352446-16f127ee-6f4c-11e8-82d4-c2e3cca4188d.png)

刚接触vue webpack ，麻烦帮忙看一下

**Comment by enuma0** [comment]
1、把dist目录跟里面的dist文件夹和index放网站的根目录
2、或者把publicPath改成127.0.0.1:8888/dist/dist/

**Comment by WGKLoveStudy** [comment]
不好意思，不太明白这个放到根目录什么意思，我已经在ng conf文件中配置了root不知道算不算；
刚才按照第二种方法试了，没生效…

**Comment by WGKLoveStudy** [comment]
@enuma0 
不好意思，不太明白这个放到根目录什么意思，我已经在ng conf文件中配置了root不知道算不算；
刚才按照第二种方法试了，没生效…

**Comment by WGKLoveStudy** [comment]
问题解决了，publicPath里面没写http协议头= =！

**Comment by Fabriceli** [comment]
你好请问django部署的步骤有吗？按照你们讨论说的配置，访问一直是空白页。我使用了nginx+supervisor+gunicorn 在阿里云上配置的。
