### ISSUE TITLE
左侧菜单栏

### ISSUE THREAD

**Issue by codeItachi** [iview/iview-admin#72]
左侧菜单栏只有两级 可否支持多级

**Comment by lison16** [comment]
之前和Aresn沟通过，因为目前iview的menu菜单不支持更多级菜单，所以如果要用嵌套的菜单是可以实现多级菜单，只不过样式上会有bug，但是不影响使用，如果你业务上有需求，可以使用嵌套菜单

**Comment by NicholasMing** [comment]
能否支持这种菜单
![image](https://user-images.githubusercontent.com/20468003/31922400-4f2548ea-b8a7-11e7-8d09-3249e8832e45.png)

**Comment by lison16** [comment]
Iview-admin目前不会这么做，因为做出来并不美观，但是如果你不在乎样式那可以去做，iview-admin会在iview支持嵌套菜单之后实现
