### ISSUE TITLE
npm  run build 后无法显示，npm run dev 是可以正常显示的

### ISSUE THREAD

**Issue by MaLuns** [iview/iview-admin#729]
![image](https://user-images.githubusercontent.com/31614024/41804757-7640b7da-76ce-11e8-9293-c25b75601236.png)

这个需要怎么配置啊
![image](https://user-images.githubusercontent.com/31614024/41804761-863cc700-76ce-11e8-856d-979070c37a98.png)

**Comment by enuma0** [comment]
webpack.prod.config.js里的publicPath改成你自己的服务器地址：
![image](https://user-images.githubusercontent.com/3970620/41843632-97cea92e-78a0-11e8-9622-d2adca23ec6a.png)

**Comment by MaLuns** [comment]
![image](https://user-images.githubusercontent.com/31614024/41885231-9c2ce704-7929-11e8-8dbc-a5617e7d89d2.png)
![image](https://user-images.githubusercontent.com/31614024/41885392-638135f8-792a-11e8-8ae3-2aa33e265253.png)
打包后这么路径没有变
