### ISSUE TITLE
请教一下，标签里面可以直接调用util 里面的全局方法吗？

### ISSUE THREAD

**Issue by gitors** [iview/iview-admin#736]
描述：
我在util 里面定一个一个方法，在 .vue 里面js 调用就可以，但是直接在img 标签里面写是不行的。
![image](https://user-images.githubusercontent.com/31715318/41947852-a566d7d0-79ec-11e8-9120-5c807cf45f19.png)
![image](https://user-images.githubusercontent.com/31715318/41947860-b32a9d2a-79ec-11e8-86e3-8669952e9e13.png)
下面这样是不行的，。
![image](https://user-images.githubusercontent.com/31715318/41947873-c154a7ba-79ec-11e8-9c74-5b323c34fb2a.png)

我是做后端的，前端不是很熟，哪位大神指点下

**Comment by lison16** [comment]
你的util又没有被vue代理

**Comment by gitors** [comment]
@lison16 好吧，用了其他方法了
