### ISSUE TITLE
关于infor-card的问题

### ISSUE THREAD

**Issue by wasdujk** [iview/iview-admin#739]
将infoCard 作为子组件使用，然后当更改:end-val时countUp抛出了错误
![360 -172341921](https://user-images.githubusercontent.com/26673917/42011292-6246d660-7ac5-11e8-905f-bb574363c519.jpg)

追踪至发生错误的this.counter.update(endVal);
发现这个组件内没有名为update()的方法,但是删除这个方法会导致数值无法实时变动，求解惑

`
<infor-card id-name="users_all" :end-val="member_type_count_a" iconType="android-person" color="#2d8cf0" intro-text="所有用户数量"></infor-card>
`

**Comment by kimoziiiii** [comment]
改成这样没事了，箭头函数作用域的问题。
```js
this.$nextTick(function () {
            let res = transformValue(this.endVal);
            let endVal = res.val;
            this.unit = res.unit;
            let demo = {};
            this.demo = demo = new CountUp(this.idName, this.startVal, endVal, this.decimals, this.duration, this.options);
            if (!demo.error) {
                demo.start();
            }
        });
```
