### ISSUE TITLE
打包出错，请问怎么解决？急！

### ISSUE THREAD

**Issue by warriorBrian** [iview/iview-admin#754]
我拉取了dev里面的代码。我去安装，成功运行起来了。
我什么都没改，就打包试了一下 npm run build ,结果出现这样的情况。根本跑不起来。

版本是**1.3.1版本。**

![tim 20180705212203](https://user-images.githubusercontent.com/28696399/42325873-181dd964-809a-11e8-8231-89c7de68c5ba.png)

**Comment by virnos** [comment]
我执行npm run dev 报错

**Comment by litsun** [comment]
浏览器报的错找不到对应的css和js，应该是打包时的路径配置问题。google 搜索一下 vue 打包路径问题，就会有解决方案了。
