### ISSUE TITLE
富文本编辑怎么上传本地图片？

### ISSUE THREAD

**Issue by web-five** [iview/iview-admin#758]
看了tinymce的文档和代码虽然有看到本地上传相关的，但是还是没有能够理解，并不清楚如何动手，因为对于客户来说，图片源地址他可能不知道怎么去弄，请问下有什么好的办法处理这个问题吗

**Comment by Desever** [comment]
this.editor.customConfig.uploadImgServer = api.baseUrl+'articleFileUpload';

    //图片上传
    editor.customConfig.uploadFileName = 'img';
    this.editor.customConfig.withCredentials = true;
    this.editor.customConfig.uploadImgHooks = {
      success: function (xhr, editor, result) {
          console.log(result);
      }
    }
