### ISSUE TITLE
页面无法在整个浏览器区域展现

### ISSUE THREAD

**Issue by gjwfiza** [iview/iview-admin#768]
按照路由配置教程，设置一个在整个浏览器区域展现的页面，但使用windows.open的形式打开会显示404。然而使用router.js中的preview，替换其中的component为我的页面文件又能正常使用，而且刷新后也不会404，这是为什么呢？

**Comment by lison16** [comment]
请使用vue-router的方式

**Comment by gjwfiza** [comment]
我是使用
`const {href} = this.$router.resolve({
        name: 'foo',
        query: {
          bar
        }
      })
window.open(href, '_blank')`
这样的方式去调用的 @lison16
