### ISSUE TITLE
关于1.3.1版本的权限控制

### ISSUE THREAD

**Issue by batmanSix** [iview/iview-admin#769]
![image](https://user-images.githubusercontent.com/29139411/42500030-cfa31c18-8462-11e8-90ec-0805ea8ab7c6.png)

我在使用iview-admin 权限管理中，如图所示登录设置权限，在route.js 中这样设置多个权限出现访问都不能成功
![image](https://user-images.githubusercontent.com/29139411/42500114-0237938e-8463-11e8-8f61-e4bd9ddc2218.png)

![image](https://user-images.githubusercontent.com/29139411/42500126-0c94fccc-8463-11e8-83b9-70504d43d245.png)

有没有大佬解决了求指导

**Comment by lison16** [comment]
你可以参考2.0的权限体系
