### ISSUE TITLE
希望添加响应式（自适应）布局解决方案

### ISSUE THREAD

**Issue by gitzhangfugui** [iview/iview-admin#77]
虽然iview定位为桌面应用，只提供后台管理，但对供应商和客户来说，就是竞争力
现在市面上桌面（台式机、笔记本）、平板、手机的使用比例还是分布比较均衡的
想一想，如果你经常桌面办公，但是没有资源允许你马上迁移到移动端。如果现在有一个过度方案，加一个android、ios壳，也许这盘棋就活了。
先写到这里吧，谢谢

[https://github.com/epicmaxco/vuestic-admin](https://github.com/epicmaxco/vuestic-admin)
[https://github.com/mrholek/CoreUI-Vue](https://github.com/mrholek/CoreUI-Vue)
[https://github.com/vue-bulma/vue-admin](https://github.com/vue-bulma/vue-admin)

**Comment by lison16** [comment]
谢谢您的建议，iview-admin在下一个大版本会考虑使用响应式布局。

**Comment by gitzhangfugui** [comment]
@lison16 嗯，同时加班狗，真的说声谢谢

**Comment by onesez** [comment]
加油！同样期待iView中所有响应式布局！

**Comment by baryon** [comment]
顶端的菜单如何支持响应式布局更好？
