### ISSUE TITLE
2.0 branch中在lib下对axios包装使用的interceptors.response处理有点问题

### ISSUE THREAD

**Issue by cw1427** [iview/iview-admin#779]
// 添加响应拦截器
            instance.interceptors.response.use((res) => {
                let { data } = res
                const is = this.destroy(url)
                if (!is) {
                    setTimeout(() => {
                        // Spin.hide()
                    }, 500)
                }
                if (!(data instanceof Blob)) {
                    if (data.code !== 200) {
                        if (data.code === 401) {
                            Cookies.remove(TOKEN_KEY)
                            window.location.href = '/#/login'
                            Message.error('Login failed')
                        } else {
                            if (data.msg) Message.error(data.msg)
                        }
                        return false
                    }
                }
                return data
            }, (error) => {
                Message.error('internal error inner')
                    // 对响应错误做点什么
                return Promise.reject(error)
            })

看这样子，内部  data对象应为axios的response的对象，好像它并没有code属性？ 另外， 我觉得这里的处理不够common， 并不适合加到全局的interceptor中。 我是否可以去掉它们。

**Comment by cw1427** [comment]
let { data } = res.data   这样可能还对一点。总之，不喜欢这样的非common的处理放在全局interceptor中处理。 有点过度包装。

**Comment by Thomas1987** [comment]
if (!(data instanceof Blob))  这个判断得应该都可以去掉，可以根据API 返回值 来自己添加拦截！！

**Comment by cw1427** [comment]
got it, thx.  但是这个算是iview-admin 框架里的，好多地方我是直接改掉，只是后续升级不好办。 个人觉得iveiw-admin框架设计的还不够好，好多都需要根据项目需要调整，但是又没有提供好的扩展调整方式。即需要直接去动它的代码。这个对后续升级不友好。希望可以多花心思在框架灵活性，扩展性设计上。
