### ISSUE TITLE
部署上打开的接口地址跟服务器地址相同

### ISSUE THREAD

**Issue by liucien** [iview/iview-admin#783]
首先说明一下这个问题在npm run dev的时候没有，就是准备部署的时候npm run build会这样
我的项目地址
![image](https://user-images.githubusercontent.com/32785166/42874008-a5647ec8-8ab2-11e8-8319-bb9a29f894d9.png)
我所请求的接口地址
![image](https://user-images.githubusercontent.com/32785166/42874041-b3ee801a-8ab2-11e8-8554-9d23fc1c368f.png)
但是打开后没有请求接口地址而是项目的地址
![image](https://user-images.githubusercontent.com/32785166/42874112-e298ec5c-8ab2-11e8-85b7-6f8d7c95ac5f.png)

**Comment by liucien** [comment]
有没有成功部署过的大佬出来指点一下~~！

**Comment by GryffindorMuggle** [comment]
本地环境访问localhost:8080和127.0.0.1:8080可以访问，本地ip+端口无法访问怎么解决

**Comment by wangbaojin2008** [comment]
您好 问题解决了吗？请联系我  qq 87735612
