### ISSUE TITLE
@keydown.enter="handleLogin"  调用导致userName.trim() 没有定义的错误！！

### ISSUE THREAD

**Issue by Thomas1987** [iview/iview-admin#786]
登录的父组件中 @keydown.enter="handleLogin" 这里调用父组件的方法 获取不到用户名和密码，回车事件会导致 js错误。

是否应该改用$refs调用子组件的！！
<template>
  <div class="login" @keydown.enter="handleLogin">
    <div class="login-con">
      <Card icon="log-in" title="欢迎登录" :bordered="false">
        <div class="form-con">
          <login-form @on-success-valid="handleSubmit"></login-form>
          <p class="login-tip">输入任意用户名和密码即可</p>
        </div>
      </Card>
    </div>
  </div>
</template>

**Comment by lison16** [comment]
down
