### ISSUE TITLE
libs>tools.js>getCommonString  有个bug

### ISSUE THREAD

**Issue by iuvword** [iview/iview-admin#788]
export const getCommonString = (arr1, arr2) => {
  let len = Math.min(arr1.length, arr2.length)
  let i = -1
  let res = []
  while (++i < len) {
    const item = arr2[i]
    if (arr1.indexOf() > -1) res.push(item) // 这句条件是不是应该改为 （arr1.indexOf(item) > -1）
  }
  return res
}

**Comment by lison16** [comment]
down
