### ISSUE TITLE
iview如何复制粘贴

### ISSUE THREAD

**Issue by dolphinfine** [iview/iview-admin#79]
打算使用这个模版进行开发，有复制粘贴的需求，具体来说就是复制一个表格到粘贴板，粘贴的时候表格还是原来的样子，边框内容都没变，看到package.json有clipboard这个依赖，但是好像并没有在项目中使用。请问如何复制粘贴？最好出一个demo。自己也尝试了一下，到目前位置还未探索成功

**Comment by lison16** [comment]
这个功能还没有做demo，很快出
