### ISSUE TITLE
Select组件添加 label-in-value属性后执行 on-change事件问题

### ISSUE THREAD

**Issue by iceonion** [iview/iview-admin#790]
select组件异步获取数据，添加label-in-value属性后 ，执行on-chang事件时会执行三次，只有第一次的数据是正确的。

>
{value: "yuantong", label: "圆通"}
{value: "圆通", label: ""}
{value: "", label: ""}

**Comment by lison16** [comment]
这个可以到iview的仓库提，确定是不是iview的bug
