### ISSUE TITLE
Bug: iview-admin-1.3.1 in Node.js 10.7.0

### ISSUE THREAD

**Issue by baoanj** [iview/iview-admin#803]
```js
fs.write(fd, buf, 0, buf.length, 0, function(err, written, buffer) {});
```
[Code Position](https://github.com/iview/iview-admin/blob/dev/build/webpack.dev.config.js#L12)

### [fs.write(fd, string[, position[, encoding]], callback)](https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fs_write_fd_string_position_encoding_callback)

Version | Changes
-- | --
v10.0.0 | The callback parameter is no longer optional. Not passing it will throw a TypeError at runtime.

**Comment by lison16** [comment]
node版本问题，换8.x版本试试
