### ISSUE TITLE
文档问题！

### ISSUE THREAD

**Issue by Freelili** [iview/iview-admin#807]
1、首先非常感谢，这个团队的付出！这个项目非常棒！
2、我建议可以写一个文档或者简易的教程，说明设计的思路和坑，可能会更棒！
3、我想问一下，iview里面有没有做的比较好的树表和嵌套明细表（一个表里面嵌套另外一个表（附表））求推荐
4、我想问一下，iview里面有没有分组表（表里面按照一个字段或者多个字段进行分组），求推荐

**Comment by spencer-live** [comment]
https://lison16.github.io/iview-admin-doc/
2.0 的已经有啦
