### ISSUE TITLE
动态加载路由

### ISSUE THREAD

**Issue by codeItachi** [iview/iview-admin#81]
怎样实现动态加载路由

**Comment by lison16** [comment]
动态路由在Iview-admin中有demo

**Comment by codeItachi** [comment]
@lison16  左侧的菜单栏 根据权限后台提供 动态加载的

**Comment by lison16** [comment]
是的

**Comment by codeItachi** [comment]
@lison16 我看到router.js都是写死的  怎样动态加载 求解

**Comment by lirahalu** [comment]
同求

**Comment by ShawshankLin** [comment]
好像是2.3的路由加了个addRouter方法

**Comment by lison16** [comment]
后面会做个demo来演示

**Comment by weechang** [comment]
> 后面会做个demo来演示

所以做了吗？我想要搞一个从后台动态加载的菜单。但是发现好难！！！

**Comment by codeItachi** [comment]
早之前的项目做了



pjt463517705@163.com
 
发件人： 耒耒耒耒耒
发送时间： 2019-02-21 11:37
收件人： iview/iview-admin
抄送： The king of man; Author
主题： Re: [iview/iview-admin] 动态加载路由 (#81)
后面会做个demo来演示
所以做了吗？我想要搞一个从后台动态加载的菜单。但是发现好难！！！

**Comment by simon9124** [comment]
已实现后端生成动态路由&左侧动态菜单：https://github.com/simon9124/iview-dynamicRouter
