### ISSUE TITLE
项目部署到阿里云主页打不开，显示Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by Fabriceli** [iview/iview-admin#810]
########################################################
本人在issue当中看到了诸多关于生产打包路径不对,字体图标引用错误的问题.以下是我的解决方案提供给大家参考:
1.webpack.base.config.js

17行修改为: path: path.resolve(__dirname, '../dist')
目的:消除冗余dist目录

2.webpack.prod.config.js

21行改为publicPath: './', // 修改 https://iv...admin 这部分为你的服务器域名
目的:将静态资源目录改为当前目录

80行改为filename: './index.html',
目的:应对上面改动移动入口html 使得入口内引用正确
########################################################

### 2. 部署步骤：npm run build
将dist文件夹放到django目录下，重启项目

### 3. 项目启动后，显示空白页，看到提示信息是**Uncaught SyntaxError: Unexpected token <**

![iview django error](https://user-images.githubusercontent.com/13508022/43366394-06db32a8-9370-11e8-81f6-2887780e5914.png)

Thanks

**Comment by Fabriceli** [comment]
直接部署我本地新建的vue项目到阿里云，可以正常显示。

**Comment by lison16** [comment]
如果是admin1.x版本，可以设置publicPath，如果是2.0版本，可以设置baseUrl，设为相对路径，然后用ngix指向

**Comment by Fabriceli** [comment]
@lison16, admin1.3.1版本的，我设置了publicPath：“http://我的域名/dist”这样的，一直是404，请问具体怎么配置？Nginx要重定向设置吗？谢谢
