### ISSUE TITLE
affix组件无法使用

### ISSUE THREAD

**Issue by Mrli2016** [iview/iview-admin#811]
是不是在内部容器里面无法使用affix组件

代码：
```javascript
<template>
   <div>
        <Affix :offset-top="100">
            <span class="demo-affix">Fix the position at the top of 100px at the top</span>
        </Affix>
        <row>.....<row>
    </div>
</template>
```
效果：
![2b5043d2-63fe-4fe8-8a6b-0e07507ddcb8](https://user-images.githubusercontent.com/27286851/43385333-177f2350-9413-11e8-8261-c0a0d989f395.png)
![2fc95413-4d5a-48ef-8476-a0ed7b18fdc1](https://user-images.githubusercontent.com/27286851/43385340-1f4749e6-9413-11e8-8509-bd1808fb4d90.png)

**Comment by lison16** [comment]
因为在Main组件中展示的页面实际是放到一个DIV容器里了，后面可能封装个组件，可以控制DIV容器滚动到顶部

**Comment by zhangfugui727** [comment]
@lison16 有方案帮忙看看吗
