### ISSUE TITLE
2.0 在ubuntu上install dependency有个小警告,不过不碍事

### ISSUE THREAD

**Issue by xinglu1985** [iview/iview-admin#813]
~/Works/iviewadmin2/iview-admin$ cnpm install
⠙ [14/30] Installing @babel/core@7.0.0-beta.47
WARN node unsupported "node@v8.10.0" is incompatible with iview-area@1.5.17 › iview@2.14.3 › v-click-outside-x@^3.0.0, expected node@>=8.11.0
⠏ [19/30] Installing webidl-conversions@^4.0.2platform unsupported @vue/cli-plugin-unit-mocha@3.0.0-rc.10 › mocha-webpack@2.0.0-beta.0 › chokidar@2.0.4 › fsevents@^1.2.2 Package require os(darwin) not compatible with your platform(linux)
[fsevents@^1.2.2] optional install error: Package require os(darwin) not compatible with your platform(linux)
✔ Installed 30 packages
✔ Linked 1015 latest versions

**Comment by lison16** [comment]
可能是node版本的原因
