### ISSUE TITLE
左侧菜单高度大于界面高度时，菜单没有滚动条

### ISSUE THREAD

**Issue by zhang8h** [iview/iview-admin#839]
左侧菜单高度大于界面高度时，菜单没有滚动条，无法点击超出屏幕界面的菜单

**Comment by SuperFate-KJ** [comment]
我也遇到这个问题，三级菜单比较多，展开后超出界面后没有滚动条

**Comment by ZH-Hf** [comment]
iview-admin-template\src\view\main\main.vue
在Sider标签 添加style="overflow: auto;" 可以解决,但是原生滚动条好丑啊

**Comment by lison16** [comment]
看一下2.0分支最新代码，刚刚修复了，能滚动，而且看不到滚动条

**Comment by ZH-Hf** [comment]
好的谢谢

**Comment by zhang8h** [comment]
非常感谢

**Comment by zhang8h** [comment]
出现了个新问题，折叠菜单后，鼠标移到菜单图标上没有二级菜单显示了   @lison16

**Comment by lison16** [comment]
这个是因为超出被隐藏了，稍等修复下

**Comment by lison16** [comment]
已修复，看2.0分支

**Comment by zhang8h** [comment]
@lison16 已验证确实好了，效率真高！！ 还有一个问题，折叠菜单后如果一级菜单超过屏幕高度，还是没有滚动条，^_^，这个解决就完美了^_^

**Comment by xinglu1985** [comment]
@zhang8h 你这个项目一级菜单真多啊~ 专业前端试吗,哈哈

**Comment by zhang8h** [comment]
目前没有那么多，只是测试到了O(∩_∩)O哈哈~
