### ISSUE TITLE
可否设置在手机打卡时候不自动缩放

### ISSUE THREAD

**Issue by hihuangwei** [iview/iview-admin#84]
可否设置在手机打卡时候不自动缩放，手机屏幕不够大，打开全部都缩在一起了
![_20171025124733](https://user-images.githubusercontent.com/3166799/31981001-deb66e86-b982-11e7-81a6-1a19aa2ee7d7.png)

**Comment by lison16** [comment]
现在没有做移动端的适配。

**Comment by hihuangwei** [comment]
我不是说移动端适配，在小屏幕的设备打开，就不要自动缩放，一缩放  全部都粘在一起了

**Comment by lison16** [comment]
如果你有这个需求可以自己设置

**Comment by hihuangwei** [comment]
![screenshot_2017-10-25-13-28-32-230_com android chrome](https://user-images.githubusercontent.com/3166799/31981986-e62e1834-b988-11e7-8f57-bc827076381f.png)
![screenshot_2017-10-25-13-22-41-599_com android chrome](https://user-images.githubusercontent.com/3166799/31982029-201d8bc4-b989-11e7-83bc-2dd0c9f63b43.png)
像iview 文档这样就挺和谐的

**Comment by yakun0622** [comment]
把模板文件index.ejs里的一个meta标签去掉就行了
`<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0">`
