### ISSUE TITLE
api.request.js 中为什么要做一个请求队列？

### ISSUE THREAD

**Issue by iijx** [iview/iview-admin#848]
看了下 api.request.js 的代码， 里面是对axios的封装。

看到做了个请求队列，想请教下这里这么做的考虑是什么。
因为我以往时是直接 创建一个axios实例(或配下拦截器)，然后直接导出。

想了很久，没想出请求队列有什么好处。

**Comment by litsun** [comment]
进入一个页面，如果需要请求两个接口或多个的时候，这个时候用请求队列就可以统一响应 加载中....  事件了，是这个用处吗？

**Comment by lison16** [comment]
是的

**Comment by iijx** [comment]
还是有点。。不太。。明白。 @litsun 可以举个简单例子说说吗。给你点赞👍  :)

**Comment by litsun** [comment]
@iijx 
```js
export default {
  methods: {
    fetchData1 () {
     open.alert("数据加载中...")
     this.$http.get()
    },
    fetchData2 () {
      open.alert("数据加载中...")
      this.$http.get()
    }
  }
}
```
页面加载时，如果需要向后台请求两次数据接口，那就会弹出两次加载中。如果用请求队列的方式，那我们就可以统一处理响应事件了。以下是我的项目代码，没有使用请求队列，所以用了setInterval 每秒查询一次是否两个接口已响应，这样的代码就很不优雅。

![image](https://user-images.githubusercontent.com/14902509/43950533-1bd24ab4-9cc3-11e8-9c27-8ca702f7efd0.png)

**Comment by iijx** [comment]
@litsun 
其实弹两次加载中，仅仅这个问题感觉没有必要这么做。我常用的是节流函数处理，只需对“提示函数(就是你这里的open.alert)”做一层封装。就可以控制给定时间内最多触发一次。

比如：
```
const Message = throttle( msg => open.alert(msg), 3000); // 3s内最多触发一次
```
后面只需要用Message('加载中')来提示就可以，至于throttlle函数的实现，网上有很多，lodash等库都自带。
