### ISSUE TITLE
侧边栏为什么加上过渡反而出现了边框很长

### ISSUE THREAD

**Issue by wangdabaoqq** [iview/iview-admin#86]

**Comment by lison16** [comment]
边框很长是什么意思，能详细说下嘛

**Comment by felixcoon** [comment]
应该是个bug。在加入了菜单展开/折叠的动态效果后，当菜单折叠起来的时候，鼠标放在具体菜单的图标上，出现的具体菜单是占满整个横向全屏的。

<img width="1440" alt="2017-10-26 01 36 16" src="https://user-images.githubusercontent.com/33035306/32013659-598bdc7a-b9ee-11e7-80c5-83796f40a4fe.png">

**Comment by lison16** [comment]
你的iview版本是多少

**Comment by wangdabaoqq** [comment]
我看的线上的地址

**Comment by felixcoon** [comment]
我白天用公司iMac上的Safari，显示正常。晚上在家里MacBook上的Safari，显示不正常。跟缓存有关？

**Comment by lison16** [comment]
建议清理下缓存看下，在线的我这看没问题
