### ISSUE TITLE
HMR (Hot module reload) not working 热重载功能不好使

### ISSUE THREAD

**Issue by maakey** [iview/iview-admin#868]
####  iview-admin的热重载功能无法实现
node v9.4.0, v10.8.0
npm v5.6.0, v6.2.0
windows 7, windows 10
vue 2.5.10
vue/cli 3.0.0
iview 3.0.0
####  步骤重现：
* git clone https://github.com/iview/iview-admin.git
* npm install
* npm run dev
* 打开网页http://localhost:8081/ 
* 修改任意vue文件，页面没有自动更改
* 查看chrome的console
* 并没有新的文件加载，但是websocket的frames正常接收数据，如果frames的type为errors，页面也会正常报错，但是frames的type为hash，页面并不会更新
#### 期望
修改vue文件时，页面会同步更新
#### 实际
修改vue文件时，页面并不会同步更新，只能每次都刷新

**Comment by zpzxgcr** [comment]
最新稳定版 v10.8.0

**Comment by lison16** [comment]
刚刚试了下node10.8，热重载也没问题，检查下你的环境吧

**Comment by zpzxgcr** [comment]
忘记说了 我是刚clone下来的简化版模板 是没有热重载的 @lison16

**Comment by maakey** [comment]
node v9.4.0, v10.8.0都试过了，不好使，每次更新完代码得刷新浏览器页面才行

**Comment by maakey** [comment]
* node v10.8.0
* npm v6.2.0
* iview 3.0.0
* iview-admin v2.0-beta.2
* vue/cli 3.0.1
热重载还是不好使，无论是修改less文件，还是vue文件，都不好使
````
vue.config.js

devServer: {
  hot: true,
  inline: true,
  proxy: {
    '/api': {
      target: 'http://127.0.0.1:90/',
      secure: false
    }
  }
}
````

**Comment by nabaonan** [comment]
更新一下packagejson中的cli依赖，到3.0.1好像就好了，我昨天更新了一下发现可以了

**Comment by maakey** [comment]
@nabaonan 的方法，不用cnpm安装，热重载好使，如果墙的厉害，用npm无法正常安装，使用 --registry https://registry.npm.taobao.org来安装，亲测也有效果。。cnpm的确挺坑。

**Comment by xiaojingyuaner** [comment]
+1

**Comment by WALLE729** [comment]
node 版本10.8.0  npm安装的，淘宝仓库和官方仓库都试过了，还是不行
