### ISSUE TITLE
表格编辑模块没有啊

### ISSUE THREAD

**Issue by usering1995** [iview/iview-admin#877]

**Comment by lison16** [comment]
看文档，有编辑功能

**Comment by usering1995** [comment]
只有多功能表格！
没有
表格
      可拖拽排序
      可编辑表格
     行内编辑
     单元格编辑
     可搜索表格
     表格导出数据
     导出为Csv文件
     导出为Xls文件
     表格转图片

**Comment by lison16** [comment]
多功能表格就可以编辑啊

**Comment by usering1995** [comment]
嗯嗯，我知道！可编辑单元行那种的怎么实现！点编辑按钮修改的！

**Comment by lison16** [comment]
如果你要用这个，可以去dev分支拿

**Comment by usering1995** [comment]
好的，明白！
