### ISSUE TITLE
点击动态路由，点击 了解详情，关闭了解详情，为什么不是回到  上一个页面？

### ISSUE THREAD

**Issue by aizhimin** [iview/iview-admin#88]
点击动态路由，点击 了解详情，关闭了解详情，为什么不是回到  上一个页面？

而是回到了最开始的一个页面

**Comment by lison16** [comment]
这个是当时设计的一个不太合理的地方吧，当时设计的是关闭当前打开的标签会调到标签列表的第二个标签页，后面会改一下
