### ISSUE TITLE
你好，我想问下你们webpack配置server的设置

### ISSUE THREAD

**Issue by YTU94** [iview/iview-admin#90]
原因是这样我想用http-proxy-middleware进行跨域代理，结果总是问题，看了下请求信息，用两个一个样的接口测试vue-cli端口号是自己写死的所以请求Remote Address： [::1]:8088，你们的请求Remote Address： 127.0.0.1:8088 是这样的，端口号也是在变的，想问下你们这个用的什么server,启动配置信息，我没找到，谢谢！

**Comment by lison16** [comment]
请参考https://github.com/iview/iview-admin/issues/75
