### ISSUE TITLE
一个发自肺腑感人至深的问题

### ISSUE THREAD

**Issue by Lay3** [iview/iview-admin#916]
辗转反侧夜不能寐，问题如下：
1、master与2.0内容一致吗？
2、下了demo发现2.0版本缺失了很多README里面描述的功能，想使用完整版该使用哪个版本？
3、文档简略了那么一点点。。

总体：体验蛮好，会向身边朋友推荐。

**Comment by DoctorWei** [comment]
README里面描述的功能是1.0版本的。2.0暂时没有这么丰富，不过可以自行集成进去。

**Comment by WuHuaJi0** [comment]
我也发现2.0 比 1.x 少了好多东西
