### ISSUE TITLE
[加强]iview-admin 按需加载js

### ISSUE THREAD

**Issue by anjia0532** [iview/iview-admin#94]
![snipaste20171026_110513](https://user-images.githubusercontent.com/15098916/32033405-06132bec-ba3f-11e7-811e-38d07ac92e34.png)
现在的vendors.js已经高达900多K了，能改成按需加载么？

js依赖图  见 http://ww1.sinaimg.cn/large/afaffa71ly1fkvh7e70xxj21h90qdq9y.jpg

**Comment by ywzhaiqi** [comment]
这已经是按需加载。

**Comment by anjia0532** [comment]
比如，像是echarts,tinymce.js貌似没必要打到vendors.js里吧？毕竟编辑器，和报表不一定都会用上。真正需要的生活，再加载不行么？

**Comment by ywzhaiqi** [comment]
你可以新建另一个 vendors.js

**Comment by anjia0532** [comment]
恩，好的，谢谢
