### ISSUE TITLE
左侧菜单动画的建议

### ISSUE THREAD

**Issue by maysoft** [iview/iview-admin#95]
关于菜单动画，现在左侧菜单收缩的时候没问题，展开的时候因为菜单文字的wrap的效果，导致下面会短暂出现横向滚动条，菜单文字也会由两行闪一下变为1行。因为本人不太懂css怎么修改，所以这块能优化下吗

**Comment by lison16** [comment]
这个问题在windows下可能比较明显，后面我们再优化下
