### ISSUE TITLE
表格拖拽排序的问题

### ISSUE THREAD

**Issue by ouzhenlin** [iview/iview-admin#97]
大神，表格拖拽排序，拿到的还是原始的数据，怎么拿到拖拽后的数据？

**Comment by lison16** [comment]
你是可以拿到拖拽了哪个数据，从哪拖拽到哪的，所以本来想用户根据业务需求自己去做更新数据的，不过后面我来做一下吧

**Comment by ouzhenlin** [comment]
就是拖拽排序，拖拽之后拿到的tableData数据和拖拽之前是一样的，我本以为拖拽end之后你会返回一个拖拽后的数据，可是没有，我今天试了vuedraggable这个依赖，是可以双向绑定的，拖拽结束后会返回一组排好序的数据。</捂脸>你这个我弄了好久没有弄出来（拖拽后更新数据）</捂脸>

**Comment by lison16** [comment]
后面会对拖拽表格做一个修改，改为v-model绑定

**Comment by guoqiang998** [comment]
@lison16 
感觉现在的拖拽好像不太人性化，也许是我自己没搞明白。

1. 拖拽进行时，能否在每行最前面动态显示一个标签，拖拽到了哪一行能够一目了然；
2. 如果我不想整行拖拽，而是只在最后一列加button，按住button拖拽要怎么做呢？
3. 如果开启了拖拽功能，table内容就没办法选中copy

上面三点如果能有办法改善就太好了。
