### ISSUE TITLE
路由跳转的bug问题

### ISSUE THREAD

**Issue by zzcyrus** [iview/iview-admin#98]
比方说点击如下链接

① http://localhost:8080/#/advanced-router/

应该自动跳转到第一个子菜单

② http://localhost:8080/#/advanced-router/mutative-router

在成功一次之后，再输入链接① ，则不能正常跳转，在输入链接① ，又正常了，基本是一次正常一次不正常。。

**Comment by lison16** [comment]
你好，按照你说的我复现了几遍，每次输入连接①都会正确跳转到第一个子菜单也就是‘动态路由’，不知道你现在问题还存在吗
