### ISSUE TITLE
项目更新太慢，花都快谢了

### ISSUE THREAD

**Issue by qiujy** [iview/iview-admin#998]
iview团队的大大们，精力都投入到写iview了吗？这个iview-admin进度太慢啊，这会掉粉的。

**Comment by lison16** [comment]
不好意思啊，admin作者不是专职做iview开发的，有自己的工作要做

**Comment by kuailemy123** [comment]
准备什么时候发布2.0正式版呀

**Comment by RedStarGroup** [comment]
是不是主要精力在搞付费论坛，这个项目不再维护了？

**Comment by lison16** [comment]
不好意思啊，可能你没有搞清楚，付费论坛是Aresn在搞，收入也是Aresn的，iview-admin是我（Lison) 在搞，但是我不是专职搞iview的，没有收你的钱，所以没有义务被你催着更新，而且很多功能和bug我也在不停的修复和更新。
